### ISSUE TITLE
Audio Sounds Soft and Bass-less

### ISSUE THREAD

**Issue by massatt212** [ublue-os/bazzite#1015]
### Describe the bug

Audio Sounds Soft and Bass-less
Kinda flat also

### What did you expect to happen?

I did a fresh install of bazzite with new iso Bazzite 40

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:2f07121f3fb4ec6e54066aa738f6fcbcf230a83433f3c9c19dccb2e481df284c
                  Version: main (2024-04-24T19:20:01Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:a802d8a39d5230440663dd8f06eea9d3ce27e722c9ffa12f8d59432283fcdc41
                  Version: 39.20240414.0 (2024-04-14T21:10:41Z)
```

### Hardware

OptiPlex 3040

**Comment by Tau5** [comment]
It also happens on the Steam Deck speakers

**Comment by KyleGospo** [comment]
Should be fixed in the latest update, issue with a steam deck package overriding Hardware it shouldn't have.

**Comment by massatt212** [comment]
it works great, thanks for the quick fix

**Comment by Tau5** [comment]
I've updated (stable) and it's still not fixed (at least with the steam deck speakers). Is the fix only on the testing branch or is it just that it is not fixed?
