### ISSUE TITLE
Internal Drive listed twice on HTPC/-Deck build 

### ISSUE THREAD

**Issue by Brunvik** [ublue-os/bazzite#1098]
### Describe the bug

When looking at the avaible hard drives in Steam settings, the main drive is listed twice.
The First is usable as spected but the second entry for this Drive is prompting to format it to use it with Steam.

This happens inside the gamescope Session, while on regular desktop and the desktop Steam client everything is normal.

### What did you expect to happen?

To only see the primary hard Drive once
![PXL_20240509_000344807](https://github.com/ublue-os/bazzite/assets/141272014/d95f3d16-8d45-44d7-a4e9-5cf4583821ca)
![PXL_20240509_101046172 MP](https://github.com/ublue-os/bazzite/assets/141272014/0f11897c-ee12-4686-8a88-a0744026a09d)
![PXL_20240509_101201426](https://github.com/ublue-os/bazzite/assets/141272014/d3518661-6feb-4333-8a8e-d6196a1a761d)

**Comment by unicornsandcandies** [comment]
> ### Describe the bug
> 
> When looking at the avaible hard drives in Steam settings, the main drive is listed twice. The First is usable as spected but the second entry for this Drive is prompting to format it to use it with Steam.
> 
> This happens inside the gamescope Session, while on regular desktop and the desktop Steam client everything is normal.
> ### What did you expect to happen?
> 
> To only see the primary hard Drive once ![PXL_20240509_000344807](https://private-user-images.githubusercontent.com/141272014/329209288-d95f3d16-8d45-44d7-a4e9-5cf4583821ca.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MjIwNDAsIm5iZiI6MTcxNTUyMTc0MCwicGF0aCI6Ii8xNDEyNzIwMTQvMzI5MjA5Mjg4LWQ5NWYzZDE2LThkNDUtNDRkNy1hNGU5LTVjZjQ1ODM4MjFjYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMlQxMzQ5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YzkwMDE3Njg2OWIwY2U2MWZjMTA2OTY3Nzc5OGYxNzg5ZmU3MDhiNmQyZTNlMmNlMjk1MTk3MTYwNzZmNzdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.y_vLFy9to0P7ZGHWjrlSA60j58viZEFSegUWc1EMWgc) ![PXL_20240509_101046172 MP](https://private-user-images.githubusercontent.com/141272014/329209985-0f11897c-ee12-4686-8a88-a0744026a09d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MjIwNDAsIm5iZiI6MTcxNTUyMTc0MCwicGF0aCI6Ii8xNDEyNzIwMTQvMzI5MjA5OTg1LTBmMTE4OTdjLWVlMTItNDY4Ni04YTg4LWEwNzQ0MDI2YTA5ZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMlQxMzQ5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZGY3YjBlOTNkZmQ1N2QxNGVhNTI1YTI5ZmY4NTZlNDZhY2ZiMTczMTY2MDRiYTdjNmEzNDg1ZDhkYTYzZmI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hyrOdpH71etsrDfL8ZuO3J9ByMZiHnBhjxLuAFab61I) ![PXL_20240509_101201426](https://private-user-images.githubusercontent.com/141272014/329209999-d3518661-6feb-4333-8a8e-d6196a1a761d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MjIwNDAsIm5iZiI6MTcxNTUyMTc0MCwicGF0aCI6Ii8xNDEyNzIwMTQvMzI5MjA5OTk5LWQzNTE4NjYxLTZmZWItNDMzMy04YThlLWQ2MTk2YTFhNzYxZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMlQxMzQ5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZDRhZWE2ZTA0MmIwOWQ5ZWUwMGFlOThmZmFiYmRjOTFkOTdmOGUxZjZjZThkY2MxZjIzNjE3NDIzZWFmZTE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dw94uQD_UmxEkv4jsr8X3rgEB0sQuboNkZ-xvNHQD7A)
> ### Output of `rpm-ostree status`
> 
> _No response_
> ### Hardware
> 
> _No response_
> ### Extra information or context
> 
> _No response_

Can confirm. Also if you run boot menu "minus and power button", there's a bazzite and fedora entry

**Comment by Brunvik** [comment]
I have this on Steam Deck 256GB too now

**Comment by lm209** [comment]
Yes same Problem on my Steam Deck 256GB LCD

**Comment by RodoMa92** [comment]
Same here

**Comment by KyleGospo** [comment]
This will be fixed with the next build

**Comment by RodoMa92** [comment]
I can still reproduce this on latest stable. Do I need to change something else manually?

**Comment by Brunvik** [comment]
Yep it is back for me too on both my LGO and my HTPC

**Comment by dazchipsugar** [comment]
I've got the same error on a fresh install on my Steam Deck. This is only in Gaming mode though.. Desktop mode doesn't have this issue.

**Comment by Jean-PierreJ** [comment]
@KyleGospo Confirming this exists on a brand new install with the latest build, as have a number of others.

I’m noticing, however, that this issue is marked as “Closed”. Is it possible to reopen this, please?

**Comment by GARGZUL** [comment]
I can confirm this bug is still happening as of today.

Fresh install of bazzite-deck-gnome on a 512Go OLED Steam Deck, disk encrypted during install.

As others, in gamescope session my internal SSD appear twice. One is fully functional, the second entry appear empty with prompt to format.

**Comment by Brunvik** [comment]
I can confirm too, still a thing :(

**Comment by Jepl4r** [comment]
This still happens with the latest release.

**Comment by CheckYourFax** [comment]
Does this still happen in latest release?

**Comment by RodoMa92** [comment]
> Does this still happen in latest release?

Yep, still there.

**Comment by Saafork** [comment]
Issue is still happening as of latest bazzite -deck image from site

**Comment by cheesepaulo** [comment]
Issue is still happening as of latest bazzite -deck image from site.
Yep, me too.

**Comment by shikiwoo** [comment]
Issue still present on bazzite -deck (Gnome), fresh install.

**Comment by kuynh** [comment]
Issue present on Bazzite-deck KDE as well

**Comment by natecox** [comment]
Also seeing this on a fresh install.

**Comment by McBrideMusings** [comment]
Same, seeing this on a fresh install

**Comment by argeualcantara** [comment]
Just installed Bazzite-deck on my ROG Ally, 2 weeks ago. Still looks like this with 2 drives on gamescope.

**Comment by Jepl4r** [comment]
Seems the issue was fixed with the latest Steam client update.

Both my Legion Go 2 and Desktop PC only show one entry for the internal drive.
![image](https://github.com/user-attachments/assets/beccb4b6-7903-477d-8d26-8924576823ca)

**Comment by ALEXoicu** [comment]
Still not fixed for me, installed latest stable today(11 April 2026)

**Comment by Duveyduv** [comment]
Still not fixed. Having this issue as well. Is this related to auto-mounting?
