### ISSUE TITLE
Xbox Wireless Dongle just don't work correctly.

### ISSUE THREAD

**Issue by ArnauS197** [ublue-os/bazzite#1418]
### Describe the bug

When I turn on my PC from sleep, it just don't work, the only way is to unplug and plug the USB dongle. Sometimes it happens even just turning on the PC, like 2-3 times of every 10. It's so annoying, it happens on both Chimera and Bazzite, controller Elite 2 with FW upgraded to the latest version. There's any alternative or fix planned? Thanks!

### What did you expect to happen?

When I turn on my PC from sleep, it just don't work, the only way is to unplug and plug the USB dongle. Sometimes it happens even just turning on the PC, like 2-3 times of every 10. It's so annoying, it happens on both Chimera and Bazzite, controller Elite 2 with FW upgraded to the latest version. There's any alternative or fix planned? Thanks!

**Comment by austonpramodh** [comment]
I am in the same boat, Wish it would work. It would make it easy to wake up the PC.

What have I tried so far?
* Unauthorizing the USB and authorizing again - Xbox controller connects but steam cannot see it neither driver adds input device in /dev (Saw it on dmesg)
* Removed kmod - xone-dongle, xone-gamepad, xone-gip-gamepad (Forgot the names, but there are three modules starting with `xone`).

only thing that works is removing the dongle physically and inserting again, even rebooting doesn't make it work.

**Comment by austonpramodh** [comment]
Looks like this is a known issue, No solution at the moment.

![image](https://github.com/user-attachments/assets/58373325-1b23-4db4-9e2d-16effdec3045)

https://discord.com/channels/733964971842732042/819644054563192846/1259955413110226985

**Comment by ArnauS197** [comment]
> I am in the same boat, Wish it would work. It would make it easy to wake up the PC.
> 
> What have I tried so far?
> 
> * Unauthorizing the USB and authorizing again - Xbox controller connects but steam cannot see it neither driver adds input device in /dev (Saw it on dmesg)
> * Removed kmod - xone-dongle, xone-gamepad, xone-gip-gamepad (Forgot the names, but there are three modules starting with `xone`).
> 
> only thing that works is removing the dongle physically and inserting again, even rebooting doesn't make it work.
> 
> @ArnauS197 Also, I am curious, What were the steps to downgrade on chimeraOS, I am new to container based OS.

Hi!

I downloaded the uninstall script for xone and then downloaded the xow installation script :) It worked like a charm, and then the dongle worked flawless all the time, but loosing some features like wake from sleep (I don't care tbh since wake from sleep just makes that I have to replug the USB dongle 100% of the times) 

I think this is not possible in Bazzite so...I just stay with xone. 

I also have to say that it worked perfectly during the last 4? 5? days, if you don't sleep your PC and turn it off correctly etc etc it seems to work fine most of the time, like 95% of the time. It's something hahaha.

Sorry for my bad english :)

**Comment by ArnauS197** [comment]
You can find the scripts I mentioned above in the github pages for XOW and XONE :)

**Comment by austonpramodh** [comment]
Oh cool, Interesting. Thanks for the info.

Your English is fine😛

**Comment by ArnauS197** [comment]
Hi, the issue still persists like the first day, nothing has improved since july that I started using Bazzite.

**Comment by arantes555** [comment]
Seeing the same here on a fresh bazzite install from  this week.

**Comment by bobo980212** [comment]
I have the same problem since september.

**Comment by ArnauS197** [comment]
It doesn't look like they're going to fix it, it happens in every Linux distro, hell it happens in Windows too, it seems the dongle is just bad af, I hope there is one from another brand with the same range and latency compatible with bazzite.

**Comment by el-banan** [comment]
having the same issue here, how come this issue is not a major one? Is everyone just using Xbox controllers using bluetooth?

**Comment by ArnauS197** [comment]
Its a global Linux issue, they just implement this software, and thats all, I just gave up and when this happens I just unplug and plug the usb again. Sad, but it is what it is

**Comment by ozboss** [comment]
The issue is that the original [xone repo](https://github.com/medusalix/xone) is quite stale. I suggest moving to [this fork](https://github.com/dlundqvist/xone) which has merged a lot of the outstanding pull requests and should fix the problem with the non functional wireless adapter after sleep.

**Comment by BjornWill** [comment]
Is there any update on this issue? Trying to install [the fork](https://github.com/dlundqvist/xone) on Bazzite does not work. If this fork does indeed fix the issues with the wireless dongle I hope it can be included in Bazzite by default?

If anyone has any more possible solutions I'd love to hear them.

**Comment by ArnauS197** [comment]
I did not found anything. It even fails with windows, at this point I think the adapter is just trash and im playing with a Dualsense or just before using xbox controller I unplug and plug again the dongle. Its sad but it is what it is

**Comment by ProteanPlatypus** [comment]
Is there any news on this issue? I'm experiencing the same symptoms on a fresh installation. Tried the official Microsoft Xbox wireless receiver as well as three other knockoff Xbox wireless receivers.

**Comment by ArnauS197** [comment]
Nope, 0 solutions

**Comment by noelmiller** [comment]
> Is there any news on this issue? I'm experiencing the same symptoms on a fresh installation. Tried the official Microsoft Xbox wireless receiver as well as three other knockoff Xbox wireless receivers.

Could you try updating the firmware on your controller and see if it resolves the issue? I had an issue with my Xbox One controller over bluetooth and I had to update the firmware using a windows PC to get it working properly.

**Comment by ProteanPlatypus** [comment]
Same, my Xbox Series controller is on the latest firmware (as of around April 13th 2025). Still having this issue.

**Comment by ozboss** [comment]
I want to note this is very much still an issue.

I still think dlundqvist/xone is the appropriate solution. The original repo still did not receive any updates while dlundqvist/xone is very actively maintained.
I also was not able to figure out where the package for xone in a bazzite image is coming from and how it becomes part of the image, maybe somebody can explain.

**Comment by ProteanPlatypus** [comment]
Still an issue for me as well.

Weirdly, the controller does wake the PC, and connects to the wireless dongle. But none of the controller buttons seem to have any response on the PC.

Xbox Series controller with firmware 5.23.6.0 (latest as of 2025-09-02)
Official Xbox wireless receiver

Let me know if you'd like any logs or output of terminal commands.

**Comment by andyschmid** [comment]
This issue has been resolved as of 43.20251102. The latest xonedo driver has been included in the 43.x release, this resolves the controller resume issue.

Also, there may be motherboard specific configuration required related to ACPI and USB for the controller to be fully detected on resume. 

There is a thread on this solution in #2367

**Comment by myralchista** [comment]
It's not fixed. Same issue on latest bazzite. Latest Xbox firmware updated through windows. Checked BIOS, didn't find anything related to usb sleep or acpi apart from resume from sleep by usb device which is enabled and works, but controller is not functioning after sleep, although the light is solid white on controller and dongle. 

Msi B350 pc mate motherboard .
Using the extender usb cable for the dongle.

**Comment by andyschmid** [comment]
You are right, it is not fully fixed. I've noticed my system has been working on and off, I think this bug is timing related. Investigating further I found the bug, reported https://github.com/dlundqvist/xone/issues/132

Hopefully it can get resolved and merged in with bazzite.

**Comment by myralchista** [comment]
Using USB 3 port (blue) on the back on the motherboard seems to fix the issue. Controller now works after sleep. Found solution on Reddit, post of 3 mouth ago. On usb2 it didn't work after sleep.

**Comment by HazemAM** [comment]
It’s also still an issue for me. Changing USB ports doesn’t help, and motherboard’s “always on” options are already enabled.

**Comment by andyschmid** [comment]
If the controller can wake the system and the light on the controller is solid, but the controller doesn't function, try this experiment:

With the controller connected and working put the system into sleep mode. Don't wake it with the controller, wake it by pressing the PC power button or keyboard. Once the system has resumed turn on the controller and check if it connects successfully.

If this works, it is likely the same issue I referenced earlier.

**Comment by HazemAM** [comment]
Tried it but didn’t work unfortunately, would’ve been a nice workaround actually. But yes, the controller wakes up the system, and the light on the controller is solid, but all controller inputs don’t register after waking up.

**Comment by andyschmid** [comment]
For what its worth on my system only USB3 ports will resume the controller. USB2 ports will still wake the system, but the controller never fully recovers.

There seems to be several factors at play: Bazzite 42.x had an outdated driver causing issues (fixed in 43), certain motherboard USB ports don't work for resume, and there is an outstanding timing related bug in the upstream xonedo driver.

**Comment by ProteanPlatypus** [comment]
This issue is still occurring for me.

I went to Desktop Mode, ran the System Update, it updated a bunch of things. Rebooted. Ran System Update again, no further updates. Rebooted into Gaming Mode.

Turned on the Xbox controller with its Xbox button. Controller quickly connects to dongle. But no button does anything in the Gaming Mode interface.

**Comment by jwittlincohen** [comment]
I'm seeing the same behavior on Bazzite with an Xbox Series X controller and the MS Xbox receiver.  The controllers pair and work fine as long as you shutdown and restart.  However, if you suspend  and then resume the system, the controllers show as paired but do not work at all (no response to any button presses).   This behavior does NOT occur when paired via Bluetooth.  This is occurring on Bazzite (Fedora 43) using the bazzite-deck image (boots directly into Steam Gaming Mode).  System specs are a Ryzen 7700X, Gigabyte B650 X AX V2 motherboard, 32 GB DDR5-6000, and a RX 9070 XT

**Comment by olepalm** [comment]
I have the same issue. But on my B450 Fatality mini-itx motherboard it seems I can resolve the issue by changing from using one of my front facing USB port, to one of the others on the rear facing IO panel. 
It is very picky about which USB port works, not all 3.0+ USB ports work. Maybe it is a wakeup timing related issue?

**Comment by jwittlincohen** [comment]
> I have the same issue. But on my B450 Fatality mini-itx motherboard it seems I can resolve the issue by changing from using one of my front facing USB port, to one of the others on the rear facing IO panel. It is very picky about which USB port works, not all 3.0+ USB ports work. Maybe it is a wakeup timing related issue?

Thanks for this advice.  When using one of the front-facing USB ports on my [Gigabyte B650 X AX V2](https://www.gigabyte.com/Motherboard/B650-GAMING-X-AX-V2-rev-1x/sp#sp) motherboard, my controller would turn on and show as paired (solid white light) but Bazzite would not respond to any input until removing and re-connecting the adapter, and sometimes I had to re-pair.  I tested using a rear USB 3.2 port (Red USB 3.2 Gen 2 Type-A port) on the motherboard directly and now it appears to be working after testing multiple suspend/resume cycles.  It never worked even a single time before.

I also tried using the custom udev rules and a systemd rule to unload and then re-load the xone_dongle kernel module, which can be found here: https://github.com/ublue-os/bazzite/issues/3569#issue-3677915662

Note that the commands did not work for me.  I had to manually create the udev and systemd files.  In addition, I had to modify the "ATTRS{idProduct}=="02e6" section because dmesg shows an id of "02fe" for my Xbox receiver.   

However, these custom rules didn't work when I had the receiver on the front USB port, so the fix may have simply been as you suggested - testing different USB 3.0 ports on the rear of the motherboard to find one that works properly.

**Comment by tekchip** [comment]
> > I have the same issue. But on my B450 Fatality mini-itx motherboard it seems I can resolve the issue by changing from using one of my front facing USB port, to one of the others on the rear facing IO panel. It is very picky about which USB port works, not all 3.0+ USB ports work. Maybe it is a wakeup timing related issue?
> 
> Thanks for this advice. When using one of the front-facing USB ports on my [Gigabyte B650 X AX V2](https://www.gigabyte.com/Motherboard/B650-GAMING-X-AX-V2-rev-1x/sp#sp) motherboard, my controller would turn on and show as paired (solid white light) but Bazzite would not respond to any input until removing and re-connecting the adapter, and sometimes I had to re-pair. I tested using a rear USB 3.2 port (Red USB 3.2 Gen 2 Type-A port) on the motherboard directly and now it appears to be working after testing multiple suspend/resume cycles. It never worked even a single time before.
> 
> I also tried using the custom udev rules and a systemd rule to unload and then re-load the xone_dongle kernel module, which can be found here: [#3569 (comment)](https://github.com/ublue-os/bazzite/issues/3569#issue-3677915662)
> 
> Note that the commands did not work for me. I had to manually create the udev and systemd files. In addition, I had to modify the "ATTRS{idProduct}=="02e6" section because dmesg shows an id of "02fe" for my Xbox receiver.
> 
> However, these custom rules didn't work when I had the receiver on the front USB port, so the fix may have simply been as you suggested - testing different USB 3.0 ports on the rear of the motherboard to find one that works properly.

I think there may be some confusion over this that is touched on here. I think there are two things happening that may be pertinent to these type of issues.

First only one of the two Xbox dongles actually supports the wake feature natively. The smaller dongle "Wireless dongle for windows 10" does not support the wake feature. The larger (older?) dongle "Wireless dongle for windows" does support the native wake feature.

Second some, but not all PCs, support wake on USB which means that any USB device should be able to wake the PC. As noted this is usually limited to some subset of ports (usb 3?). Presumably this will allow the smaller Xbox dongle to wake the PC. However wake on USB is often disabled by default in the bios and, often, only certain USB ports work with this feature. Check your motherboard manual for which ports should support wake on USB.

This confusion is compounded by errors like what I found in my #3569 post.

Hopefully that info will help cut through some of the confusion and help get to some brass tacks in fixing this type of issue.

**Comment by meowkash** [comment]
I noticed that whenever I try to power on my xbox controller (which is connected via USB) to my PC, it goes into pairing mode. Now, this only happens if I am resuming from a suspended state (S3 sleep). A hacky workaround for this has been to unplug it and plug it back in again. On some digging around (```udevadm monitor --kernel --udev --property```), I observed that whenever the system goes to sleep, xpad does not send a remove command but the controller is put to sleep by the system. Thus, when the system turns on, the system thinks the controller is connected and never tries to establish a connection with it whereas the controller only gets power but no connection so goes into pairing mode. At least, this is my theory. 

I have a temporary workaround for this using a systemd service but would appreciate if it could be fixed at the driver level. Here is the service file I am using to fix this issue 

```
[Unit]
Description=Reset Xbox controllers on resume
After=suspend.target

[Service]
Type=oneshot
ExecStart=/bin/bash -c 'for d in /sys/bus/usb/drivers/xpad/*-*; do [ -e "$d" ] && echo "${d##*/}" > /sys/bus/usb/drivers/xpad/unbind && sleep 1 && echo "${d##*/}" > /sys/bus/usb/drivers/xpad/bind; done'

[Install]
WantedBy=suspend.target
```

See if this helps fix the issue, OP?

**Comment by Prodeguerriero** [comment]
Hi @meowkash,

I also have the issue that after waking the machine from sleep the controller isn't detected by the machine, even though the controller connects to the dongle.

I stumbled upon your comment while looking around for a solution to this problem and I have a couple of questions and remarks:
- do you run the service at the system or user level?
- my driver path uses `xone-dongle` instead of `xpad`
- manually writing to `unbind` and then `bind` doesn't seem to get the gamepad to work. This should technically work though, right?
- if I start the service manually and then check the status, I see this error:  
  `xbox.controller.wake.service: Invalid environment variable name evaluates to an empty string: d##*/`

**Comment by meowkash** [comment]
Hi @Prodeguerriero, I tried running it system level and it worked for a couple of times but stopped working again post reboot. I also tried rebasing to KDE to see if there was a difference in how things were being handled but no dice. As of now, the problem has come back on my end too and I don't have any more ideas on what's going on. I still believe it is caused by the wrong driver trying to take over, failing to connect, and not letting the Xbox controller driver take over.

**Comment by drdaz** [comment]
Still an issue.

Another data point for this thread, with a kernel-side, suspend-time error. 

Xbox Wireless Adapter (045e:02e6) on Bazzite. After resume from suspend, the
controller reconnects to the dongle (LED goes solid) but doesn't work — it's
absent from `evtest` and `/proc/bus/input/devices`. Only physically unplugging
and replugging the dongle brings it back.

dmesg shows the dongle's power-off failing on suspend:

`xone-dongle 1-6:1.0: xone_dongle_suspend: power off failed: -110`

Things I tried that did NOT fix it (controller stayed dead):
- de-authorize/re-authorize via sysfs `authorized`
- unbind/bind at `/sys/bus/usb/drivers/usb`
- unbind/bind of the interface at `xone-dongle`
- reloading the `xone_dongle` module
- udev rule setting `power/wakeup=disabled`
- a system-sleep hook de-authorizing the dongle before suspend

Only a physical replug works.

Environment:
- Bazzite, S3 suspend (`/sys/power/mem_sleep` = `[deep]`)
- ASRock Z390 Phantom Gaming-ITX/ac
- Adapter 045e:02e6, plugged directly into the board (not a hub)
- Intermittent — occasionally resumes fine, but broken more often than not

**Comment by rdamron** [comment]
I previously had a fully working setup on v43 stable, on v44 testing this issue occurs. Rolling back to v43 solves the issue. Not sure how helpful this data point is but wake on usb is so very clutch.
