### ISSUE TITLE
Steam game UI suddenly looks psychedelic

### ISSUE THREAD

**Issue by Caanen** [ublue-os/bazzite#1538]
### Describe the bug

Everything was fine yesterday. I come back today and wake from sleep and the UI looked like it had a bad drug binge. See photo.
![IMG_20240824_064525113](https://github.com/user-attachments/assets/e0a93659-b817-4f10-87c9-08f79e388f4e)

### What did you expect to happen?

Expected game UI to look like normal.

### Hardware

Minisforum AtomMan G7 PT

**Comment by KyleGospo** [comment]
Ensure HDR is enabled in both game mode and on your monitor

**Comment by Caanen** [comment]
I'll give it a try. Though I'm not entirely sure HDR is supported on my television.

**Comment by Caanen** [comment]
I will say leaving gamepad ui and going to desktop returns thing to normal. Also entering gamepad ui from desktop also seems to fix the issue. Rebooting the system or waking from sleep while in gamepad ui causes the weird color issue again.

**Comment by Caanen** [comment]
Steam game mode says that my display does not support HDR. It is an old panel after all.

**Comment by Caanen** [comment]
Confirmed that this happens 100% when the system wakes on sleep in gamepad ui. Not sure if this is helpful or not but thought I'd report on it anyways.

**Comment by Thermionix** [comment]
I've managed to fix this on my system (AMD Ryzen 5600, AMD RX 7600) which was also getting corrupted vibrant colors on boot

I created a config file to force HDR:
````
$ cat .config/environment.d/gamescope-session-plus.conf
GAMESCOPECMD="gamescope -e -f --xwayland-count 2 --hdr-enabled --hdr-itm-enable --adaptive-sync"
`````

new and old launch args:
`````
$ cat .gamescope-cmd.log
gamescope -e -f --xwayland-count 2 --hdr-enabled --hdr-itm-enable --adaptive-sync -R /run/user/1000/gamescope.4T8iu4f/startup.socket -T /run/user/1000/gamescope.4T8iu4f/stats.pipe
$ cat .gamescope-cmd.log.old
/usr/bin/gamescope --bypass-steam-resolution --prefer-output *,eDP-1 --xwayland-count 2 --default-touch-mode 4 --hide-cursor-delay 3000 --fade-out-duration 200 --steam -R /run/user/1000/gamescope.XWryusq/startup.socket -T /run/user/1000/gamescope.XWryusq/stats.pipe
`````

**Comment by JakWolf** [comment]
I'm having the exact same problem on a AMD PC build (ryzen 5500 & radeon 6700).

Sadly, adding the flags in gamescope-session-plus.conf results in a black screen when booting. Had to boot in safe mode to delete the config.

Any ideas how to make this work? Maybe i should remove some flags in the config...

**Comment by davetansley** [comment]
Same issue here with an AMD 7600M XT GPU. Reboot doesn't solve it, but unplugging and plugging the HDMI cures it every time. It happens maybe 50% of boots or wakes from sleep.

**Comment by jlnr** [comment]
I'm getting the psychedelic experience on the AtomMan G7 PT on every boot. It goes away when I start a game (and in many other situations).

After finding this issue, I enabled HDR in the Steam settings, created the environment.d file shown above, and turned on HDR in my TV settings. And indeed, that reliably solves the issue.

The problem is that HDR on my TV looks unbearably bad. I have also experienced this bug on an ancient TV that certainly has no HDR support. The question is, why does the game mode session accidentally enable HDR on startup?

Some ideas:
- See if Nobara's Deck image exhibits the same issue.
- Bisect the issue by installing really old versions of Bazzite?

**Comment by jlnr** [comment]
The issue does not seem to happen in Nobara 41 for handhelds. (The HTPC build would be more fitting for the AtomMan, but the handheld version felt more like an "apples to apples" comparison with regards to gamescope etc.)

**Comment by jlnr** [comment]
It looks like general HDR support first landed in April according to this announcement:
https://universal-blue.discourse.group/t/announcing-bazzite-3-0/1218

@Caanen, you said that everything was fine "yesterday", and your two most recent images are 2024-08-22 and 2024-08-15. So I guess something happened between those builds that introduced this issue. Looking at the git log, a bunch of updates happened in that time frame: kernel 6.9.12-205, gamescope 3.15.x, mesa 24.1.6...

**Comment by jlnr** [comment]
Deleted my previous comments after too many edits, reposting:

I'm getting the psychedelic experience on the AtomMan G7 PT on every wake and boot (reboots excluded). It goes away when I start a game, or unplug the HDMI cable and plug it back in, or enter desktop mode, etc.

> Ensure HDR is enabled in both game mode and on your monitor

That did not work for me, the psychedelic effect still appears. (Also, everything looks _worse_ with HDR enabled, but this [might be an unrelated gamescope issue](https://github.com/ValveSoftware/gamescope/issues/1497). This workaround also wouldn't help on displays that don't have HDR support.)

The question is, why does the game mode session output different colors on startup, but only then, and only on AMD dGPUs?

Things I've tried:
* Nobara 41 handheld edition does not seem to exhibit this behavior.
* Using a DisplayPort-to-HDMI cable does not help.
* Downgrading to the 2024-08-15 build mentioned in the original issue text is not possible anymore, `bazzite-rollback-helper` only has builds starting from September. -> I cannot verify if that build still worked or not.

I don't think this issue is as old as HDR support itself, [because I can find reports of working HDR going back to June.](https://universal-blue.discourse.group/t/any-updates-on-hdr/1924)

Looking at the commit log before 2024-08-22, I see several system updates: kernel 6.9.12-205, gamescope 3.15.x, mesa 24.1.6. I guess the next best thing is to fork Bazzite and try to narrow it down to a specific update?

Coincidentally, I also want to use my TV for audio (over HDMI), and I have to set my audio output device back and forth after a reboot, otherwise it won't work. It's as if the HDMI connection is badly initialized, if that makes sense? Edit: The audio issue has somehow resolved itself.

**Comment by jlnr** [comment]
TIL that this is a documented quirk in the Bazzite docs: https://docs.bazzite.gg/Handheld_and_HTPC_edition/quirks/#rainbow-display

Will try the documented workaround of Force Composite. But it would still be interesting to know where exactly this bug originates from (GameScope, AMD drivers, Fedora, ...). Edit: Force Composite did not help in my case.

**Comment by jlnr** [comment]
For me, the glitch stopped happening at some point during the last weeks. (I am still experiencing what I thought would be a side effect of the same bug—my HTPC uses the wrong resolution until I unplug and re-plug the HDMI cable—but at least the colors are normal now.)

**Comment by CheckYourFax** [comment]
Is anyone still having issues with HDR in Gaming Mode?

**Comment by crdpa** [comment]
This issue started happening recently for me too.

It fixes if i unplug and plug again the HDMI cable. Or if I go to options and change something that refreshes the screen like enabling and disabling HDR.

I always have HDR off, but my TV supports it.

It's a Ryzen AM5 with Asus Radeon RX 7600 OC

**Comment by RayBa82** [comment]
CPU AMD 7800X3D + GPU AMD 7800XT

Same since a few updates, rainbow colors after every fresh boot direct in game mode.

**Comment by theycallmeboxy** [comment]
I am also experiencing this issue, using Bazzite Deck.  9070xt and 5800x

**Comment by antheas** [comment]
You guys have a different issue that was fixed in this update. So update

**Comment by theycallmeboxy** [comment]
> You guys have a different issue that was fixed in this update. So update

I actually never had this issue until updating this evening, but I have only been using Bazzite for a limited amount of time, maybe less than 2 weeks.

**Comment by antheas** [comment]
6.17 kernel had a little issue

**Comment by RayBa82** [comment]
Still have the same issue on testing-43.20251119

**Comment by argeualcantara** [comment]
I got my PC on **Nov. 14**, installed bazzite, all good. After installation completed, I tested a few games and decided to update.
After updating it started booting with this glitch, but after a few seconds when I moved my mouse, it would go away and look like it was suppoed to be. When the pc went to sleep and wake up again the issue would come back.

I had to do the force composite thing in order to have it working just like before updating. My monitor does not support HDR, a friend of mine had no issues after updating on the same day, but his monitor supports HDR.

I feel like this only happens with people whose monitor does not support HDR and it tries to activate by default.

**Comment by RayBa82** [comment]
Maybe, I can't even deacivate HDR because the button does nothing...

**Comment by JonSchaeffer** [comment]
I've had Bazzite since March 2025. In July I've gotten the rainbow display on every wake from sleep. Toggling HDR does the trick, but it's annoying to have to do this every single time.

**Comment by Scottedont** [comment]
I have the same problem but weirdly enough, the problem is corrected simply by holding down the xbox button and B to bring up the HHD menu. Once that menu pops up, all the colors are suddenly corrected. I dont have to enable and disable HDR but that does work too. I have a 4k HDR vizio tv hooked up to a 7800xt via HDMI. It supports HDR but I leave it off because the colors don't look exactly right when in HDR mode. 

I have been running bazzite on this machine since 2024 and this is a recent development. I wonder if this problem is related to HHD.

**Comment by MarkCuypers** [comment]
Even in 2026 this is still an issue

![Image](https://github.com/user-attachments/assets/55eb67b9-c5d4-4954-8865-8816d0a226ea)

**Comment by mrtrumbe** [comment]
Please remove the stale label! I can confirm this issues is still present on my AMD build (Radeon RX 7800 XT card). It doesn't happen every time, but it consistently happens when I wake or boot into game mode. Controller input doesn't make it go away until I do certain actions in the UI, but interestingly, moving the mouse fixes it. Attaching my journalctl logs for the period around a wake when this occurred in case that is helpful. In this wake cycle, the steam UX came up with the pixelated rainbow colors similar to the screenshots in previous comments, I waited a few seconds, then I moved the mouse which corrected the issue. I went through logs, but nothing popped out to my eyes.

[launchctl.log](https://github.com/user-attachments/files/25459032/launchctl.log)

**Comment by DNPLukeBu** [comment]
This has happened to me every time I boot, until I move my mouse, for over 6 months.  HDR is off in gamemode, since I just have a standard panel.  I love Bazzite, but between this and the horrid sound, I take of my headphones and close my eyes for rebooting.

**Comment by DjTuner13** [comment]
Happening to me as well, internet has said to enable developer mode, in dev mode select force composite on. I will report back.
