### ISSUE TITLE
DisplayLink monitor has no output after Bazzite 41 update

### ISSUE THREAD

**Issue by nyssestrup** [ublue-os/bazzite#1825]
### Describe the bug

Hello

After the recent Bazzite 41 update, my DisplayLink monitor no longer seems to work. I've been following #1801 and tried updating my system after the issue was marked as completed, which now results in the monitor (3) being detected:
![Image](https://github.com/user-attachments/assets/109573a7-1100-4957-a402-888445734b18)

The monitor itself outputs nothing but a black image, but I'm seemingly able to drag windows to it.

### What did you expect to happen?

.

### Output of `rpm-ostree status`

State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-gnome-nvidia-open:stable
                   Digest: sha256:6dfadff34b2f0ed1b459b240987fda78765a2086ccdf8708e9c0bda7293ad217
                  Version: 41.20241030 (2024-10-31T01:22:09Z)
          LayeredPackages: openrgb
            LocalPackages: opendeck-2.2.0-1.x86_64

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-gnome-nvidia-open:stable
                   Digest: sha256:c36b6f99c888d73a2ee674c5e1c89a12a7c650fd688087b284c20abf40023753
                  Version: 41.20241029.1 (2024-10-29T15:39:12Z)
          LayeredPackages: openrgb
            LocalPackages: opendeck-2.2.0-1.x86_64

### Hardware

# System Details Report
---

## Report details
- **Date generated:**                              2024-10-31 09:04:51

## Hardware Information:
- **Hardware Model:**                              ASUS TUF GAMING B650-PLUS WIFI
- **Memory:**                                      32.0 GiB
- **Processor:**                                   AMD Ryzen™ 5 7600X × 12
- **Graphics:**                                    NVIDIA GeForce RTX™ 4070
- **Graphics 1:**                                  Advanced Micro Devices, Inc. [AMD®/ATI] Raphael
- **Disk Capacity:**                               3.3 TB

## Software Information:
- **Firmware Version:**                            1616
- **OS Name:**                                     Bazzite 41 (FROM Fedora Silverblue)
- **OS Build:**                                    Stable (F41.20241030)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               47
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.11.5-307.bazzite.fc41.x86_64

**Comment by KyleGospo** [comment]
This was fixed as of last night's release.

**Comment by nyssestrup** [comment]
Forgive me for asking a potentially stupid question as I'm still a Linux novice, but is F41.20241030, (the version mentioned under Software Information) that my system is running on not last nights release?

**Comment by LordAlderaan** [comment]
Is still have this problem in 41.20241112.1. 

In my case it is the DVI output which I'm using as a third output using a DVI to HDMI connector. All three screens (DisplayPort, HDMI, DVI) work fine in windows and worked fine in 40. But the DVI output is longer working in 41. Even the startup and logon screens are not visible on it.

rpm-ostree status
```
State: idle
Deployments:
  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia-open:stable
                   Digest: sha256:821cc798ce42c401cd9ef392689128e4ee039ba7d58001386d71268830a7d4d5
                  Version: 41.20241112.1 (2024-11-12T23:59:36Z)
                     Diff: 308 upgraded

● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia-open:stable
                   Digest: sha256:a9a6906e6ab46d2d86b4c0ef963ea8ce5728a63e4e94905d837a19c305d76dc3
                  Version: 41.20241104 (2024-11-04T05:01:05Z)

```

cat /sys/devices/virtual/dmi/id/product_name
```
To Be Filled By O.E.M.
```
