### ISSUE TITLE
"Documentation" app/link not working

### ISSUE THREAD

**Issue by zabzone** [ublue-os/bazzite#2110]
### Describe the bug

When you click on the "Documentation" app/link in the Utilities catgeory, it leads you to http://127.0.0.1:1290/, and says "Directory listing for /". Nothing else is in the page on inspect.

![Image](https://github.com/user-attachments/assets/978072ad-7675-4dbb-b9c5-c91d65966cb9)

### What did you expect to happen?

I expected it to lead to a proper documentation site

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-nvidia-gnome:stable
                   Digest: sha256:3d944d715cd07ef47fb667c96d2c19ff3616cae8914dec3207cffdeeaed6b11e
                  Version: 41.20250106.3 (2025-01-07T04:27:46Z)
            LocalPackages: VirtualBox-7.1-7.1.4_165100_fedora40-1.x86_64

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-nvidia-gnome:stable
                   Digest: sha256:3d944d715cd07ef47fb667c96d2c19ff3616cae8914dec3207cffdeeaed6b11e
                  Version: 41.20250106.3 (2025-01-07T04:27:46Z)
```

### Hardware

  %%%%%%%%%    %%%%%%%####======#####     󰾰  Alienware Aurora R15
  %%%%%%%%%    %%%%%#######=====#####     󰻠  13th Gen Intel(R) Core(TM) i7-13700F (24) @ 5.20 GHz
  %%%%%%%%%    %%%#########=====#####     󰍛  NVIDIA GeForce RTX 4070 [Discrete]
  %%%%%%%%%    %%##########=====#####       7.71 GiB / 31.05 GiB (25%)
  %%%%%%%%%====###########=====######       145.62 GiB / 952.28 GiB (15%) - btrfs [Read-only]
   %%%%%%%%====#########======######        591.66 GiB / 1.79 TiB (32%) - ext4
    %%%%%%%=====#####========######       󰍹  3440x1440 @ 165 Hz in 34" [External]

**Comment by nicknamenamenick** [comment]
Thanks! This should be fixed in the next Bazzite build.

**Comment by atimeofday** [comment]
Checking in - has this been fixed, and is it ready to close?

**Comment by CheckYourFax** [comment]
This is fixed.

**Comment by Wilf-bog** [comment]
It seems like the issue is back on current version of Bazzite.

<img width="544" height="287" alt="Image" src="https://github.com/user-attachments/assets/24ff3496-e1bb-4084-97b3-44abf67be478" />

https://paste.centos.org/view/6a7606ea
