### ISSUE TITLE
mangoapp constantly crash/looping and core-dumping - Causing spikes in cpu usage and high temps at idle in gaming mode

### ISSUE THREAD

**Issue by adr3nal1n** [ublue-os/bazzite#2275]
### Describe the bug

Hi,

Am using bazzite-deck-gnome:stable on an AMD 7840HS Mini PC and have noticed that since the last 2 stable updates that at idle in gaming mode, the CPU fan constantly spins up and down and that CPU clocking and temps are much higher (clocking at 2.4Ghz and around 60 degrees c) compared to what I normally experience (usually 400Mhz at around 34 degrees c)

Did a "sudo journalctl -f" and can see mangoapp continuously crashing and core-dumping at least every second. If I kill the mangoapp process the CPU clocking, fan and temps all settle back down to normal.

Snippet of journal below:

`Feb 14 08:07:08 bazzite-lounge systemd-coredump[284682]: Process 284660 (mangoapp) of user 1000 dumped core.
                                                         Module mangoapp from rpm mangohud-0.7.2-2.20231002gita109f0b.fc41.x86_64
                                                         #0  0x000055ba0ca13b34 main (mangoapp + 0x18b34)
                                                         #3  0x000055ba0ca18725 _start (mangoapp + 0x1d725)
                                                         #2  0x000055ba0ca67d67 _ZL11fileChangedP13notify_thread.lto_priv.0 (mangoapp + 0x6cd67)
                                                         #3  0x000055ba0cb7fc24 execute_native_thread_routine (mangoapp + 0x184c24)
                                                         #1  0x000055ba0ca1a4b5 _ZL15msg_read_threadv (mangoapp + 0x1f4b5)
                                                         #2  0x000055ba0cb7fc24 execute_native_thread_routine (mangoapp + 0x184c24)
                                                         #1  0x000055ba0ca18b93 _ZL11ctrl_threadv (mangoapp + 0x1db93)
                                                         #2  0x000055ba0cb7fc24 execute_native_thread_routine (mangoapp + 0x184c24)
Feb 14 08:07:08 bazzite-lounge gamescope-session-plus[2580]: /usr/share/gamescope-session-plus/gamescope-session-plus: line 342: 284660 Segmentation fault      (core dumped) mangoapp
Feb 14 08:07:08 bazzite-lounge gamescope-session-plus[2580]: + mangoapp
Feb 14 08:07:08 bazzite-lounge audit[284690]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=2 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=284690 comm="mangoapp" exe="/usr/bin/mangoapp" sig=11 res=1
Feb 14 08:07:08 bazzite-lounge kernel: mangoapp[284690]: segfault at 8 ip 0000563d40da7b34 sp 00007ffd083ea8c0 error 4 in mangoapp[18b34,563d40d90000+1b9000] likely on CPU 1 (core 1, socket 0)
Feb 14 08:07:08 bazzite-lounge systemd-coredump[284711]: Process 284690 (mangoapp) of user 1000 terminated abnormally with signal 11/SEGV, processing...
Feb 14 08:07:09 bazzite-lounge systemd-coredump[284712]: Removed old coredump core.mangoapp.1000.8abf44a3b6a44e4380832ddaa9f4f74e.235989.1739519608000000.zst.`

Thank you for looking into this.

### What did you expect to happen?

Normal CPU idle in gamemode is 400Mhz and temps usually around 34 degrees c (and low fan noise)

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:4de240a567f48a78a0e168e411278a53f17cc8603437850437159f5b8b49d050
                  Version: 41.20250211 (2025-02-11T04:45:03Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:773bc31220ea12b669859025a710efb0881f4b8d73848587650bc1ef14952140
                  Version: 41.20250208 (2025-02-08T06:31:01Z)
```

### Hardware

GMKtec K6 AMD 7840HS Mini PC, 32GB DDR5 5600 RAM, 1TB gen 4 SSD

**Comment by adr3nal1n** [comment]
Same issue exists after updating to the latest stable release 41.20250215: Stable

**Comment by KyleGospo** [comment]
Thanks for the report, this should be fixed in the latest build.

**Comment by adr3nal1n** [comment]
Still the same issue after updating to the latest stable release
`Feb 16 16:50:58 bazzite-lounge systemd-coredump[12027]: [🡕] Process 12005 (mangoapp) of user 1000 dumped core.
                                                        
                                                        Module liblzma.so.5 from rpm xz-5.6.2-2.fc41.x86_64
                                                        Module libtinfo.so.6 from rpm ncurses-6.5-2.20240629.fc41.x86_64
                                                        Module libpciaccess.so.0 from rpm libpciaccess-0.16-13.fc41.x86_64
                                                        Module libxml2.so.2 from rpm libxml2-2.12.9-1.fc41.x86_64
                                                        Module libedit.so.0 from rpm libedit-3.1-54.20250104cvs.fc41.x86_64
                                                        Module libdrm_intel.so.1 from rpm libdrm-2.4.124-1.fc41.x86_64
                                                        Module libdrm_amdgpu.so.1 from rpm libdrm-2.4.124-1.fc41.x86_64
                                                        Module libelf.so.1 from rpm elfutils-0.192-7.fc41.x86_64
                                                        Module libdrm_radeon.so.1 from rpm libdrm-2.4.124-1.fc41.x86_64
                                                        Module libxshmfence.so.1 from rpm libxshmfence-1.3.2-5.fc41.x86_64
                                                        Module libxcb-sync.so.1 from rpm libxcb-1.17.0-3.fc41.x86_64
                                                        Module libxcb-randr.so.0 from rpm libxcb-1.17.0-3.fc41.x86_64
                                                        Module libsensors.so.4 from rpm lm_sensors-3.6.0-20.fc41.x86_64
                                                        Module libSPIRV-Tools.so from rpm spirv-tools-2024.4-1.fc41.x86_64
                                                        Module libzstd.so.1 from rpm zstd-1.5.6-2.fc41.x86_64
                                                        Module libz.so.1 from rpm zlib-ng-2.2.3-1.fc41.x86_64
                                                        Module libxcb-xfixes.so.0 from rpm libxcb-1.17.0-3.fc41.x86_64
                                                        Module libxcb-present.so.0 from rpm libxcb-1.17.0-3.fc41.x86_64
                                                        Module libxcb-dri3.so.0 from rpm libxcb-1.17.0-3.fc41.x86_64
                                                        Module libexpat.so.1 from rpm expat-2.6.4-1.fc41.x86_64
                                                        Module libxcb-shm.so.0 from rpm libxcb-1.17.0-3.fc41.x86_64
                                                        Module libxcb-glx.so.0 from rpm libxcb-1.17.0-3.fc41.x86_64
                                                        Module libdrm.so.2 from rpm libdrm-2.4.124-1.fc41.x86_64
                                                        Module libgallium-24.3.3.so from rpm mesa-24.3.3-3.fc41.x86_64
                                                        Module libglapi.so.0 from rpm mesa-24.3.3-3.fc41.x86_64
                                                        Module libGLX_mesa.so.0 from rpm mesa-24.3.3-3.fc41.x86_64
                                                        Module libX11-xcb.so.1 from rpm libX11-1.8.11-1.fc41.x86_64
                                                        Module libXinerama.so.1 from rpm libXinerama-1.1.5-7.fc41.x86_64
                                                        Module libXfixes.so.3 from rpm libXfixes-6.0.1-4.fc41.x86_64
                                                        Module libXcursor.so.1 from rpm libXcursor-1.2.3-1.fc41.x86_64
                                                        Module libXrender.so.1 from rpm libXrender-0.9.12-1.fc41.x86_64
                                                        Module libXrandr.so.2 from rpm libXrandr-1.5.4-4.fc41.x86_64
                                                       Module libXi.so.6 from rpm libXi-1.8.2-1.fc41.x86_64
                                                        Module libXxf86vm.so.1 from rpm libXxf86vm-1.1.6-1.fc41.x86_64
                                                        Module libXau.so.6 from rpm libXau-1.0.11-7.fc41.x86_64
                                                        Module libffi.so.8 from rpm libffi-3.4.6-3.fc41.x86_64
                                                        Module libxcb.so.1 from rpm libxcb-1.17.0-3.fc41.x86_64
                                                        Module libGLdispatch.so.0 from rpm libglvnd-1.7.0-5.fc41.x86_64
                                                        Module libXext.so.6 from rpm libXext-1.3.6-2.fc41.x86_64
                                                        Module libGLX.so.0 from rpm libglvnd-1.7.0-5.fc41.x86_64
                                                        Module libxkbcommon.so.0 from rpm libxkbcommon-1.7.0-4.fc41.x86_64
                                                        Module libglfw.so.3 from rpm glfw-3.3.10-1.fc41.x86_64
                                                        Module libwayland-client.so.0 from rpm wayland-1.23.0-2.fc41.x86_64
                                                        Module libX11.so.6 from rpm libX11-1.8.11-1.fc41.x86_64
                                                        Module libfmt.so.11 from rpm fmt-11.0.2-2.fc41.x86_64
                                                        Module libspdlog.so.1.14 from rpm spdlog-1.14.1-3.fc41.x86_64
                                                        Module libGL.so.1 from rpm libglvnd-1.7.0-5.fc41.x86_64
                                                        Module mangoapp from rpm mangohud-0.8.0-1.20250212gitf77864d.fc41.x86_64
                                                        Stack trace of thread 12005:
                                                        #0  0x000055c9468e0840 main (mangoapp + 0x1a840)
                                                        #1  0x00007f22745eb248 __libc_start_call_main (libc.so.6 + 0x3248)
                                                        #2  0x00007f22745eb30b __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x330b)
                                                        #3  0x000055c9468e4da5 _start (mangoapp + 0x1eda5)
                                                        
                                                        Stack trace of thread 12011:
                                                        #0  0x00007f22746557e9 __futex_abstimed_wait_common (libc.so.6 + 0x6d7e9)
                                                        #3  0x00007f2263ac558b n/a (libgallium-24.3.3.so + 0x4c558b)
                                                        #4  0x00007f2263afa65c n/a (libgallium-24.3.3.so + 0x4fa65c)
                                                        #5  0x00007f2274659168 start_thread (libc.so.6 + 0x71168)
                                                        #6  0x00007f22746dd14c __clone3 (libc.so.6 + 0xf514c)
                                                        
                                                        Stack trace of thread 12007:
                                                        #0  0x00007f22746557e9 __futex_abstimed_wait_common (libc.so.6 + 0x6d7e9)
                                                        #1  0x00007f2274658239 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x70239)
                                                        #2  0x00007f2263afa72d n/a (libgallium-24.3.3.so + 0x4fa72d)
                                                        #3  0x00007f2263ac558b n/a (libgallium-24.3.3.so + 0x4c558b)
                                                        #4  0x00007f2263afa65c n/a (libgallium-24.3.3.so + 0x4fa65c)
                                                        #5  0x00007f2274659168 start_thread (libc.so.6 + 0x71168)
                                                        #6  0x00007f22746dd14c __clone3 (libc.so.6 + 0xf514c)
                                                        
                                                        Stack trace of thread 12006:
                                                        #0  0x00007f22746557e9 __futex_abstimed_wait_common (libc.so.6 + 0x6d7e9)
                                                        #1  0x00007f2274658239 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x70239)
                                                        #2  0x00007f2263afa72d n/a (libgallium-24.3.3.so + 0x4fa72d)
                                                        #3  0x00007f2263ac558b n/a (libgallium-24.3.3.so + 0x4c558b)
                                                        #4  0x00007f2263afa65c n/a (libgallium-24.3.3.so + 0x4fa65c)
                                                        #5  0x00007f2274659168 start_thread (libc.so.6 + 0x71168)
                                                        #6  0x00007f22746dd14c __clone3 (libc.so.6 + 0xf514c)
                                                        
                                                        Stack trace of thread 12025:
                                                        #0  0x00007f22746dfa2d __libc_msgrcv (libc.so.6 + 0xf7a2d)
                                                        #1  0x000055c9468e5233 _ZL11ctrl_threadv (mangoapp + 0x1f233)
                                                        #2  0x000055c946a56e64 execute_native_thread_routine (mangoapp + 0x190e64)
                                                        #3  0x00007f2274659168 start_thread (libc.so.6 + 0x71168)
                                                        #4  0x00007f22746dd14c __clone3 (libc.so.6 + 0xf514c)
                                                        
                                                        Stack trace of thread 12014:
                                                        #0  0x00007f22746557e9 __futex_abstimed_wait_common (libc.so.6 + 0x6d7e9)#1  0x00007f2274658239 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x70239)
                                                        #2  0x00007f2263afa72d n/a (libgallium-24.3.3.so + 0x4fa72d)

                                                        #1  0x00007f2274658239 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x70239)
                                                        #2  0x00007f2263afa72d n/a (libgallium-24.3.3.so + 0x4fa72d)
                                                        #3  0x00007f2263ac558b n/a (libgallium-24.3.3.so + 0x4c558b)
                                                        #4  0x00007f2263afa65c n/a (libgallium-24.3.3.so + 0x4fa65c)
                                                        #5  0x00007f2274659168 start_thread (libc.so.6 + 0x71168)
                                                        #6  0x00007f22746dd14c __clone3 (libc.so.6 + 0xf514c)
                                                        
                                                        Stack trace of thread 12013:
                                                        #0  0x00007f22746557e9 __futex_abstimed_wait_common (libc.so.6 + 0x6d7e9)
                                                        #1  0x00007f2274658239 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x70239)
                                                        #2  0x00007f2263afa72d n/a (libgallium-24.3.3.so + 0x4fa72d)
                                                        #3  0x00007f2263ac558b n/a (libgallium-24.3.3.so + 0x4c558b)
                                                        #4  0x00007f2263afa65c n/a (libgallium-24.3.3.so + 0x4fa65c)
                                                        #5  0x00007f2274659168 start_thread (libc.so.6 + 0x71168)
                                                        #6  0x00007f22746dd14c __clone3 (libc.so.6 + 0xf514c)
                                                        
                                                        Stack trace of thread 12012:
                                                        #0  0x00007f22746557e9 __futex_abstimed_wait_common (libc.so.6 + 0x6d7e9)
                                                        #1  0x00007f2274658239 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x70239)
                                                        #2  0x00007f2263afa72d n/a (libgallium-24.3.3.so + 0x4fa72d)
                                                        #3  0x00007f2263ac558b n/a (libgallium-24.3.3.so + 0x4c558b)
                                                        #4  0x00007f2263afa65c n/a (libgallium-24.3.3.so + 0x4fa65c)
                                                        #5  0x00007f2274659168 start_thread (libc.so.6 + 0x71168)
                                                        #6  0x00007f22746dd14c __clone3 (libc.so.6 + 0xf514c)
                                                        
                                                        Stack trace of thread 12015:
                                                        #0  0x00007f22746557e9 __futex_abstimed_wait_common (libc.so.6 + 0x6d7e9)
                                                        #1  0x00007f2274658239 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x70239)
                                                        #2  0x00007f2263afa72d n/a (libgallium-24.3.3.so + 0x4fa72d)
                                                        #3  0x00007f2263ac558b n/a (libgallium-24.3.3.so + 0x4c558b)
                                                        #4  0x00007f2263afa65c n/a (libgallium-24.3.3.so + 0x4fa65c)
                                                        #1  0x00007f2274658239 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x70239)
                                                        #2  0x00007f2263afa72d n/a (libgallium-24.3.3.so + 0x4fa72d)
                                                        #3  0x00007f2263ac558b n/a (libgallium-24.3.3.so + 0x4c558b)
                                                        #4  0x00007f2263afa65c n/a (libgallium-24.3.3.so + 0x4fa65c)
                                                        #5  0x00007f2274659168 start_thread (libc.so.6 + 0x71168)
                                                        #6  0x00007f22746dd14c __clone3 (libc.so.6 + 0xf514c)
                                                        
                                                        Stack trace of thread 12013:
                                                        #0  0x00007f22746557e9 __futex_abstimed_wait_common (libc.so.6 + 0x6d7e9)
                                                        #1  0x00007f2274658239 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x70239)
                                                        #2  0x00007f2263afa72d n/a (libgallium-24.3.3.so + 0x4fa72d)
                                                        #3  0x00007f2263ac558b n/a (libgallium-24.3.3.so + 0x4c558b)
                                                        #4  0x00007f2263afa65c n/a (libgallium-24.3.3.so + 0x4fa65c)
                                                        #5  0x00007f2274659168 start_thread (libc.so.6 + 0x71168)
                                                        #6  0x00007f22746dd14c __clone3 (libc.so.6 + 0xf514c)
                                                        
                                                        Stack trace of thread 12012:
                                                        #0  0x00007f22746557e9 __futex_abstimed_wait_common (libc.so.6 + 0x6d7e9)
                                                        #1  0x00007f2274658239 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x70239)
                                                        #2  0x00007f2263afa72d n/a (libgallium-24.3.3.so + 0x4fa72d)
                                                        #3  0x00007f2263ac558b n/a (libgallium-24.3.3.so + 0x4c558b)
                                                        #4  0x00007f2263afa65c n/a (libgallium-24.3.3.so + 0x4fa65c)
                                                        #5  0x00007f2274659168 start_thread (libc.so.6 + 0x71168)
                                                        #6  0x00007f22746dd14c __clone3 (libc.so.6 + 0xf514c)
                                                        
                                                        Stack trace of thread 12015:
                                                        #0  0x00007f22746557e9 __futex_abstimed_wait_common (libc.so.6 + 0x6d7e9)
                                                        #1  0x00007f2274658239 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x70239)
                                                        #2  0x00007f2263afa72d n/a (libgallium-24.3.3.so + 0x4fa72d)
                                                        #3  0x00007f2263ac558b n/a (libgallium-24.3.3.so + 0x4c558b)
                                                        #4  0x00007f2263afa65c n/a (libgallium-24.3.3.so + 0x4fa65c)
                                                        #5  0x00007f2274659168 start_thread (libc.so.6 + 0x71168)
                                                        #6  0x00007f22746dd14c __clone3 (libc.so.6 + 0xf514c)
                                                        
                                                        Stack trace of thread 12008:
                                                        #0  0x00007f22746557e9 __futex_abstimed_wait_common (libc.so.6 + 0x6d7e9)
                                                        #1  0x00007f2274658239 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x70239)
                                                        #2  0x00007f2263afa72d n/a (libgallium-24.3.3.so + 0x4fa72d)
                                                        #3  0x00007f2263ac558b n/a (libgallium-24.3.3.so + 0x4c558b)
                                                        #4  0x00007f2263afa65c n/a (libgallium-24.3.3.so + 0x4fa65c)
                                                        #5  0x00007f2274659168 start_thread (libc.so.6 + 0x71168)
                                                        #6  0x00007f22746dd14c __clone3 (libc.so.6 + 0xf514c)
                                                        
                                                        Stack trace of thread 12024:
                                                        #0  0x00007f22746dfa2d __libc_msgrcv (libc.so.6 + 0xf7a2d)
                                                        #1  0x000055c9468e6c85 _ZL15msg_read_threadv (mangoapp + 0x20c85)
                                                        #2  0x000055c946a56e64 execute_native_thread_routine (mangoapp + 0x190e64)
                                                        #3  0x00007f2274659168 start_thread (libc.so.6 + 0x71168)
                                                        #4  0x00007f22746dd14c __clone3 (libc.so.6 + 0xf514c)
                                                        
                                                        Stack trace of thread 12009:
                                                        #0  0x00007f22746557e9 __futex_abstimed_wait_common (libc.so.6 + 0x6d7e9)
                                                        #1  0x00007f2274658239 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x70239)
                                                        #2  0x00007f2263afa72d n/a (libgallium-24.3.3.so + 0x4fa72d)
                                                        #3  0x00007f2263ac558b n/a (libgallium-24.3.3.so + 0x4c558b)
                                                        #4  0x00007f2263afa65c n/a (libgallium-24.3.3.so + 0x4fa65c)
                                                        #5  0x00007f2274659168 start_thread (libc.so.6 + 0x71168)
                                                        #6  0x00007f22746dd14c __clone3 (libc.so.6 + 0xf514c)
                                                        
                                                        Stack trace of thread 12010:
                                                        #0  0x00007f22746557e9 __futex_abstimed_wait_common (libc.so.6 + 0x6d7e9)
                                                        #1  0x00007f2274658239 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x70239)
                                                        #2  0x00007f2263afa72d n/a (libgallium-24.3.3.so + 0x4fa72d)
                                                        #3  0x00007f2263ac558b n/a (libgallium-24.3.3.so + 0x4c558b)
                                                        #4  0x00007f2263afa65c n/a (libgallium-24.3.3.so + 0x4fa65c)
                                                        #5  0x00007f2274659168 start_thread (libc.so.6 + 0x71168)
                                                        #6  0x00007f22746dd14c __clone3 (libc.so.6 + 0xf514c)#5  0x00007f2274659168 start_thread (libc.so.6 + 0x71168)
                                                        #6  0x00007f22746dd14c __clone3 (libc.so.6 + 0xf514c)
                                                        Stack trace of thread 12016:
                                                        #0  0x00007f22746a5713 clock_nanosleep@GLIBC_2.2.5 (libc.so.6 + 0xbd713)
                                                        #1  0x00007f22746b1807 __nanosleep (libc.so.6 + 0xc9807)
                                                        #2  0x000055c94694aeb7 _ZL11fileChangedP13notify_thread.lto_priv.0 (mangoapp + 0x84eb7)
                                                        #3  0x000055c946a56e64 execute_native_thread_routine (mangoapp + 0x190e64)
                                                        #4  0x00007f2274659168 start_thread (libc.so.6 + 0x71168)
                                                        #5  0x00007f22746dd14c __clone3 (libc.so.6 + 0xf514c)
                                                        ELF object binary architecture: AMD x86-64
Feb 16 16:50:58 bazzite-lounge systemd[1]: systemd-coredump@235-12026-0.service: Deactivated successfully.
Feb 16 16:50:58 bazzite-lounge audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-coredump@235-12026-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Feb 16 16:50:58 bazzite-lounge systemd[1]: systemd-coredump@235-12026-0.service: Consumed 224ms CPU time, 132.9M memory peak.
Feb 16 16:50:58 bazzite-lounge audit: BPF prog-id=961 op=UNLOAD
Feb 16 16:50:58 bazzite-lounge audit: BPF prog-id=960 op=UNLOAD
Feb 16 16:50:58 bazzite-lounge audit: BPF prog-id=959 op=UNLOAD
Feb 16 16:50:58 bazzite-lounge gamescope-session-plus[2597]: /usr/share/gamescope-session-plus/gamescope-session-plus: line 343: 12005 Segmentation fault      (core dumped) mangoapp
Feb 16 16:50:58 bazzite-lounge gamescope-session-plus[2597]: + true
Feb 16 16:50:58 bazzite-lounge gamescope-session-plus[2597]: + mangoapp
Feb 16 16:50:58 bazzite-lounge gamescope-session-plus[12041]: [2025-02-16 16:50:58.734] [MANGOHUD] [error] [overlay_params.cpp:629] Unknown option 'nis_steam_sharpness'
Feb 16 16:50:58 bazzite-lounge audit[12041]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=2 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=12041 comm="mangoapp" exe="/usr/bin/mangoapp" sig=11 res=1
Feb 16 16:50:58 bazzite-lounge kernel: mangoapp[12041]: segfault at 8 ip 000055bf5609a840 sp 00007fff2cfe8460 error 4 in mangoapp[1a840,55bf56081000+1c5000] likely on CPU 9 (core 1, socket 0)
`

**Comment by CheckYourFax** [comment]
This is a critical bug that is potentially hardware-killing. The constant writes of these coredumps can cause terabytes of data written per day.

**Comment by adr3nal1n** [comment]
Adding my log for reference https://paste.centos.org/view/1d5846b5

**Comment by adr3nal1n** [comment]
Issue resolved after updating to 41.20250216: Stable

**Comment by CheckYourFax** [comment]
Issue resolved here too 👍

**Comment by adr3nal1n** [comment]
Closing issue as it is now resolved, thanks again Bazzite devs for all your work.

**Comment by Archpresident** [comment]
I have a similar problem on archlinux with version 0.8.0-2 of mangohud of the official repositories. Mangoapp in a gamescope session on tty2 separate from sway continuously creates core dump and clogs the am reaching up to 17 gb of ram occupied

  

 [dmesg](https://pastebin.com/PSFHp5mD)

[journalctl](https://pastebin.com/DspaAeN3)
