### ISSUE TITLE
ROG Ally (Z1 Extreme): Controller (and other inputs) gets permanently disabled after a while until restart.

### ISSUE THREAD

**Issue by SomeoneIsWorking** [ublue-os/bazzite#2406]
While using the device, after a while.
These stop working altogether
- Bluetooth
- Built-in controller
- The input devices I connect via USB (I tried a Keyboard)

I don't know what triggers this, it seems to be totally random.
Restart fixes it.

The touch screen still works. (And power and volume buttons)

But this didn't always used to happen.
First 2 months I installed Bazzite, it was smooth sailing.
Now the last month this is happening during all my gaming sessions.
I think it doesn't happen if I'm using an external controller.
~~One potential case is I think I switched the controller type to Steam Controller around that time but I'm not sure.~~
I always update Steam in gaming mode and use System Update in the desktop mode so maybe an update eventually fixes it.
But no luck so far.
~~I'll switch to another controller type and after gathering some info, I'll report back.~~
I wanted to post this here so anyone who maybe shares the same problem will see it.

**Comment by iachurakov** [comment]
I have similar issue, rog ally x, built-in controller stopped working after hibernation. Restart fixed it. OS F41.20250317

**Comment by greargon285** [comment]
It happened to my z1 extreme 4 times already in different games in gaming mode.

Nothing works, except touch screen, volume buttons, power button and USB peripherals.

I can swap the screen to pull the HHD side menu and steam keyboard(confusing), but not the steam side menu.

**Comment by n0k0m3** [comment]
Revert to 20250216 or older images, linked to other issue

**Comment by CheckYourFax** [comment]
I'm assuming this has been fixed in the latest version?

**Comment by antheas** [comment]
No it's not fixed. It's a steam bug. Steam bugs out and stops receiving input from the controller. You can tell because it still works in the controller tester

**Comment by CheckYourFax** [comment]
Is there an issue open upstream?

**Comment by antheas** [comment]
Don't think so. Go for it if you can reproduce.

**Comment by CheckYourFax** [comment]
I haven't been able to reproduce it at all on my lgo.

**Comment by novkien** [comment]
I have same issue, playing RDR2 then sleep, after wake the controller totally disabled. only works on steamUI until restart game.

**Comment by cr4zyc4t** [comment]
I have some issue with The Last of Us, other games work fine.
I notice that after waking up, the game actually recognize controller for 1s before completely disabled

**Comment by MessiahMozgus** [comment]
> I have some issue with The Last of Us, suspend then wake up, lost in-game controller while OS still recognize it, I need to open steam menu to kill the game. Other games work fine. I notice that after waking up, the game actually recognize controller for 1s before completely disabled

Rog Ally here. Having the same issue here. On newest stable proton as well as ProtonGE 9-1 which I am using for Berserk. Was getting this issue in Multiversus and other games. Just started happening this week. Never had this before and I've been on Bazzite for half a year.

8 months ago an issue was found that sounds like this, but unfortunately I definitely dont have this setting enabled, so thats not a fix:

Turning on the wake animation when resuming from sleep causes the device to act erratically.

No controls outside of Steam.

Steam's top and bottom panels missing.

**Comment by SteevenEleven** [comment]
Same for me, ROG ALLY x
Since 2 update I think, if the console goes to sleep, the controller will kind of reconnect too late and in 2 games (as far as I tried) Fallout New Vegas and Starwars Outlaws, it's gone, it won't reconnect and the game will be unaccesible.
Up to now I've made lot of tries and it's just 100% sure it will happen. I didn't found any solutions.

**Comment by antheas** [comment]
Post a log from handheld Daemon after you wake up. Are all of you ally non-x owners?

**Comment by antheas** [comment]
> Same for me, ROG ALLY x Since 2 update I think, if the console goes to sleep, the controller will kind of reconnect too late and in 2 games (as far as I tried) Fallout New Vegas and Starwars Outlaws, it's gone, it won't reconnect and the game will be unaccesible. Up to now I've made lot of tries and it's just 100% sure it will happen. I didn't found any solutions.

My Ally X test unit works perfect on latest bazzite on Super meat boy, which is a game that has problems if the controller disconnects. One of you post a log please.

**Comment by GarThor** [comment]
I have a similar issue with the steam controller over bluetooth.  Eventually it just cuts out.

Looks like it's still detected as "connected" in the bluetooth settings menu, but Steam doesn't see it at all, and it's completely non-functional in desktop mode.

**Comment by SteevenEleven** [comment]
@antheas Thanks, I was trying to make fetch a log and then I saw the "downgrade to previous version" or something similar.  The version I had was 42.20250425 ; now it's back to 3.15.4 and working well (for the controler lost after wake up).

**Comment by antheas** [comment]
> @antheas Thanks, I was trying to make fetch a log and then I saw the "downgrade to previous version" or something similar.  The version I had was 42.20250425 ; now it's back to 3.15.4 and working well (for the controler lost after wake up).

So, it works now? I'm confused. Can you update to the latest version and see if it works?

**Comment by GarThor** [comment]
Sorry, I'm a little new to Bazzite (and fedora/rh distros in general).  What did you downgrade exactly?  The OS version?  Some software on the host?

**Comment by antheas** [comment]
Guys grab a log so if there is an issue we can fix this. Stop sidetracking

**Comment by GarThor** [comment]
I'd love to...

What log would you like me to copy?

**Comment by CheckYourFax** [comment]
`journalctl -b -1 > ~/lastboot.txt`

Then upload that file here.

**Comment by GarThor** [comment]
For clarity... 

o Reboot
o journalctl -b -1 > ~/lastboot.txt (before the issue occurs?)
o upload

**Comment by antheas** [comment]
After the issue occurs

**Comment by CheckYourFax** [comment]
> For clarity...
> 
> o Reboot o journalctl -b -1 > ~/lastboot.txt (before the issue occurs?) o upload

After it occurs and are basically forced to reboot. Reboot and then upload the log. Doesn't matter anymore after you rebooted, but make sure the issue occurred before you rebooted.

**Comment by antheas** [comment]
The controller still works in steam. Just upload the log then. You can get the same from hhd.

If you reboot use the command. Otherwise replace -1 with 0

**Comment by GarThor** [comment]
Hmm... that's fun...

I was going to do as you said, and post the logs here, but after rebooting twice to make sure I have a clean log to compare it against, I've yet to actually reproduce the issue.  It's been nearly an hour, and my controller is still working fine... -_-

Quantum bugs, yay!

**Comment by antheas** [comment]
Ok guys, i figured out the problem. Fix is in testing

> Edit... after a few hours of watching some tv, I went to pause the show before the next episode came on. I noticed the steam controller was powered off... probably due to inactivity. Powering it back on seems to have yielded the results from the previous testing.

It is unfortunate I do not see this but I do not get emails about edits.

Turns out that when the Ally is asleep and you plug it in, the kernel partially awakes and this sometimes caused a timer to lapse and expire the cached controller, so it was recreated after sleep and that broke games that depend on that. Very hard bug to reproduce.

https://github.com/hhd-dev/hhd/releases/tag/v3.15.7

**Comment by GarThor** [comment]
I switched back to ubuntu... i was having other issues w/ bazzite that weren't occuring with ubuntu, so it seemed like the easiest solution...

I think I might just get a new controller... this one seems to be having issues, and it might be easier to diag if i can eliminate some variabkes.

**Comment by antheas** [comment]
This fix is specific to handheld devices unfortunately

**Comment by novkien** [comment]
> This fix is specific to handheld devices unfortunately

How to update hhd to 3.15.7. 3.15.6 is showed as lastest

**Comment by antheas** [comment]
> > This fix is specific to handheld devices unfortunately
> 
> How to update hhd to 3.15.7. 3.15.6 is showed as lastest

You can switch to bazzite testing, or press switch to hhd beta in the hhd updates dialog that will switch you to it until you reboot. We plan to push this out to bazzite stable in a few hours.

**Comment by MessiahMozgus** [comment]
> Ok guys, i figured out the problem. Fix is in testing
> 
> > Edit... after a few hours of watching some tv, I went to pause the show before the next episode came on. I noticed the steam controller was powered off... probably due to inactivity. Powering it back on seems to have yielded the results from the previous testing.
> 
> It is unfortunate I do not see this but I do not get emails about edits.
> 
> Turns out that when the Ally is asleep and you plug it in, the kernel partially awakes and this sometimes caused a timer to lapse and expire the cached controller, so it was recreated after sleep and that broke games that depend on that. Very hard bug to reproduce.
> 
> https://github.com/hhd-dev/hhd/releases/tag/v3.15.7

Will you let us know when it's in stable? Thanks.

**Comment by novkien** [comment]
> > > This fix is specific to handheld devices unfortunately
> > 
> > 
> > How to update hhd to 3.15.7. 3.15.6 is showed as lastest
> 
> You can switch to bazzite testing, or press switch to hhd beta in the hhd updates dialog that will switch you to it until you reboot. We plan to push this out to bazzite stable in a few hours.


Hello again, thanks for the hardwork, but the issue still exist on my rog ally. Here is the paste of last boot which is the issue reproduced

https://paste.centos.org/view/32990e6f

**Comment by novkien** [comment]
The procedure of my lastboot is, restart, launch the game( the witcher 3) when the game is on menu ui sleep the device then resume. The controller can not work. Open hhe menu and upload the lastboot

**Comment by novkien** [comment]
@antheas ok, you re right. The root caused is proton. I have changed to lower version of proton then the system back to normal condition.
