### ISSUE TITLE
OneXplayer G1 Display colour problem

### ISSUE THREAD

**Issue by DMaximillian** [ublue-os/bazzite#2550]
### Describe the bug

When you touch touchpad on external keyboard or touch touch-keyboard in Game mode some kind of yellow display filter is turning on with a bit FPS drop (when mouse icon appears). After pressing gamepad buttons or external keyboard buttons everything goes normal (when mouse disappears).
Moreover, when you open left steam menu - same happens.

### What did you expect to happen?

I expected no difference between display work when uses touchpad or touch-keyboard

### Output of `rpm-ostree status`

```shell
bazzite@bazzite:~$ rpm-ostree status 
State: idle
Deployments:
ostres-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable 
Digest: sha256:bd13f05f33bd1003b37ff5f3d34e031f99f28f31be1324c44e415f4556b6b45b 
Version: 42.20250425 (2025-04-25T16:42:58Z)

ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable 
Digest: sha256:76b3f9e1dbb86bcfd1f18930a1af887533d3de600c1c21fd94c01174cf658bfc 
Version: 41.20250409.1 (2025-04-09T19:14:25Z)
```

### Hardware

ONEXPLAYER G1 A

**Comment by CheckYourFax** [comment]
In Gaming Mode go to Display->Use Native Color Temperature

That should fix it

**Comment by DMaximillian** [comment]
Did it, it helped in desktop, but ingame problem still persist
