### ISSUE TITLE
Several audio issues (and sometimes video) with suspend/wake on GPD Win 4 2013 7640u

### ISSUE THREAD

**Issue by plrusek** [ublue-os/bazzite#2615]
### Describe the bug

1. Waking up from suspend tends to produce audio crackles for a while (0:15 on video 1 is when it starts). Pretty much 100% chance of it happening on wake. Does eventually go away, sometimes longer like on the video or sometimes very quickly.

[Video 1](https://www.youtube.com/watch?v=LZrn_wUZ95I)

2. Much more rarily, like 1% of the time, the display will be messed up. Has to be suspended and waked again to fix.

[Video 2](https://www.youtube.com/watch?v=3GhxjfAY-cs)

3. Rare issue where sometimes the device will take a really long time to sleep (about 10-20 seconds), with last second of the audio repeating.

[Video 3](https://youtu.be/Salo-QGydJE)

4. Pretty rare issue where device won't respond to just a single press of the power button. Twice or more needed.

[Video 4](https://www.youtube.com/watch?v=IDljgmaGIKc)

### What did you expect to happen?

1. No audio crackles expected.
2. No visual glitches expected.
3. Fast sleep time expected. Usually it repeats the last second of the audio only once before going to sleep.
4. Single press of the button expected to wake up the device, not multiple.

### Output of `rpm-ostree status`

```shell
bazzite@bazzite:~$ rpm-ostree status
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:5a7243860ed83ea6accb3845ba8948a06ee344163cb4696d6fe79b95abad25e9
                  Version: 42.20250430 (2025-05-01T19:27:27Z)
 
  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck:stable
                   Digest: sha256:76b3f9e1dbb86bcfd1f18930a1af887533d3de600c1c21fd94c01174cf658bfc
                  Version: 41.20250409.1 (2025-04-09T19:14:25Z)
```

### Hardware

GPD Win 4 (2023)
AMD Ryzen 5 7640u
16GB RAM
512GB NVMe

bazzite@bazzite:~$ cat /sys/devices/virtual/dmi/id/product_name
G1618-04

### Extra information or context

Of course, suspend/wake is still usable despite these issues and performs better than anything on Windows. It's just not a completely fixed up experience yet. The first audio issue is probably the only one that really bugs me as it happens every single time. Others are pretty rare.

**Comment by NickelKang** [comment]
I also experience this audio bug on legion go s z1e upon resuming from sleep.  It does eventually stop crackling as you mentioned but it can take several seconds up to 1 minute.

**Comment by satyavratwagle** [comment]
GPD Win 4 (2025)
AMD Ryzen HX 370

I have the same audio crackling issue. 
I've found that for me, if you switch off the wifi, it doesn't crackle when you wake from suspend. Not a solution, but hopefully there is some clue there.

**Comment by NickelKang** [comment]
Legion go s 
AMD Z1E

I can confirm toggling WiFi off before sleep/resume also stops audio crackling on the legion go s z1e.  But yeah, not a fix.  This lead me down the rabbit hole of testing disabling wifi power saver but this did not fix the crackling for me.  
https://docs.bazzite.gg/General/issues_and_resolutions/

**Comment by plrusek** [comment]
A lot of these issues I originally reported I have not seen in a while. It's also entirely possible that most of it was fixed thanks to a BIOS update that I did only after reporting these issues.

The one consistent issue I have right now is that there is no audio after waking from hibernation (said hibernation happening after around 24h, I think in relation to HHD hibernating the device when it asks or under 5% battery). Putting it to sleep and waking up will restore audio.

My advice to previous posters is to update their BIOSes if they haven't already.

**Comment by NickelKang** [comment]
Thanks for chiming in. I still get crackling on a fully patched Stable Bazzite (including BIOS). But I'm also on a different device. (Legion go s Z1E). It is tied to wifi somehow, while it's connecting after sleep resume (Wifi OFF = No crackling).

This does not happen when using official SteamOS, so I suspect Valve is handling pipewire sleep/resume differently in their custom Arch build. I'm not really sure, but I prefer Bazzite for many reasons, so it's worth dealing with some bugs.

**Comment by plrusek** [comment]
I have not had these suspend/wake issues for a long time now, they are not present in Deck 44/testing either so it's definitely gone due to continued support.

The only problem that remains is no audio after waking up from hibernation but that's a separate issue entirely, not even mentioned in the opening comment. Might open a separate issue just for that.
