### ISSUE TITLE
GNOME file chooser freezes applications randomly

### ISSUE THREAD

**Issue by scovik** [ublue-os/bazzite#2658]
### Describe the bug

Multiple applications consistently freeze when opening files through the file chooser dialog. This issue:

* Affects applications across different toolkits (Libadwaita/GTK, Qt, Electron, etc.) including Firefox, Steam, Heroic, and others
* Occurs randomly – sometimes an application works normally, other times it freezes (effectively a coin toss)
* Began occurring recently without any configuration changes or system modifications
* Reproducible across several application types
* Freezes require force-quitting Libadwaita applications

### What did you expect to happen?

File chooser shouldn't freeze applications.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:de25f06ba3cdb4454356ab4ecdffb3253c712a8b619633dfcea41e138aa27ba5
                  Version: 42.20250519.2 (2025-05-20T00:21:54Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:stable
                   Digest: sha256:ccb44a93ba1afff9667e934962e383df18ee0fe66921e9c985611627c2673aae
                  Version: 42.20250519 (2025-05-19T05:07:46Z)
```

### Hardware

Steam Deck LCD (Jupiter)

### Extra information or context

[Screen capture of the bug](https://drive.proton.me/urls/01GFW07VGR#SzKKJ4M4arRZ)

**Layered packages:**
p7zip-plugins

**Installed extensions:**
Alphabetical App Grid
Clipboard Indicator
Statisig
Mic Indicator Visibility Manager

**Comment by badnetmask** [comment]
That happened to me yesterday, after I upgraded to `42.20250519`. But for me Chrome was freezing every single time I tried to save something (I was trying to download a few files). I didn't test any other apps, simply reverted to `42.20250511`.

**Comment by scovik** [comment]
As a temporary workaround, version 42.20250513 does not have this bug.

In case of Deck:
`rpm-ostree rebase ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-deck-gnome:42.20250513`

For desktop:
`rpm-ostree rebase ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-gnome:42.20250513`

What a strange bug.

**Comment by SinnedNima** [comment]
Hey guys, just confirming the bugs. i was on **42.20250519.2** and as @scovik  suggested i rebased to **42.20250513**.
Now everything works fine.

Other people have similar issues like USB disconnection and freezing. I in particular had issues with keyboard mouse and many applications like Librewolf, Discord and Betterbird which were lagging like hell and file uploads were not working either.
Sometimes i couldn't interact with the window bar or address bar or my keyboard mouse randomly refused to work.
My session was still active and all other applications were working, but no input could be made except with GSConnect.
It was possible for me to use my phone to log out of the gnome session and regain control without restarting the system.

I do use input leap to share my keyboard/mouse with my work notebook - that was a nightmare on  **42.20250519.2** as well.

In **42.20250513** uploading photos is working again, files is smooth and thus far, no disconnects from keyboard and mouse. 

`State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-gnome:42.20250513
                   Digest: sha256:ad63ccfe93ced88955d5b0e550b7cc3158b5f2fd895f71660403366f4e1db026
                  Version: 42.20250513 (2025-05-13T16:14:16Z)
          LayeredPackages: android-tools coolercontrol gnome-tweaks liquidctl onedrive

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-gnome:stable
                   Digest: sha256:211e8b9c8c1655d7b57173f7347b9c85619905772d1422f71069b8fb05e8b2f5
                  Version: 42.20250519.2 (2025-05-20T00:18:49Z)
          LayeredPackages: android-tools coolercontrol gnome-tweaks liquidctl onedrive
`

`# System Details Report
---

## Report details
- **Date generated:**                              2025-05-21 21:56:19

## Hardware Information:
- **Hardware Model:**                              Micro-Star International Co., Ltd. MS-7C91
- **Memory:**                                      32.0 GiB
- **Processor:**                                   AMD Ryzen™ 7 5700G with Radeon™ Graphics × 16
- **Graphics:**                                    AMD Radeon™ RX 6950 XT
- **Disk Capacity:**                               3.0 TB

## Software Information:
- **Firmware Version:**                            A.I0
- **OS Name:**                                     Bazzite 42 (FROM Fedora Silverblue)
- **OS Build:**                                    Stable (F42.20250513)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               48
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.14.4-104.bazzite.fc42.x86_64
`

**Comment by castrojo** [comment]
Found the issue, Bazzite needs to pull in: https://bodhi.fedoraproject.org/updates/FEDORA-2025-c358833c5d

See: https://github.com/ublue-os/bluefin/pull/2564

**Comment by KyleGospo** [comment]
Fixed in latest

**Comment by CptWonderful** [comment]
Hey all. I still have this bug in the latest version. Any update on this?
