### ISSUE TITLE
xdg-desktop-portal is crashing with a segfault

### ISSUE THREAD

**Issue by ion-ize** [ublue-os/bazzite#2673]
### Describe the bug

This occurs when attempting to launch the file/folder picker from any chromium/electron based app. This recently started occurring as I was not having issues as recent as 5/12/2025.

### What did you expect to happen?

You should be able to interact with the file picker window then return to the app with the expected files sent to the app, or if cancelled the app should function normally.

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-gnome-nvidia-open:stable-41
                   Digest: sha256:2fb5a81211040d6146d097f5d0408b7bfadb2b517d1284921db84409a6b6bf06
                  Version: 41.20250409.1 (2025-04-09T19:07:51Z)
                     Diff: 3 upgraded, 2170 downgraded, 94 removed, 126 added

● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-gnome-nvidia-open:stable
                   Digest: sha256:0f29f69d63bd38893453a2f1dee0579344505a6fc25c08d480125c9a2ecee3ca
                  Version: 42.20250522.1 (2025-05-22T07:09:04Z)
          LayeredPackages: coolercontrol liquidctl
                 Unlocked: transient

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-gnome-nvidia-open:stable
                   Digest: sha256:0f29f69d63bd38893453a2f1dee0579344505a6fc25c08d480125c9a2ecee3ca
                  Version: 42.20250522.1 (2025-05-22T07:09:04Z)
          LayeredPackages: coolercontrol liquidctl
```

### Hardware

OS: Bazzite 42 (FROM Fedora Silverblue) x86_64
Kernel: Linux 6.14.6-105.bazzite.fc42.x86_64
Display (Acer Technologies 23"): 1200x1920 @ 75 Hz (as 750x1200) in 23" [External]
Display (LC27G7xT): 2560x1440 @ 240 Hz in 27" [External] *
CPU: AMD Ryzen 9 9950X3D (32) @ 5.76 GHz
GPU: NVIDIA GeForce RTX 2080 Ti Rev. A [Discrete]
Memory: 12.31 GiB / 62.42 GiB (20%)
Swap: 0 B / 4.00 GiB (0%)
Disk (/): 28.74 MiB / 28.74 MiB (100%) - overlay [Read-only]
Disk (/sysroot): 778.88 GiB / 952.27 GiB (82%) - btrfs [Read-only]
Disk (/var/mnt/BGD): 2.36 TiB / 3.22 TiB (73%) - ext4
Disk (/var/mnt/Game-Drive): 782.51 GiB / 915.80 GiB (85%) - ext4
Local IP (enp3s0): [redacted]
Locale: en_GB.UTF-8

### Extra information or context

I validated this happens on my system under the following app install types:
-flatpak (both user and system context)
-appimage
-app installed inside a distrobox (tried both fedora and ubuntu distroboxes)

This also occurs even with nvidia_drm.modeset=1  added to kargs.

I tried disabling all gnome extensions.

So far I have tested this with vscode, vscodium, postman, discord, and chrome and all have the issue.

I created a new test user on my device and still had the issue. 

I ran the apps with LIBGL_ALWAYS_SOFTWARE=1 to confirm it was not a GPU driver bug.

I tested on a different system running bazzite 41 and it does not have this issue. After updating that system to the latest stable version (stable-42.20250522.1) it also experiences this issue.

**Comment by ion-ize** [comment]
The rpm-ostree status shows my staged rebase back to bazzite 41 to attempt to get this working again.

**Comment by YisHub** [comment]
Hi, I can confirm I'm experiencing the exact same issue on Bazzite GNOME (NVIDIA). The file picker dialog causes the application (Flatpaks like Chrome, Edge, VSCode, Firefox) to freeze when trying to save a file or open a folder.

**System Information:**

*   **Output of `rpm-ostree status`:**
    ```
    jesus@bazzite:~$ rpm-ostree status
    State: idle
    Deployments:
    ● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-gnome-nvidia:stable
                       Digest: sha256:0eb5d1432f7ae278353dd9dec00ec477fbc285b44736954113293ee91c7e7797
                      Version: 42.20250522.1 (2025-05-22T07:10:17Z)
              LayeredPackages: chromedriver coolercontrol gnome-tweaks liquidctl
    
      ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-gnome-nvidia:stable
                       Digest: sha256:922c2ef64ae90e747616df7a2e5b74fb328d747bdeb6936e659b3a39da7af8b4
                      Version: 42.20250519.2 (2025-05-20T00:24:26Z)
              LayeredPackages: chromedriver coolercontrol gnome-tweaks liquidctl

    ```

*   **`fastfetch` output:**
    ```
      jesus@bazzite
    
     󱋩  bazzite-gnome-nvidia:stable 
     󰣛  Bazzite 42 (FROM Fedora Silverblue)
       Linux 6.14.6-105.bazzite.fc42.x86_64
     󰅐  1 hour, 20 mins
    
     󰾰  Nitro AN515-51 (V1.22)
     󰻠  Intel(R) Core(TM) i5-7300HQ (4) @ 3.50 GHz
     󰍛  NVIDIA GeForce GTX 1050 Mobile [Discrete]
     󰍛  Intel HD Graphics 630 @ 1.00 GHz [Integrated]
       4.33 GiB / 11.56 GiB (37%)
       28.77 MiB / 28.77 MiB (100%) - overlay [Read-only]
       50.91 GiB / 929.93 GiB (5%) - btrfs [Read-only]
     󰍹  1920x1080 @ 60 Hz in 15" [Built-in]
       100% [AC Connected]
    
     󰕮  GNOME 48.1
       Mutter (Wayland)
       bash 5.2.37
       Ptyxis 48.3
     󰏖  2320 (rpm), 76 (flatpak-system), 3 (flatpak-user)


    ```

**Logs:**

*   **`xdg-desktop-portal` :**
    ```
    jesus@bazzite:~$ journalctl --user -u xdg-desktop-portal --boot --no-pager --output=short-iso | tail -n 100
                                                             #7  0x00007ff5b13e8e13 g_signal_emit (libgobject-2.0.so.0 + 0x26e13)
                                                             #8  0x00007ff5b1518b36 dispatch_in_thread_func (libgio-2.0.so.0 + 0xf8b36)
                                                             #9  0x00007ff5b14a078c g_task_thread_pool_thread (libgio-2.0.so.0 + 0x8078c)
                                                             #10 0x00007ff5b1667ac2 g_thread_pool_thread_proxy (libglib-2.0.so.0 + 0x78ac2)
                                                             #11 0x00007ff5b16668e2 g_thread_proxy (libglib-2.0.so.0 + 0x778e2)
                                                             #12 0x00007ff5b0ff71d4 start_thread (libc.so.6 + 0x711d4)
                                                             #13 0x00007ff5b1079cec __clone3 (libc.so.6 + 0xf3cec)
                                                             
                                                             Stack trace of thread 11551:
                                                             #0  0x00007ff5b0fff6c2 __syscall_cancel_arch (libc.so.6 + 0x796c2)
                                                             #1  0x00007ff5b0ff39da __internal_syscall_cancel (libc.so.6 + 0x6d9da)
                                                             #2  0x00007ff5b0ff3a24 __syscall_cancel (libc.so.6 + 0x6da24)
                                                             #3  0x00007ff5b106d176 ppoll (libc.so.6 + 0xe7176)
                                                             #4  0x00007ff5b1639210 g_main_context_iterate_unlocked.isra.0 (libglib-2.0.so.0 + 0x4a210)
                                                             #5  0x00007ff5b16392d3 g_main_context_iteration (libglib-2.0.so.0 + 0x4a2d3)
                                                             #6  0x00007ff5b1639321 glib_worker_main (libglib-2.0.so.0 + 0x4a321)
                                                             #7  0x00007ff5b16668e2 g_thread_proxy (libglib-2.0.so.0 + 0x778e2)
                                                             #8  0x00007ff5b0ff71d4 start_thread (libc.so.6 + 0x711d4)
                                                             #9  0x00007ff5b1079cec __clone3 (libc.so.6 + 0xf3cec)
                                                             
                                                             Stack trace of thread 11556:
                                                             #0  0x00007ff5b0fff6c2 __syscall_cancel_arch (libc.so.6 + 0x796c2)
                                                             #1  0x00007ff5b0ff39da __internal_syscall_cancel (libc.so.6 + 0x6d9da)
                                                             #2  0x00007ff5b0ff3a24 __syscall_cancel (libc.so.6 + 0x6da24)
                                                             #3  0x00007ff5b106d176 ppoll (libc.so.6 + 0xe7176)
                                                             #4  0x00007ff5b1639210 g_main_context_iterate_unlocked.isra.0 (libglib-2.0.so.0 + 0x4a210)
                                                             #5  0x00007ff5b16392d3 g_main_context_iteration (libglib-2.0.so.0 + 0x4a2d3)
                                                             #6  0x00007ff5a04dfb1d dconf_gdbus_worker_thread (libdconfsettings.so + 0x5b1d)
                                                             #7  0x00007ff5b16668e2 g_thread_proxy (libglib-2.0.so.0 + 0x778e2)
                                                             #8  0x00007ff5b0ff71d4 start_thread (libc.so.6 + 0x711d4)
                                                             #9  0x00007ff5b1079cec __clone3 (libc.so.6 + 0xf3cec)
                                                             
                                                             Stack trace of thread 11552:
                                                             #0  0x00007ff5b1077a8d syscall (libc.so.6 + 0xf1a8d)
                                                             #1  0x00007ff5b165c3ed g_cond_wait (libglib-2.0.so.0 + 0x6d3ed)
                                                             #2  0x00007ff5b15f8e2c g_async_queue_pop_intern_unlocked (libglib-2.0.so.0 + 0x9e2c)
                                                             #3  0x00007ff5b1666d94 g_thread_pool_spawn_thread (libglib-2.0.so.0 + 0x77d94)
                                                             #4  0x00007ff5b16668e2 g_thread_proxy (libglib-2.0.so.0 + 0x778e2)
                                                             #5  0x00007ff5b0ff71d4 start_thread (libc.so.6 + 0x711d4)
                                                             #6  0x00007ff5b1079cec __clone3 (libc.so.6 + 0xf3cec)
                                                             
                                                             Stack trace of thread 11557:
                                                             #0  0x00007ff5b0fff6c2 __syscall_cancel_arch (libc.so.6 + 0x796c2)
                                                             #1  0x00007ff5b0ff39da __internal_syscall_cancel (libc.so.6 + 0x6d9da)
                                                             #2  0x00007ff5b0ff3a24 __syscall_cancel (libc.so.6 + 0x6da24)
                                                             #3  0x00007ff5b1079fd5 epoll_wait (libc.so.6 + 0xf3fd5)
                                                             #4  0x00007ff58b2570b9 impl_pollfd_wait (libspa-support.so + 0x180b9)
                                                             #5  0x00007ff58b24473f loop_iterate (libspa-support.so + 0x573f)
                                                             #6  0x00007ff5b133ecf4 do_loop (libpipewire-0.3.so.0 + 0x77cf4)
                                                             #7  0x00007ff5b0ff71d4 start_thread (libc.so.6 + 0x711d4)
                                                             #8  0x00007ff5b1079cec __clone3 (libc.so.6 + 0xf3cec)
                                                             
                                                             Stack trace of thread 11554:
                                                             #0  0x00007ff5b1077a8d syscall (libc.so.6 + 0xf1a8d)
                                                             #1  0x00007ff5b165d2ab g_cond_wait_until (libglib-2.0.so.0 + 0x6e2ab)
                                                             #2  0x00007ff5b15f8ded g_async_queue_pop_intern_unlocked (libglib-2.0.so.0 + 0x9ded)
                                                             #3  0x00007ff5b1667b1a g_thread_pool_thread_proxy (libglib-2.0.so.0 + 0x78b1a)
                                                             #4  0x00007ff5b16668e2 g_thread_proxy (libglib-2.0.so.0 + 0x778e2)
                                                             #5  0x00007ff5b0ff71d4 start_thread (libc.so.6 + 0x711d4)
                                                             #6  0x00007ff5b1079cec __clone3 (libc.so.6 + 0xf3cec)
                                                             
                                                             Stack trace of thread 11558:
                                                             #0  0x00007ff5b0fff6c2 __syscall_cancel_arch (libc.so.6 + 0x796c2)
                                                             #1  0x00007ff5b0ff39da __internal_syscall_cancel (libc.so.6 + 0x6d9da)
                                                             #2  0x00007ff5b1043902 clock_nanosleep@GLIBC_2.2.5 (libc.so.6 + 0xbd902)
                                                             #3  0x00007ff5b104f657 __nanosleep (libc.so.6 + 0xc9657)
                                                             #4  0x00007ff5b1061aee sleep (libc.so.6 + 0xdbaee)
                                                             #5  0x0000562883e96d4b n/a (/db/d7385060805d85ad43244b16a653d1cf452d69c34cc79010a684de54c0472d.file + 0x47d4b)
                                                             #6  0x00007ff5b16668e2 g_thread_proxy (libglib-2.0.so.0 + 0x778e2)
                                                             #7  0x00007ff5b0ff71d4 start_thread (libc.so.6 + 0x711d4)
                                                             #8  0x00007ff5b1079cec __clone3 (libc.so.6 + 0xf3cec)
                                                             
                                                             Stack trace of thread 11553:
                                                             #0  0x00007ff5b0fff6c2 __syscall_cancel_arch (libc.so.6 + 0x796c2)
                                                             #1  0x00007ff5b0ff39da __internal_syscall_cancel (libc.so.6 + 0x6d9da)
                                                             #2  0x00007ff5b0ff3a24 __syscall_cancel (libc.so.6 + 0x6da24)
                                                             #3  0x00007ff5b106d176 ppoll (libc.so.6 + 0xe7176)
                                                             #4  0x00007ff5b1639210 g_main_context_iterate_unlocked.isra.0 (libglib-2.0.so.0 + 0x4a210)
                                                             #5  0x00007ff5b16393cf g_main_loop_run (libglib-2.0.so.0 + 0x4a3cf)
                                                             #6  0x00007ff5b15072b2 gdbus_shared_thread_func.lto_priv.0 (libgio-2.0.so.0 + 0xe72b2)
                                                             #7  0x00007ff5b16668e2 g_thread_proxy (libglib-2.0.so.0 + 0x778e2)
                                                             #8  0x00007ff5b0ff71d4 start_thread (libc.so.6 + 0x711d4)
                                                             #9  0x00007ff5b1079cec __clone3 (libc.so.6 + 0xf3cec)
                                                             
                                                             Stack trace of thread 11549:
                                                             #0  0x00007ff5b0fff6c2 __syscall_cancel_arch (libc.so.6 + 0x796c2)
                                                             #1  0x00007ff5b0ff39da __internal_syscall_cancel (libc.so.6 + 0x6d9da)
                                                             #2  0x00007ff5b0ff3a24 __syscall_cancel (libc.so.6 + 0x6da24)
                                                             #3  0x00007ff5b106d176 ppoll (libc.so.6 + 0xe7176)
                                                             #4  0x00007ff5b1639210 g_main_context_iterate_unlocked.isra.0 (libglib-2.0.so.0 + 0x4a210)
                                                             #5  0x00007ff5b16393cf g_main_loop_run (libglib-2.0.so.0 + 0x4a3cf)
                                                             #6  0x0000562883e5dcd6 n/a (/db/d7385060805d85ad43244b16a653d1cf452d69c34cc79010a684de54c0472d.file + 0xecd6)
                                                             #7  0x00007ff5b0f895f5 __libc_start_call_main (libc.so.6 + 0x35f5)
                                                             #8  0x00007ff5b0f896a8 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x36a8)
                                                             #9  0x0000562883e5e405 n/a (/db/d7385060805d85ad43244b16a653d1cf452d69c34cc79010a684de54c0472d.file + 0xf405)
                                                             ELF object binary architecture: AMD x86-64
    2025-05-23T08:42:01-03:00 bazzite systemd[2551]: xdg-desktop-portal.service: Main process exited, code=dumped, status=11/SEGV
    2025-05-23T08:42:01-03:00 bazzite systemd[2551]: xdg-desktop-portal.service: Failed with result 'core-dump'.
    2025-05-23T08:42:02-03:00 bazzite systemd[2551]: Starting xdg-desktop-portal.service - Portal service...
    2025-05-23T08:42:02-03:00 bazzite systemd[2551]: Started xdg-desktop-portal.service - Portal service.
    ```

*   **`xdg-desktop-portal-gnome` :**
    ```
    jesus@bazzite:~$ journalctl --user -u xdg-desktop-portal-gnome --boot --no-pager --output=short-iso | tail -n 50
    2025-05-23T07:14:35-03:00 bazzite systemd[2551]: Starting xdg-desktop-portal-gnome.service - Portal service (GNOME implementation)...
    2025-05-23T07:14:36-03:00 bazzite systemd[2551]: Started xdg-desktop-portal-gnome.service - Portal service (GNOME implementation).
    2025-05-23T07:14:41-03:00 bazzite xdg-desktop-por[3681]: Failed to associate portal window with parent window 
    2025-05-23T07:14:41-03:00 bazzite xdg-desktop-portal-gnome[3681]: MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:873: FINISHME: support YUV colorspace with DRM format modifiers
    2025-05-23T07:14:41-03:00 bazzite xdg-desktop-portal-gnome[3681]: MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:905: FINISHME: support more multi-planar formats with DRM modifiers
    2025-05-23T07:14:53-03:00 bazzite xdg-desktop-por[3681]: Failed to stop screen cast session: GDBus.Error:org.freedesktop.DBus.Error.Failed: Session not started
    2025-05-23T07:14:55-03:00 bazzite xdg-desktop-por[3681]: Failed to associate portal window with parent window 
    2025-05-23T07:14:57-03:00 bazzite xdg-desktop-por[3681]: Failed to stop screen cast session: GDBus.Error:org.freedesktop.DBus.Error.Failed: Session not started
    2025-05-23T07:15:12-03:00 bazzite xdg-desktop-por[3681]: Failed to associate portal window with parent window 
    2025-05-23T08:13:39-03:00 bazzite xdg-desktop-por[3681]: Failed to associate portal window with parent window 
    2025-05-23T08:13:49-03:00 bazzite systemd[2551]: Stopping xdg-desktop-portal-gnome.service - Portal service (GNOME implementation)...
    2025-05-23T08:13:49-03:00 bazzite systemd[2551]: Stopped xdg-desktop-portal-gnome.service - Portal service (GNOME implementation).
    2025-05-23T08:13:49-03:00 bazzite systemd[2551]: xdg-desktop-portal-gnome.service: Consumed 1.399s CPU time, 85.4M memory peak.
    2025-05-23T08:13:49-03:00 bazzite systemd[2551]: Starting xdg-desktop-portal-gnome.service - Portal service (GNOME implementation)...
    2025-05-23T08:13:50-03:00 bazzite systemd[2551]: Started xdg-desktop-portal-gnome.service - Portal service (GNOME implementation).
    2025-05-23T08:13:58-03:00 bazzite xdg-desktop-por[9040]: Failed to associate portal window with parent window 
    2025-05-23T08:13:58-03:00 bazzite xdg-desktop-portal-gnome[9040]: MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:873: FINISHME: support YUV colorspace with DRM format modifiers
    2025-05-23T08:13:58-03:00 bazzite xdg-desktop-portal-gnome[9040]: MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:905: FINISHME: support more multi-planar formats with DRM modifiers
    2025-05-23T08:14:25-03:00 bazzite systemd[2551]: Stopping xdg-desktop-portal-gnome.service - Portal service (GNOME implementation)...
    2025-05-23T08:14:25-03:00 bazzite systemd[2551]: Stopped xdg-desktop-portal-gnome.service - Portal service (GNOME implementation).
    2025-05-23T08:14:25-03:00 bazzite systemd[2551]: Starting xdg-desktop-portal-gnome.service - Portal service (GNOME implementation)...
    2025-05-23T08:14:25-03:00 bazzite systemd[2551]: Started xdg-desktop-portal-gnome.service - Portal service (GNOME implementation).
    2025-05-23T08:14:32-03:00 bazzite xdg-desktop-por[9627]: Failed to associate portal window with parent window 
    2025-05-23T08:14:33-03:00 bazzite xdg-desktop-portal-gnome[9627]: MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:873: FINISHME: support YUV colorspace with DRM format modifiers
    2025-05-23T08:14:33-03:00 bazzite xdg-desktop-portal-gnome[9627]: MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:905: FINISHME: support more multi-planar formats with DRM modifiers
    2025-05-23T08:37:11-03:00 bazzite systemd[2551]: Stopping xdg-desktop-portal-gnome.service - Portal service (GNOME implementation)...
    2025-05-23T08:37:11-03:00 bazzite systemd[2551]: Stopped xdg-desktop-portal-gnome.service - Portal service (GNOME implementation).
    2025-05-23T08:37:11-03:00 bazzite systemd[2551]: Starting xdg-desktop-portal-gnome.service - Portal service (GNOME implementation)...
    2025-05-23T08:37:11-03:00 bazzite systemd[2551]: Started xdg-desktop-portal-gnome.service - Portal service (GNOME implementation).
    2025-05-23T08:37:19-03:00 bazzite systemd[2551]: Stopping xdg-desktop-portal-gnome.service - Portal service (GNOME implementation)...
    2025-05-23T08:37:19-03:00 bazzite systemd[2551]: Stopped xdg-desktop-portal-gnome.service - Portal service (GNOME implementation).
    2025-05-23T08:37:19-03:00 bazzite systemd[2551]: Starting xdg-desktop-portal-gnome.service - Portal service (GNOME implementation)...
    2025-05-23T08:37:19-03:00 bazzite systemd[2551]: Started xdg-desktop-portal-gnome.service - Portal service (GNOME implementation).
    2025-05-23T08:37:26-03:00 bazzite xdg-desktop-por[11446]: Failed to associate portal window with parent window 
    2025-05-23T08:37:26-03:00 bazzite xdg-desktop-portal-gnome[11446]: MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:873: FINISHME: support YUV colorspace with DRM format modifiers
    2025-05-23T08:37:26-03:00 bazzite xdg-desktop-portal-gnome[11446]: MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:905: FINISHME: support more multi-planar formats with DRM modifiers
    2025-05-23T08:41:27-03:00 bazzite systemd[2551]: Stopping xdg-desktop-portal-gnome.service - Portal service (GNOME implementation)...
    2025-05-23T08:41:27-03:00 bazzite systemd[2551]: Stopped xdg-desktop-portal-gnome.service - Portal service (GNOME implementation).
    2025-05-23T08:41:27-03:00 bazzite systemd[2551]: Starting xdg-desktop-portal-gnome.service - Portal service (GNOME implementation)...
    2025-05-23T08:41:28-03:00 bazzite systemd[2551]: Started xdg-desktop-portal-gnome.service - Portal service (GNOME implementation).
    2025-05-23T08:41:35-03:00 bazzite xdg-desktop-por[11562]: Failed to associate portal window with parent window 
    2025-05-23T08:41:35-03:00 bazzite xdg-desktop-portal-gnome[11562]: MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:873: FINISHME: support YUV colorspace with DRM format modifiers
    2025-05-23T08:41:35-03:00 bazzite xdg-desktop-portal-gnome[11562]: MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:905: FINISHME: support more multi-planar formats with DRM modifiers
    
    ```

**Observations:**
*   The `xdg-desktop-portal` service crashes with a SEGV (Segmentation Fault) and `code=dumped`.
*   The `xdg-desktop-portal-gnome` log shows "Failed to associate portal window with parent window" and MESA-INTEL warnings right before or around the time of the crash.
*   The issue started after updating to Bazzite version `42.20250522.1`.

Happy to provide more information if needed. Thanks for looking into this!

**Comment by YisHub** [comment]
**UPDATE:** I've rolled back to Version: `42.20250519.2` (2025-05-20T00:24:26Z) and unfortunately the issue with xdg-desktop-portal crashing and freezing file dialogs persists even on this earlier build.

**Comment by Pryka** [comment]
There is a bug in xdg-desktop-portal, we experienced the same in Bluefin. 

Fixed by this PR - https://github.com/ublue-os/bluefin/pull/2564

**Comment by KyleGospo** [comment]
Fixed in latest

**Comment by ion-ize** [comment]
This is still occurring for me on the latest stable version (42.20250522.1 at the time of writing this) I rebased over to the testing branch (42.20250526) and it is resolved there for now.
