### ISSUE TITLE
KDE screen locker broken after bazzite:stable 42.20250706 [USER FIX]

### ISSUE THREAD

**Issue by Sgaytor** [ublue-os/bazzite#2856]
### Describe the bug

When I locked my screen I was greeted with a screen informing me that the screen locker was broken and how to manually unlock the screen via the tty

### What did you expect to happen?

The lock screen to function as usual.
While the manual fix on the user end is fairly easy, the [lockscreen-broken] screen would be daunting for inexperienced users. 

### Output of `rpm-ostree status`

```shell
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:f159ba0c67d6b84789879f560a508e95e03c26c4e7425b2aa7d942f1caf3eca1
                  Version: 42.20250706 (2025-07-07T22:50:08Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:c5b8a398f1109929da5ab2554f0c96290b09e76f2fe46c11200704edeb0897e1
                  Version: 42.20250621 (2025-06-21T20:49:01Z)
```

### Hardware

```
##############################################################################
### file 1 of 3: 63
##############################################################################
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:f159ba0c67d6b84789879f560a508e95e03c26c4e7425b2aa7d942f1caf3eca1
                  Version: 42.20250706 (2025-07-07T22:50:08Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:c5b8a398f1109929da5ab2554f0c96290b09e76f2fe46c11200704edeb0897e1
                  Version: 42.20250621 (2025-06-21T20:49:01Z)
##############################################################################
### file 2 of 3: 62
##############################################################################
=== fpaste 0.5.0.0 System Information ===
* OS Release (lsb_release -ds):
     "Bazzite 42 (FROM Fedora Kinoite)"
     
* CPU Model (grep 'model name' /proc/cpuinfo | awk -F: '{print $2}' | uniq -c |
     sed -re 's/^ +//' ):
     16  AMD Ryzen 7 7700X 8-Core Processor
     
* 64-bit Support (grep -q ' lm ' /proc/cpuinfo && echo Yes || echo No):
     Yes
     
* Hardware Virtualization Support (grep -Eq '(vmx|svm)' /proc/cpuinfo && echo Yes || echo No):
     Yes
     
* Kernel (uname -r):
     6.15.4-104.bazzite.fc42.x86_64
     
* Kernel cmdline (cat /proc/cmdline):
     BOOT_IMAGE=(hd2,gpt2)/ostree/default-c4186a2c3083f98dd316f66397e1959c6e007171c6991d8c3fa8e2cb1b71b026/vmlinuz-6.15.4-104.bazzite.fc42.x86_64 rhgb quiet root=UUID=d058b972-d119-4a63-94ec-f24a8c8a3f12 rootflags=subvol=root rw ostree=/ostree/boot.1/default/c4186a2c3083f98dd316f66397e1959c6e007171c6991d8c3fa8e2cb1b71b026/0 bluetooth.disable_ertm=1 preempt=full amdgpu.ppfeaturemask=0xfff7ffff split_lock_detect=off
     
* Desktop(s) Running (without results: "ps -eo comm= | grep -E '(gnome-session|startkde|startactive|xfce.?-session|fluxbox|blackbox|hackedbox|ratpoison|enlightenment|icewm-session|od-session|wmaker|wmx|openbox-lxde|openbox-gnome-session|openbox-kde-session|mwm|e16|fvwm|xmonad|sugar-session|mate-session|lxqt-session|cinnamon|lxdm-session|awesome|phosh|sway|Hyperland)' "):
     N/A

* Desktop(s) Installed (ls -m /usr/share/{xsessions,wayland-sessions}/ | sed 's/\.desktop//g' ):
     /usr/share/wayland-sessions/:
     plasma
     
     /usr/share/xsessions/:
     
* Session Type (env | grep 'XDG_SESSION_TYPE' | sed 's/.*=//' ):
     wayland
     
* SELinux Status (sestatus):
     SELinux status:                 enabled
     SELinuxfs mount:                /sys/fs/selinux
     SELinux root directory:         /etc/selinux
     Loaded policy name:             targeted
     Current mode:                   enforcing
     Mode from config file:          enforcing
     Policy MLS status:              enabled
     Policy deny_unknown status:     allowed
     Memory protection checking:     actual (secure)
     Max kernel policy version:      34
     
* SELinux Errors (selinuxenabled && journalctl --no-hostname --since yesterday |grep avc: | grep -Eo comm="[^ ]+" | sort |uniq -c |sort -rn):
          50 comm="iio-sensor-prox"
          43 comm="ostree"
          15 comm="bootupctl"
           5 comm="tuned-ppd"
           4 comm="logrotate"
     
* Memory usage (free -hm):
                    total        used        free      shared  buff/cache   available
     Mem:            15Gi       4.7Gi       6.9Gi       117Mi       4.8Gi        10Gi
     Swap:          4.0Gi          0B       4.0Gi
     
* ZRAM usage (zramctl --output-all):
     NAME       DISKSIZE DATA COMPR ALGORITHM STREAMS ZERO-PAGES TOTAL MEM-LIMIT MEM-USED MIGRATED MOUNTPOINT
     /dev/zram0       4G   4K   69B lz4                        0   20K        0B      20K       0B [SWAP]
     
* Load average (uptime):
      13:36:10 up 20 min,  2 users,  load average: 0.36, 0.46, 0.45
     
* Pressure Stall Information (grep -R . /proc/pressure/):
     /proc/pressure/io:some avg10=0.00 avg60=0.00 avg300=0.00 total=2672230
     /proc/pressure/io:full avg10=0.00 avg60=0.00 avg300=0.00 total=2389956
     /proc/pressure/cpu:some avg10=0.00 avg60=0.00 avg300=0.00 total=2695186
     /proc/pressure/cpu:full avg10=0.00 avg60=0.00 avg300=0.00 total=0
     /proc/pressure/irq:full avg10=0.00 avg60=0.00 avg300=0.00 total=3031602
     /proc/pressure/memory:some avg10=0.00 avg60=0.00 avg300=0.00 total=7
     /proc/pressure/memory:full avg10=0.00 avg60=0.00 avg300=0.00 total=7
     
* Top 5 CPU hogs (ps axuScnh | awk '$2!=7680' | sort -rnk3 | head -5):
         1000    7678 15.0  0.0 231928  3812 pts/3    S+   13:36   0:00 device-info
         1000    2357  8.8  0.0  24224 15292 ?        Ss   13:15   1:49 systemd
         1000    6440  5.7  3.5 11963004 564144 ?     Sl   13:27   0:28 firefox-bin
            0    7728  5.7  0.1 642120 29460 ?        Ssl  13:36   0:00 rpm-ostree
         1000    6681  5.4  2.0 2950576 322096 ?      Sl   13:27   0:27 Isolated Web Co
     
* Top 5 Memory hogs (ps axuScnh | sort -rnk4 | head -5):
         1000    2972  0.5  4.0 9578440 642756 ?      Ssl  13:15   0:07 plasmashell
         1000    6440  5.7  3.5 11963004 564144 ?     Sl   13:27   0:28 firefox-bin
         1000    3959  2.3  2.9 1466850120 471336 ?   Sl   13:15   0:29 vesktop.bin
         1000    6719  1.6  2.3 3124544 379716 ?      Sl   13:27   0:08 Isolated Web Co
         1000    6681  5.4  2.0 2950576 322096 ?      Sl   13:27   0:27 Isolated Web Co
     
* block devices (lsblk -o NAME,FSTYPE,SIZE,FSUSE%,MOUNTPOINT,UUID,MIN-IO,SCHED,DISC-GRAN,MODEL):
     NAME        FSTYPE   SIZE FSUSE% MOUNTPOINT                    UUID                                 MIN-IO SCHED DISC-GRAN MODEL
     sda                232.9G                                                                              512 kyber      512B Samsung SSD 870 EVO 250GB
     ├─sda1      vfat     100M                                      AEBA-7B96                               512 kyber      512B 
     ├─sda2                16M                                                                              512 kyber      512B 
     ├─sda3      ntfs   232.1G                                      64BCBC48BCBC1710                        512 kyber      512B 
     └─sda4      ntfs     650M                                      2C0289E90289B87A                        512 kyber      512B 
     sdb                931.5G                                                                             4096 bfq          4K WDC WD10EZEX-22MFCA0
     └─sdb1      btrfs  931.5G    44% /run/media/system/backup-hdd  228f1ee2-ecfd-4d3f-bf8e-3ea7f50fcfad   4096 bfq          4K 
     sdc                232.9G                                                                              512 kyber      512B Samsung SSD 870 EVO 250GB
     ├─sdc1      vfat     600M     2% /boot/efi                     6B03-F9A5                               512 kyber      512B 
     ├─sdc2      ext4       1G    35% /boot                         c3e43961-6e25-43de-a0be-d849aa2f3b77    512 kyber      512B 
     └─sdc3      btrfs  231.3G    36% /var/home                     d058b972-d119-4a63-94ec-f24a8c8a3f12    512 kyber      512B 
     zram0       swap       4G        [SWAP]                        47368abd-3d5c-400e-a72a-045ac83d253e   4096              4K 
     nvme0n1            931.5G                                                                              512 kyber      512B Samsung SSD 970 EVO Plus 1TB
     ├─nvme0n1p1 ntfs   350.1G                                      54FCDCFEFCDCDAF6                        512 kyber      512B 
     └─nvme0n1p2 btrfs  581.4G    90% /run/media/system/linux-games db8cb46b-23aa-4638-b65a-68c69a07ccb7    512 kyber      512B 
     
* PCI devices (lspci -nn):
     00:00.0 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Raphael/Granite Ridge Root Complex [1022:14d8]
     00:00.2 IOMMU [0806]: Advanced Micro Devices, Inc. [AMD] Raphael/Granite Ridge IOMMU [1022:14d9]
     00:01.0 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Raphael/Granite Ridge Dummy Host Bridge [1022:14da]
     00:01.1 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] Raphael/Granite Ridge GPP Bridge [1022:14db]
     00:01.2 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] Raphael/Granite Ridge GPP Bridge [1022:14db]
     00:02.0 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Raphael/Granite Ridge Dummy Host Bridge [1022:14da]
     00:02.1 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] Raphael/Granite Ridge GPP Bridge [1022:14db]
     00:03.0 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Raphael/Granite Ridge Dummy Host Bridge [1022:14da]
     00:04.0 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Raphael/Granite Ridge Dummy Host Bridge [1022:14da]
     00:08.0 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Raphael/Granite Ridge Dummy Host Bridge [1022:14da]
     00:08.1 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] Raphael/Granite Ridge Internal GPP Bridge to Bus [C:A] [1022:14dd]
     00:08.3 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] Raphael/Granite Ridge Internal GPP Bridge to Bus [C:A] [1022:14dd]
     00:14.0 SMBus [0c05]: Advanced Micro Devices, Inc. [AMD] FCH SMBus Controller [1022:790b] (rev 71)
     00:14.3 ISA bridge [0601]: Advanced Micro Devices, Inc. [AMD] FCH LPC Bridge [1022:790e] (rev 51)
     00:18.0 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Raphael/Granite Ridge Data Fabric; Function 0 [1022:14e0]
     00:18.1 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Raphael/Granite Ridge Data Fabric; Function 1 [1022:14e1]
     00:18.2 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Raphael/Granite Ridge Data Fabric; Function 2 [1022:14e2]
     00:18.3 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Raphael/Granite Ridge Data Fabric; Function 3 [1022:14e3]
     00:18.4 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Raphael/Granite Ridge Data Fabric; Function 4 [1022:14e4]
     00:18.5 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Raphael/Granite Ridge Data Fabric; Function 5 [1022:14e5]
     00:18.6 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Raphael/Granite Ridge Data Fabric; Function 6 [1022:14e6]
     00:18.7 Host bridge [0600]: Advanced Micro Devices, Inc. [AMD] Raphael/Granite Ridge Data Fabric; Function 7 [1022:14e7]
     01:00.0 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 10 XL Upstream Port of PCI Express Switch [1002:1478] (rev 24)
     02:00.0 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 10 XL Downstream Port of PCI Express Switch [1002:1479] (rev 24)
     03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 48 [RX 9070/9070 XT] [1002:7550] (rev c3)
     03:00.1 Audio device [0403]: Advanced Micro Devices, Inc. [AMD/ATI] Device [1002:ab40]
     04:00.0 Non-Volatile memory controller [0108]: Samsung Electronics Co Ltd NVMe SSD Controller SM981/PM981/PM983 [144d:a808]
     05:00.0 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] 600 Series Chipset PCIe Switch Upstream Port [1022:43f4] (rev 01)
     06:00.0 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] 600 Series Chipset PCIe Switch Downstream Port [1022:43f5] (rev 01)
     06:04.0 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] 600 Series Chipset PCIe Switch Downstream Port [1022:43f5] (rev 01)
     06:05.0 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] 600 Series Chipset PCIe Switch Downstream Port [1022:43f5] (rev 01)
     06:06.0 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] 600 Series Chipset PCIe Switch Downstream Port [1022:43f5] (rev 01)
     06:07.0 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] 600 Series Chipset PCIe Switch Downstream Port [1022:43f5] (rev 01)
     06:08.0 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] 600 Series Chipset PCIe Switch Downstream Port [1022:43f5] (rev 01)
     06:09.0 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] 600 Series Chipset PCIe Switch Downstream Port [1022:43f5] (rev 01)
     06:0a.0 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] 600 Series Chipset PCIe Switch Downstream Port [1022:43f5] (rev 01)
     06:0b.0 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] 600 Series Chipset PCIe Switch Downstream Port [1022:43f5] (rev 01)
     06:0c.0 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] 600 Series Chipset PCIe Switch Downstream Port [1022:43f5] (rev 01)
     06:0d.0 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] 600 Series Chipset PCIe Switch Downstream Port [1022:43f5] (rev 01)
     0a:00.0 SATA controller [0106]: ASMedia Technology Inc. ASM1064 Serial ATA Controller [1b21:1064] (rev 02)
     0e:00.0 Ethernet controller [0200]: Realtek Semiconductor Co., Ltd. RTL8125 2.5GbE Controller [10ec:8125] (rev 05)
     0f:00.0 Network controller [0280]: MEDIATEK Corp. MT7922 802.11ax PCI Express Wireless Network Adapter [14c3:0616]
     10:00.0 USB controller [0c03]: Advanced Micro Devices, Inc. [AMD] 600 Series Chipset USB 3.2 Controller [1022:43f7] (rev 01)
     11:00.0 SATA controller [0106]: Advanced Micro Devices, Inc. [AMD] 600 Series Chipset SATA Controller [1022:43f6] (rev 01)
     12:00.0 Non-Essential Instrumentation [1300]: Advanced Micro Devices, Inc. [AMD] Raphael/Granite Ridge PCIe Dummy Function [1022:14de] (rev c3)
     12:00.2 Encryption controller [1080]: Advanced Micro Devices, Inc. [AMD] Family 19h PSP/CCP [1022:1649]
     12:00.3 USB controller [0c03]: Advanced Micro Devices, Inc. [AMD] Raphael/Granite Ridge USB 3.1 xHCI [1022:15b6]
     12:00.4 USB controller [0c03]: Advanced Micro Devices, Inc. [AMD] Raphael/Granite Ridge USB 3.1 xHCI [1022:15b7]
     12:00.6 Audio device [0403]: Advanced Micro Devices, Inc. [AMD] Family 17h/19h/1ah HD Audio Controller [1022:15e3]
     13:00.0 USB controller [0c03]: Advanced Micro Devices, Inc. [AMD] Raphael/Granite Ridge USB 2.0 xHCI [1022:15b8]
     
* USB devices (lsusb):
     Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
     Bus 001 Device 002: ID 31b2:0011 KTMicro KT_USB_AUDIO
     Bus 001 Device 003: ID 046d:c539 Logitech, Inc. Lightspeed Receiver
     Bus 001 Device 004: ID 174c:2074 ASMedia Technology Inc. ASM1074 High-Speed hub
     Bus 001 Device 005: ID 1462:7d78 Micro Star International MYSTIC LIGHT 
     Bus 001 Device 006: ID 0909:001c Audio-Technica Corp. AT2020USB+
     Bus 001 Device 007: ID 0e8d:0616 MediaTek Inc. Wireless_Device
     Bus 001 Device 008: ID 0424:2514 Microchip Technology, Inc. (formerly SMSC) USB 2.0 Hub
     Bus 001 Device 009: ID 0bda:5411 Realtek Semiconductor Corp. RTS5411 Hub
     Bus 001 Device 010: ID 046d:085b Logitech, Inc. Logitech Webcam C925e
     Bus 001 Device 011: ID 054c:0ce6 Sony Corp. DualSense wireless controller (PS5)
     Bus 001 Device 012: ID 0bda:1100 Realtek Semiconductor Corp. HID Device
     Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
     Bus 002 Device 002: ID 174c:3074 ASMedia Technology Inc. ASM1074 SuperSpeed hub
     Bus 002 Device 003: ID 0bda:0411 Realtek Semiconductor Corp. Hub
     Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
     Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
     Bus 005 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
     Bus 005 Device 002: ID 05ac:024f Apple, Inc. Aluminium Keyboard (ANSI)
     Bus 006 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
     Bus 007 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
     Bus 008 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
     
* PCI Video Card (lspci |  grep -i -E 'vga' | cut -b1-7 | xargs -i lspci -vnnks {} | grep -v "<access denied>"):
     03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 48 [RX 9070/9070 XT] [1002:7550] (rev c3) (prog-if 00 [VGA controller])
     	Subsystem: XFX Limited Device [1eae:8710]
     	Flags: bus master, fast devsel, latency 0, IRQ 106, IOMMU group 15
     	Memory at f800000000 (64-bit, prefetchable) [size=16G]
     	Memory at fc00000000 (64-bit, prefetchable) [size=256M]
     	I/O ports at f000 [size=256]
     	Memory at f6c00000 (32-bit, non-prefetchable) [size=512K]
     	Expansion ROM at f6c80000 [disabled] [size=128K]
     	Kernel driver in use: amdgpu
     	Kernel modules: amdgpu
     
     
* GL Support (glxinfo -B | grep -E "OpenGL version|OpenGL renderer"):
     OpenGL renderer string: AMD Radeon RX 9070 (radeonsi, gfx1201, LLVM 20.1.7, DRM 3.63, 6.15.4-104.bazzite.fc42.x86_64)
     OpenGL version string: 4.6 (Compatibility Profile) Mesa 25.1.5
     
* DRM Information (journalctl -k -b --no-hostname | grep -o 'kernel:.*drm.*$' | cut -d ' ' -f 2- ):
     ACPI: bus type drm_connector registered
     [drm] amdgpu kernel modesetting enabled.
     [drm] initializing kernel modesetting (IP DISCOVERY 0x1002:0x7550 0x1EAE:0x8710 0xC3).
     [drm] register mmio base: 0xF6C00000
     [drm] register mmio size: 524288
     [drm] vm size is 262144 GB, 4 levels, block size is 9-bit, fragment size is 9-bit
     [drm] Detected VRAM RAM=16304M, BAR=16384M
     [drm] RAM width 256bits GDDR6
     [drm] amdgpu: 16304M of VRAM memory ready
     [drm] amdgpu: 7788M of GTT memory ready.
     [drm] GART: num cpu pages 131072, num gpu pages 131072
     [drm] Loading DMUB firmware via PSP: version=0x00011100
     [drm] Display Core v3.2.325 initialized on DCN 4.0.1
     [drm] DP-HDMI FRL PCON supported
     [drm] DMUB hardware initialized: version=0x00011100
     [drm] ring gfx_32768.1.1 was added
     [drm] ring compute_32768.2.2 was added
     [drm] ring sdma_32768.3.3 was added
     [drm] ring gfx_32768.1.1 ib test pass
     [drm] ring compute_32768.2.2 ib test pass
     [drm] ring sdma_32768.3.3 ib test pass
     amdgpu 0000:03:00.0: [drm] Registered 4 planes with drm panic
     [drm] Initialized amdgpu 3.63.0 for 0000:03:00.0 on minor 0
     fbcon: amdgpudrmfb (fb0) is primary device
     amdgpu 0000:03:00.0: [drm] fb0: amdgpudrmfb frame buffer device
     [drm] pre_validate_dsc:1627 MST_DSC dsc precompute is not needed
     Modules linked in: wl(POE+) zenergy(OE) amd_atl intel_rapl_msr mt7921e intel_rapl_common mt7921_common snd_hda_codec_realtek snd_hda_codec_generic mt792x_lib snd_hda_scodec_component edac_mce_amd spd5118 snd_hda_codec_hdmi mt76_connac_lib mt76 kvm_amd snd_hda_intel snd_intel_dspcfg snd_usb_audio(+) mac80211 snd_intel_sdw_acpi kvm snd_hda_codec snd_usbmidi_lib snd_ump snd_hda_core btusb uvcvideo btrtl snd_rawmidi snd_hwdep btintel libarc4 uvc snd_seq videobuf2_vmalloc i2c_piix4 btbcm videobuf2_memops rapl wmi_bmof pcspkr snd_seq_device btmtk videobuf2_v4l2 i2c_smbus k10temp snd_pcm cfg80211 videobuf2_common bluetooth snd_timer r8169 videodev snd realtek joydev rfkill soundcore apple_mfi_fastcharge mc gpio_amdpt gpio_generic tcp_bbr vhba(OE) loop nfnetlink lz4 zram lz4hc_compress lz4_compress overlay erofs netfs hid_logitech_hidpp hid_playstation uhid pkcs8_key_parser led_class_multicolor ntsync ff_memless amdgpu hid_logitech_dj amdxcp gpu_sched drm_panel_backlight_quirks drm_buddy drm_ttm_helper ttm
      drm_exec i2c_algo_bit drm_suballoc_helper nvme polyval_clmulni polyval_generic drm_display_helper ghash_clmulni_intel nvme_core sha512_ssse3 sha256_ssse3 sha1_ssse3 hid_apple cec sp5100_tco nvme_keyring nvme_auth video wmi vfio_pci vfio_pci_core irqbypass vfio_iommu_type1 vfio iommufd nct6687(OE) kvmfr(OE) gcadapter_oc(OE) fuse i2c_dev
     
* Xorg modules (grep LoadModule /var/log/Xorg.0.log ~/.local/share/xorg/Xorg.0.log | cut -d \" -f 2 | xargs):
     
     
* Xorg errors (without results: "grep '^\[.*(EE)' /var/log/Xorg.0.log ~/.local/share/xorg/Xorg.0.log | cut -d ':' -f 2- "):
     N/A

* PCI Audio devices (lspci |  grep -i -E 'audio' | cut -b1-7 | xargs -i lspci -vnnks {} | grep -v "<access denied>"):
     03:00.1 Audio device [0403]: Advanced Micro Devices, Inc. [AMD/ATI] Device [1002:ab40]
     	Subsystem: Advanced Micro Devices, Inc. [AMD/ATI] Device [1002:ab40]
     	Flags: bus master, fast devsel, latency 0, IRQ 109, IOMMU group 16
     	Memory at f6ca0000 (32-bit, non-prefetchable) [size=16K]
     	Kernel driver in use: snd_hda_intel
     	Kernel modules: snd_hda_intel
     
     12:00.6 Audio device [0403]: Advanced Micro Devices, Inc. [AMD] Family 17h/19h/1ah HD Audio Controller [1022:15e3]
     	DeviceName: Realtek ALC1220
     	Subsystem: Micro-Star International Co., Ltd. [MSI] Device [1462:9d78]
     	Flags: bus master, fast devsel, latency 0, IRQ 110, IOMMU group 34
     	Memory at f6b00000 (32-bit, non-prefetchable) [size=32K]
     	Kernel driver in use: snd_hda_intel
     	Kernel modules: snd_hda_intel
     
     
* Audio devices (cat /proc/asound/cards):
      0 [KTUSBAUDIO     ]: USB-Audio - KT_USB_AUDIO
                           KTMicro KT_USB_AUDIO at usb-0000:10:00.0-1, full speed
      1 [Generic        ]: HDA-Intel - HD-Audio Generic
                           HD-Audio Generic at 0xf6ca0000 irq 109
      2 [Generic_1      ]: HDA-Intel - HD-Audio Generic
                           HD-Audio Generic at 0xf6b00000 irq 110
      3 [AT2020USB      ]: USB-Audio - AT2020USB+
                           audio-technica AT2020USB+ at usb-0000:10:00.0-5.1, full speed
      4 [Controller     ]: USB-Audio - DualSense Wireless Controller
                           Sony Interactive Entertainment DualSense Wireless Controller at usb-0000:10:00.
      5 [C925e          ]: USB-Audio - Logitech Webcam C925e
                           Logitech Webcam C925e at usb-0000:10:00.0-5.2.1, high speed
     
* User audio services (systemctl --user --no-pager status wireplumber pipewire* | sed "s/$(hostname)/ahost/"):
     ● wireplumber.service - Multimedia Service Session Manager
          Loaded: loaded (/usr/lib/systemd/user/wireplumber.service; enabled; preset: enabled)
         Drop-In: /usr/lib/systemd/user/service.d
                  └─10-timeout-abort.conf
          Active: active (running) since Tue 2025-07-08 13:15:39 AEST; 20min ago
      Invocation: 3bdddf5053e94bbdbd5a16dde06e0213
        Main PID: 2741 (wireplumber)
           Tasks: 6 (limit: 18367)
          Memory: 7.7M (peak: 9M)
             CPU: 569ms
          CGroup: /user.slice/user-1000.slice/user@1000.service/session.slice/wireplumber.service
                  └─2741 /usr/bin/wireplumber
     
     Jul 08 13:15:52 ahost wireplumber[2741]: spa.alsa: The decibel volume range for element 'PCM' (-4000 dB - -500 dB) has negative maximum. Disabling the decibel range.
     Jul 08 13:15:52 ahost wireplumber[2741]: spa.alsa: The decibel volume range for element 'PCM' (-4000 dB - -500 dB) has negative maximum. Disabling the decibel range.
     Jul 08 13:15:52 ahost wireplumber[2741]: spa.bluez5.midi: org.bluez.GattManager1.RegisterApplication() failed: GDBus.Error:org.bluez.Error.AlreadyExists: Already Exists
     Jul 08 13:15:58 ahost wireplumber[2741]: spa.alsa: The decibel volume range for element 'PCM' (-4000 dB - -500 dB) has negative maximum. Disabling the decibel range.
     Jul 08 13:15:58 ahost wireplumber[2741]: spa.alsa: The decibel volume range for element 'PCM' (-4000 dB - -500 dB) has negative maximum. Disabling the decibel range.
     Jul 08 13:15:58 ahost wireplumber[2741]: spa.alsa: The decibel volume range for element 'PCM' (-4000 dB - -500 dB) has negative maximum. Disabling the decibel range.
     Jul 08 13:15:58 ahost wireplumber[2741]: spa.alsa: The decibel volume range for element 'PCM' (-4000 dB - -500 dB) has negative maximum. Disabling the decibel range.
     Jul 08 13:15:58 ahost wireplumber[2741]: spa.alsa: The decibel volume range for element 'PCM' (-4000 dB - -500 dB) has negative maximum. Disabling the decibel range.
     Jul 08 13:15:58 ahost wireplumber[2741]: spa.bluez5.midi: org.bluez.GattManager1.RegisterApplication() failed: GDBus.Error:org.bluez.Error.AlreadyExists: Already Exists
     Jul 08 13:27:46 ahost wireplumber[2741]: wp-event-dispatcher: <WpAsyncEventHook:0x564e8be9ddb0> failed: <WpSiStandardLink:0x564e8be60210> link failed: 1 of 1 PipeWire links failed to activate
     
     ● pipewire.service - PipeWire Multimedia Service
          Loaded: loaded (/usr/lib/systemd/user/pipewire.service; disabled; preset: disabled)
         Drop-In: /usr/lib/systemd/user/pipewire.service.d
                  └─00-uresourced.conf
                  /usr/lib/systemd/user/service.d
                  └─10-timeout-abort.conf
          Active: active (running) since Tue 2025-07-08 13:15:39 AEST; 20min ago
      Invocation: 358eaa2da7d14762ac604769af1f4cd5
     TriggeredBy: ● pipewire.socket
        Main PID: 2738 (pipewire)
           Tasks: 3 (limit: 18367)
          Memory: 9.3M (peak: 11.5M)
             CPU: 2.169s
          CGroup: /user.slice/user-1000.slice/user@1000.service/session.slice/pipewire.service
                  └─2738 /usr/bin/pipewire
     
     Jul 08 13:15:39 ahost systemd[2357]: Started pipewire.service - PipeWire Multimedia Service.
     
     ● pipewire.socket - PipeWire Multimedia System Sockets
          Loaded: loaded (/usr/lib/systemd/user/pipewire.socket; enabled; preset: enabled)
          Active: active (running) since Tue 2025-07-08 13:15:32 AEST; 20min ago
      Invocation: f76b5418bf0242b28e8ce7b91490a5df
        Triggers: ● pipewire.service
          Listen: /run/user/1000/pipewire-0 (Stream)
                  /run/user/1000/pipewire-0-manager (Stream)
          CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/pipewire.socket
     
     Jul 08 13:15:32 ahost systemd[2357]: Listening on pipewire.socket - PipeWire Multimedia System Sockets.
     
     ● pipewire-pulse.socket - PipeWire PulseAudio
          Loaded: loaded (/usr/lib/systemd/user/pipewire-pulse.socket; enabled; preset: enabled)
          Active: active (running) since Tue 2025-07-08 13:15:32 AEST; 20min ago
      Invocation: 718786a1d11c4a43965c7e95471d3d03
        Triggers: ● pipewire-pulse.service
          Listen: /run/user/1000/pulse/native (Stream)
          CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/pipewire-pulse.socket
     
     Jul 08 13:15:32 ahost systemd[2357]: Listening on pipewire-pulse.socket - PipeWire PulseAudio.
     
     ● pipewire-pulse.service - PipeWire PulseAudio
          Loaded: loaded (/usr/lib/systemd/user/pipewire-pulse.service; disabled; preset: disabled)
         Drop-In: /usr/lib/systemd/user/service.d
                  └─10-timeout-abort.conf
          Active: active (running) since Tue 2025-07-08 13:15:39 AEST; 20min ago
      Invocation: 6784a4596add4f35901433d062c3f26e
     TriggeredBy: ● pipewire-pulse.socket
        Main PID: 2743 (pipewire-pulse)
           Tasks: 3 (limit: 18367)
          Memory: 11.8M (peak: 17.9M)
             CPU: 245ms
          CGroup: /user.slice/user-1000.slice/user@1000.service/session.slice/pipewire-pulse.service
                  └─2743 /usr/bin/pipewire-pulse
     
     Jul 08 13:15:39 ahost systemd[2357]: Started pipewire-pulse.service - PipeWire PulseAudio.
     
* PCI Network devices (lspci |  grep -i -E 'net' | cut -b1-7 | xargs -i lspci -vnnks {} | grep -v "<access denied>"):
     0e:00.0 Ethernet controller [0200]: Realtek Semiconductor Co., Ltd. RTL8125 2.5GbE Controller [10ec:8125] (rev 05)
     	Subsystem: Micro-Star International Co., Ltd. [MSI] Device [1462:7d78]
     	Flags: bus master, fast devsel, latency 0, IRQ 41, IOMMU group 26
     	I/O ports at e000 [size=256]
     	Memory at f6600000 (64-bit, non-prefetchable) [size=64K]
     	Memory at f6610000 (64-bit, non-prefetchable) [size=16K]
     	Kernel driver in use: r8169
     	Kernel modules: r8169
     
     0f:00.0 Network controller [0280]: MEDIATEK Corp. MT7922 802.11ax PCI Express Wireless Network Adapter [14c3:0616]
     	Subsystem: MEDIATEK Corp. MT7922 802.11ax PCI Express Wireless Network Adapter [14c3:0616]
     	Flags: bus master, fast devsel, latency 0, IRQ 111, IOMMU group 27
     	Memory at fc10100000 (64-bit, prefetchable) [size=1M]
     	Memory at f6500000 (64-bit, non-prefetchable) [size=32K]
     	Kernel driver in use: mt7921e
     	Kernel modules: mt7921e, wl
     
     
* Network status (ip -br addr | awk '{print $1" " $2}' | column -t):
     lo       UNKNOWN
     enp14s0  DOWN
     wlp15s0  UP
     
* Kernel buffer tail (journalctl --no-hostname -k --lines 50):
     Jul 08 13:15:24 kernel: Bluetooth: BNEP filters: protocol multicast
     Jul 08 13:15:24 kernel: Bluetooth: BNEP socket layer initialized
     Jul 08 13:15:24 kernel: Bluetooth: MGMT ver 1.23
     Jul 08 13:15:24 kernel: mt7921e 0000:0f:00.0 wlp15s0: renamed from wlan0
     Jul 08 13:15:24 kernel: RPC: Registered named UNIX socket transport module.
     Jul 08 13:15:24 kernel: RPC: Registered udp transport module.
     Jul 08 13:15:24 kernel: RPC: Registered tcp transport module.
     Jul 08 13:15:24 kernel: RPC: Registered tcp-with-tls transport module.
     Jul 08 13:15:24 kernel: RPC: Registered tcp NFSv4.1 backchannel transport module.
     Jul 08 13:15:24 kernel: nvme nvme0: using unchecked data buffer
     Jul 08 13:15:24 kernel: BTRFS: device label linux-games devid 1 transid 31699 /dev/nvme0n1p2 (259:2) scanned by mount (1553)
     Jul 08 13:15:24 kernel: BTRFS info (device nvme0n1p2): first mount of filesystem db8cb46b-23aa-4638-b65a-68c69a07ccb7
     Jul 08 13:15:24 kernel: BTRFS info (device nvme0n1p2): using crc32c (crc32c-x86_64) checksum algorithm
     Jul 08 13:15:24 kernel: BTRFS info (device nvme0n1p2): using free-space-tree
     Jul 08 13:15:25 kernel: NET: Registered PF_QIPCRTR protocol family
     Jul 08 13:15:25 kernel: Realtek Internal NBASE-T PHY r8169-0-e00:00: attached PHY driver (mii_bus:phy_addr=r8169-0-e00:00, irq=MAC)
     Jul 08 13:15:25 kernel: r8169 0000:0e:00.0 enp14s0: Link is Down
     Jul 08 13:15:27 kernel: ahci 0000:11:00.0: port does not support device sleep
     Jul 08 13:15:27 kernel: ahci 0000:0a:00.0: port does not support device sleep
     Jul 08 13:15:29 kernel: wlp15s0: authenticate with 24:7f:20:85:a8:7b (local address=3a:d4:cf:24:69:c5)
     Jul 08 13:15:29 kernel: wlp15s0: send auth to 24:7f:20:85:a8:7b (try 1/3)
     Jul 08 13:15:29 kernel: wlp15s0: authenticated
     Jul 08 13:15:29 kernel: wlp15s0: associate with 24:7f:20:85:a8:7b (try 1/3)
     Jul 08 13:15:29 kernel: wlp15s0: RX AssocResp from 24:7f:20:85:a8:7b (capab=0x11 status=0 aid=2)
     Jul 08 13:15:29 kernel: wlp15s0: associated
     Jul 08 13:15:29 kernel: wlp15s0: Limiting TX power to 23 (23 - 0) dBm as advertised by 24:7f:20:85:a8:7b
     Jul 08 13:15:34 kernel: usb 1-5.2.1: reset high-speed USB device number 10 using xhci_hcd
     Jul 08 13:15:34 kernel: Bluetooth: RFCOMM TTY layer initialized
     Jul 08 13:15:34 kernel: Bluetooth: RFCOMM socket layer initialized
     Jul 08 13:15:34 kernel: Bluetooth: RFCOMM ver 1.11
     Jul 08 13:15:42 kernel: uinput: UI_SET_PHYS is deprecated. Use UI_SET_PHYS_STR
     Jul 08 13:15:42 kernel: input: input-remapper keyboard as /devices/virtual/input/input36
     Jul 08 13:15:42 kernel: input: input-remapper Sony Interactive Entertainment DualSense Wireless Contr forwarde as /devices/virtual/input/input37
     Jul 08 13:15:43 kernel: show_signal_msg: 101 callbacks suppressed
     Jul 08 13:15:43 kernel: kscreenlocker_g[3719]: segfault at 52 ip 00007f619702219d sp 00007ffe7b186d60 error 4 in d8a22d47e187298e95f6673634de3a4d863dce8205e994c89020d8e82c05bb.file[319d,7f619701f000+7000] likely on CPU 12 (core 4, socket 0)
     Jul 08 13:15:43 kernel: Code: be 02 00 00 00 4c 89 e7 31 c0 e8 2e da ff ff 49 83 7e 10 00 0f 85 8b 00 00 00 49 8b 87 b0 01 00 00 48 85 c0 74 32 4c 8b 63 18 <4c> 8b 70 18 44 8b 6d a8 4c 89 e7 e8 53 d9 ff ff 48 83 ec 08 31 d2
     Jul 08 13:15:44 kernel: kscreenlocker_g[3897]: segfault at 60 ip 00007f6a2587819d sp 00007fff56080ec0 error 4 in d8a22d47e187298e95f6673634de3a4d863dce8205e994c89020d8e82c05bb.file[319d,7f6a25875000+7000] likely on CPU 3 (core 3, socket 0)
     Jul 08 13:15:44 kernel: Code: be 02 00 00 00 4c 89 e7 31 c0 e8 2e da ff ff 49 83 7e 10 00 0f 85 8b 00 00 00 49 8b 87 b0 01 00 00 48 85 c0 74 32 4c 8b 63 18 <4c> 8b 70 18 44 8b 6d a8 4c 89 e7 e8 53 d9 ff ff 48 83 ec 08 31 d2
     Jul 08 13:15:44 kernel: kscreenlocker_g[3976]: segfault at 6f ip 00007f5f893e119d sp 00007fff749934a0 error 4 in d8a22d47e187298e95f6673634de3a4d863dce8205e994c89020d8e82c05bb.file[319d,7f5f893de000+7000] likely on CPU 10 (core 2, socket 0)
     Jul 08 13:15:44 kernel: Code: be 02 00 00 00 4c 89 e7 31 c0 e8 2e da ff ff 49 83 7e 10 00 0f 85 8b 00 00 00 49 8b 87 b0 01 00 00 48 85 c0 74 32 4c 8b 63 18 <4c> 8b 70 18 44 8b 6d a8 4c 89 e7 e8 53 d9 ff ff 48 83 ec 08 31 d2
     Jul 08 13:15:44 kernel: kscreenlocker_g[4040]: segfault at 7d ip 00007f361114c19d sp 00007ffffdb8d360 error 4 in d8a22d47e187298e95f6673634de3a4d863dce8205e994c89020d8e82c05bb.file[319d,7f3611149000+7000] likely on CPU 13 (core 5, socket 0)
     Jul 08 13:15:44 kernel: Code: be 02 00 00 00 4c 89 e7 31 c0 e8 2e da ff ff 49 83 7e 10 00 0f 85 8b 00 00 00 49 8b 87 b0 01 00 00 48 85 c0 74 32 4c 8b 63 18 <4c> 8b 70 18 44 8b 6d a8 4c 89 e7 e8 53 d9 ff ff 48 83 ec 08 31 d2
     Jul 08 13:15:47 kernel: fbcon: Taking over console
     Jul 08 13:15:47 kernel: Console: switching to colour frame buffer device 240x75
     Jul 08 13:15:59 kernel: logitech-hidpp-device 0003:046D:407F.000B: HID++ 4.2 device connected.
     Jul 08 13:16:39 kernel: kscreenlocker_g[4501]: segfault at 133 ip 00007f81a2e8819d sp 00007ffc2102dbe0 error 4 likely on CPU 0 (core 0, socket 0)
     Jul 08 13:16:39 kernel: Code: be 02 00 00 00 4c 89 e7 31 c0 e8 2e da ff ff 49 83 7e 10 00 0f 85 8b 00 00 00 49 8b 87 b0 01 00 00 48 85 c0 74 32 4c 8b 63 18 <4c> 8b 70 18 44 8b 6d a8 4c 89 e7 e8 53 d9 ff ff 48 83 ec 08 31 d2
     Jul 08 13:16:46 kernel: kscreenlocker_g[4632]: segfault at 191 ip 00007fdddc93c19d sp 00007ffcedf7fcf0 error 4 in d8a22d47e187298e95f6673634de3a4d863dce8205e994c89020d8e82c05bb.file[319d,7fdddc939000+7000] likely on CPU 1 (core 1, socket 0)
     Jul 08 13:16:46 kernel: Code: be 02 00 00 00 4c 89 e7 31 c0 e8 2e da ff ff 49 83 7e 10 00 0f 85 8b 00 00 00 49 8b 87 b0 01 00 00 48 85 c0 74 32 4c 8b 63 18 <4c> 8b 70 18 44 8b 6d a8 4c 89 e7 e8 53 d9 ff ff 48 83 ec 08 31 d2
     Jul 08 13:18:40 kernel: evm: overlay not supported
     
* Last few reboots (last -x -n10 reboot runlevel):
     runlevel (to lvl 5)   6.15.4-104.bazzi Tue Jul  8 13:15   still running
     reboot   system boot  6.15.4-104.bazzi Tue Jul  8 13:15   still running
     runlevel (to lvl 5)   6.15.4-104.bazzi Tue Jul  8 12:54 - 13:14  (00:19)
     reboot   system boot  6.15.4-104.bazzi Tue Jul  8 12:54 - 13:14  (00:20)
     runlevel (to lvl 5)   6.14.6-109.bazzi Tue Jul  8 12:27 - 12:53  (00:26)
     reboot   system boot  6.14.6-109.bazzi Tue Jul  8 12:27 - 12:53  (00:26)
     runlevel (to lvl 5)   6.14.6-109.bazzi Mon Jul  7 16:58 - 18:53  (01:54)
     reboot   system boot  6.14.6-109.bazzi Mon Jul  7 16:58 - 18:53  (01:54)
     runlevel (to lvl 5)   6.14.6-109.bazzi Sun Jul  6 16:37 - 18:40  (02:03)
     reboot   system boot  6.14.6-109.bazzi Sun Jul  6 16:37 - 18:40  (02:03)
     
     wtmp begins Tue Apr 15 06:26:29 2025
     
* DNF Repositories (dnf repolist):
     ERROR: Fedora Atomic images utilize rpm-ostree instead (and is discouraged to use).
     Please, ]8;;https://docs.bazzite.gg/Installing_and_Managing_Software/read our documentation]8;;
     ]8;;https://docs.bazzite.gg/Installing_and_Managing_Software/https://docs.bazzite.gg/Installing_and_Managing_Software/]8;;
     
     
* DNF Extras (dnf -C list extras):
     ERROR: Fedora Atomic images utilize rpm-ostree instead (and is discouraged to use).
     Please, ]8;;https://docs.bazzite.gg/Installing_and_Managing_Software/read our documentation]8;;
     ]8;;https://docs.bazzite.gg/Installing_and_Managing_Software/https://docs.bazzite.gg/Installing_and_Managing_Software/]8;;
     
     
* Last 20 packages installed (rpm -qa --nodigest --nosignature --last | head -20):
     ublue-os-media-automount-udev-0.16-1.fc42.noarch Tue 08 Jul 2025 08:43:33 AEST
     ublue-brew-0.1.7-1.fc42.x86_64                Tue 08 Jul 2025 08:43:08 AEST
     kf6-kio-widgets-libs-6.15.0-1.fc42.switcheroo.x86_64 Tue 08 Jul 2025 08:42:39 AEST
     kf6-kio-widgets-6.15.0-1.fc42.switcheroo.x86_64 Tue 08 Jul 2025 08:42:39 AEST
     kf6-kio-gui-6.15.0-1.fc42.switcheroo.x86_64   Tue 08 Jul 2025 08:42:39 AEST
     kf6-kio-file-widgets-6.15.0-1.fc42.switcheroo.x86_64 Tue 08 Jul 2025 08:42:39 AEST
     kf6-kio-doc-6.15.0-1.fc42.switcheroo.noarch   Tue 08 Jul 2025 08:42:39 AEST
     kf6-kio-core-libs-6.15.0-1.fc42.switcheroo.x86_64 Tue 08 Jul 2025 08:42:39 AEST
     kf6-kio-core-6.15.0-1.fc42.switcheroo.x86_64  Tue 08 Jul 2025 08:42:39 AEST
     kf6-kio-6.15.0-1.fc42.switcheroo.x86_64       Tue 08 Jul 2025 08:42:39 AEST
     steamdeck-kde-presets-desktop-0.0.git.5186.92a5a22a-1.fc42.noarch Tue 08 Jul 2025 08:42:36 AEST
     rom-properties-kf6-2.3-1.fc42.x86_64          Tue 08 Jul 2025 08:42:36 AEST
     ptyxis-48.4-2.fc42.x86_64                     Tue 08 Jul 2025 08:42:36 AEST
     krunner-bazaar-1.0.0-1.fc42.x86_64            Tue 08 Jul 2025 08:42:36 AEST
     wallpaper-engine-kde-plugin-100.ed58dd8b-1.bazzite.x86_64 Tue 08 Jul 2025 08:42:35 AEST
     vte291-gtk4-0.80.2-2.fc42.x86_64              Tue 08 Jul 2025 08:42:35 AEST
     vapoursynth-libs-70-7.fc42.x86_64             Tue 08 Jul 2025 08:42:35 AEST
     unixODBC-2.3.12-6.fc42.x86_64                 Tue 08 Jul 2025 08:42:35 AEST
     uchardet-0.0.8-7.fc42.x86_64                  Tue 08 Jul 2025 08:42:35 AEST
     qt6-qtwebsockets-devel-6.9.1-1.fc42.x86_64    Tue 08 Jul 2025 08:42:35 AEST
     
* EFI boot manager output (efibootmgr -v):
     BootCurrent: 0002
     Timeout: 1 seconds
     BootOrder: 0002,0000
     Boot0000* Windows Boot Manager	HD(1,GPT,ecc7d92c-2dc0-453c-82d7-0ea4cdd77a30,0x800,0x32000)/\EFI\Microsoft\Boot\bootmgfw.efi57494e444f5753000100000088000000780000004200430044004f0042004a004500430054003d007b00390064006500610038003600320063002d0035006300640064002d0034006500370030002d0061006300630031002d006600330032006200330034003400640034003700390035007d00000000000100000010000000040000007fff0400
           dp: 04 01 2a 00 01 00 00 00 00 08 00 00 00 00 00 00 00 20 03 00 00 00 00 00 2c d9 c7 ec c0 2d 3c 45 82 d7 0e a4 cd d7 7a 30 02 02 / 04 04 46 00 5c 00 45 00 46 00 49 00 5c 00 4d 00 69 00 63 00 72 00 6f 00 73 00 6f 00 66 00 74 00 5c 00 42 00 6f 00 6f 00 74 00 5c 00 62 00 6f 00 6f 00 74 00 6d 00 67 00 66 00 77 00 2e 00 65 00 66 00 69 00 00 00 / 7f ff 04 00
         data: 57 49 4e 44 4f 57 53 00 01 00 00 00 88 00 00 00 78 00 00 00 42 00 43 00 44 00 4f 00 42 00 4a 00 45 00 43 00 54 00 3d 00 7b 00 39 00 64 00 65 00 61 00 38 00 36 00 32 00 63 00 2d 00 35 00 63 00 64 00 64 00 2d 00 34 00 65 00 37 00 30 00 2d 00 61 00 63 00 63 00 31 00 2d 00 66 00 33 00 32 00 62 00 33 00 34 00 34 00 64 00 34 00 37 00 39 00 35 00 7d 00 00 00 00 00 01 00 00 00 10 00 00 00 04 00 00 00 7f ff 04 00
     Boot0002* Fedora
     	HD(1,GPT,7f07f42e-b5ab-45e7-897d-697b601d4562,0x800,0x12c000)/\EFI\fedora\shimx64.efi
           dp: 04 01 2a 00 01 00 00 00 00 08 00 00 00 00 00 00 00 c0 12 00 00 00 00 00 2e f4 07 7f ab b5 e7 45 89 7d 69 7b 60 1d 45 62 02 02 / 04 04 34 00 5c 00 45 00 46 00 49 00 5c 00 66 00 65 00 64 00 6f 00 72 00 61 00 5c 00 73 00 68 00 69 00 6d 00 78 00 36 00 34 00 2e 00 65 00 66 00 69 00 00 00 / 7f ff 04 00
     

##############################################################################
### file 3 of 3: 61
##############################################################################
com.dec05eba.gpu_screen_recorder	5.7.3	system,current
com.discordapp.Discord	0.0.101	system,current
com.github.Bleuzen.FFaudioConverter	0.32.0	system,current
com.github.Matoking.protontricks	1.12.1	system,current
com.github.neithern.g4music	4.5	system,current
com.github.tchx84.Flatseal	2.3.1	system,current
com.jeffser.Alpaca	7.0.1	system,current
com.jeffser.Alpaca.Plugins.AMD	0.9.3	system,runtime
com.jeffser.Alpaca.Plugins.Ollama	0.9.3	system,runtime
com.obsproject.Studio	31.0.4	system,current
com.obsproject.Studio.Plugin.AdvancedMasks	1.1.0	system,runtime
com.obsproject.Studio.Plugin.GStreamerVaapi	0.4.2	system,runtime
com.obsproject.Studio.Plugin.Gstreamer	0.4.1	system,runtime
com.obsproject.Studio.Plugin.OBSVkCapture	1.5.2	system,runtime
com.ranfdev.DistroShelf	1.0.12	system,current
com.spotify.Client	1.2.63.394.g126b0d89	system,current
de.haeckerfelix.Shortwave	5.0.0	system,current
de.leopoldluley.Clapgrep	25.05+1	system,current
dev.vencord.Vesktop	1.5.7	system,current
io.github.fastrizwaan.WineZGUI	0.99.15	system,current
io.github.flattool.Warehouse	2.1.0	system,current
io.github.idevecore.Valuta	1.4.0	system,current
io.github.ilya_zlobintsev.LACT	0.8.0	system,current
io.github.vikdevelop.SaveDesktop	3.6	system,current
io.gitlab.librewolf-community	140.0.2-1	system,current
io.missioncenter.MissionCenter	1.0.2	system,current
it.mijorus.gearlever	3.3.4	system,current
net.davidotek.pupgui2	2.12.0	system,current
org.bunkus.mkvtoolnix-gui	93.0	system,current
org.freedesktop.LinuxAudio.Plugins.TAP	1.0.1	system,runtime
org.freedesktop.LinuxAudio.Plugins.swh	0.4.17	system,runtime
org.freedesktop.Platform	freedesktop-sdk-24.08.22	system,runtime
org.freedesktop.Platform.Compat.i386		system,runtime
org.freedesktop.Platform.GL.default	25.0.7	system,runtime
org.freedesktop.Platform.GL.default	25.0.7	system,runtime
org.freedesktop.Platform.GL.default	25.1.3	system,runtime
org.freedesktop.Platform.GL.default	25.1.3	system,runtime
org.freedesktop.Platform.GL32.default	25.1.3	system,runtime
org.freedesktop.Platform.GL32.default	25.1.3	system,runtime
org.freedesktop.Platform.VulkanLayer.MangoHud	0.8.1	system,runtime
org.freedesktop.Platform.VulkanLayer.OBSVkCapture	1.5.1	system,runtime
org.freedesktop.Platform.VulkanLayer.vkBasalt	0.3.2.10	system,runtime
org.freedesktop.Platform.ffmpeg-full		system,runtime
org.freedesktop.Platform.ffmpeg_full.i386		system,runtime
org.freedesktop.Platform.openh264	2.1.0	system,runtime
org.freedesktop.Platform.openh264	2.5.1	system,runtime
org.gnome.Platform		system,runtime
org.gnome.Platform		system,runtime
org.gnome.SimpleScan	48.1	system,current
org.gnome.Snapshot	48.0.1	system,current
org.gnome.World.PikaBackup	0.7.4	system,current
org.gtk.Gtk3theme.Breeze	6.4.2	system,runtime
org.gtk.Gtk3theme.adw-gtk3	6.2	system,runtime
org.gtk.Gtk3theme.adw-gtk3-dark	6.2	system,runtime
org.kde.KStyle.Adwaita		system,runtime
org.kde.KStyle.Adwaita		system,runtime
org.kde.KStyle.Adwaita		system,runtime
org.kde.KStyle.Adwaita		system,runtime
org.kde.Platform		system,runtime
org.kde.Platform		system,runtime,eol=We strongly recommend moving to the latest stable version of the Platform and SDK
org.kde.Platform		system,runtime
org.kde.Platform		system,runtime
org.kde.filelight	25.04.3	system,current
org.kde.gwenview	25.04.3	system,current
org.kde.haruna	1.4.0	system,current
org.kde.kcalc	25.04.3	system,current
org.kde.kclock	25.04.3	system,current
org.kde.kdenlive	25.04.3	system,current
org.kde.krita	5.2.9	system,current
org.kde.krita.Codecs		system,runtime
org.kde.okular	25.04.3	system,current
org.keepassxc.KeePassXC	2.7.10	system,current
org.mozilla.firefox	140.0.2	system,current
org.nickvision.tubeconverter	2025.6.0	system,current
org.pipewire.Helvum	0.5.1	system,current
org.tenacityaudio.Tenacity	1.3.4	system,current
org.videolan.VLC	3.0.21	system,current
org.winehq.Wine.gecko		system,runtime
org.winehq.Wine.mono		system,runtime
```

### Extra information or context

I first tried a full restart of my system, which did not resolve the issue. 
I had a custom image set as my lockscreen background (a 1.9MiB JPG) saved in my user folder
I fixed the issue on my end by changing the lockscreen background in the kde settings. I was then able to change it back to the same image and it functioned as expected.

**Comment by Zynax1** [comment]
I also had this issue on bazzite:stable 42.20250708, though I had the default bazzite lock screen background. I also had to change to a different background to fix it.

**Comment by Zynax1** [comment]
Update: it looks like changing the background is only a temporary fix, screen locker has broken again for me. No idea what's causing it. Changing the background no longer fixes the issue at all either.

**Comment by qwahzi** [comment]
Same issue here, and changing the background did not resolve it. Not sure if it matters, but I have 3 monitors and a 9070 XT

**Comment by schoukro** [comment]
Same issue. Using external monitor connected through usb-C hub. Not sure if it happens only with one monitor. Nvidia 4070 so doesn't look like the GPU.

**Comment by Kuah-link** [comment]
Had exactly same issue with GPD Duo - integrated GPU (amd hx370), KDE variant, dual screen laptop.

I tried rollback to 0621 version, and confirm that this issue didn't exist yet

when i re-base it again to 0708, the lockscreen issue occured regardless of swapping wallpaper, theme, colour.

I also tried restart + changing wallpaper and restart again. didn't help.

**Comment by CheckYourFax** [comment]
Will be fixed ASAP. Bear with us guys.

**Comment by seanpatrick1976** [comment]
Same issue here - I rebooted and it worked so I'll just wait for the fix. 

Hardware: 7900xtx + 12600k. Single monitor.

**Comment by lotemon** [comment]
'm also experiencing the same issue on the 0708 build, even with the latest Mesa drivers.

After several tests, I believe the root of the bug is related to an incompatibility between Wayland, the KWin compositor, QtMultimedia, and Vulkan, especially when customizing the Plasma desktop on an immutable system (rpm-ostree).

I'm also noticing unreliable behavior with screen resolutions above 1920x1080 — xrandr fails to apply valid modes, the compositor becomes unstable, and windows are often placed outside the visible area.

    Changing the wallpaper used to work as a temporary workaround, but no longer has any effect.

I suggest looking deeper into critical graphical parameters, particularly around xrandr, the compositor initialization, and what happens when restarting the graphical stack with:

sudo systemctl restart sddm

This command (which restarts the graphical server — X11 or Wayland depending on the backend) doesn’t always restore a usable state when Plasma customizations are active (themes, SDDM styles, wallpapers, desktop effects, etc.), indicating a possible incompatibility or corrupted graphic state.

Thanks to the team for looking into this. Happy to provide logs or assist with further testing if needed.

My current hardware and setup:

    CPU: AMD Ryzen 5 5600GT @ 4.93 GHz

    GPUs: AMD Radeon RX 6600 (discrete) and AMD Radeon Vega Mobile Series (integrated)

    Displays:

        3840x2160 @ 60 Hz on 49" external monitor

        1920x1080 @ 60 Hz on 32" external monitor

    Desktop Environment: KDE Plasma 6.4.1 running on Wayland with KWin

    System: Bazzite 42 (based on Fedora Kinoite), Linux kernel 6.15.4-104.bazzite.fc42.x86_64

    RAM: 14.91 GiB total, ~65% used

    Storage: ext4 and btrfs (read-only) partitions

    Session compositor: KWin (Wayland)

Issues appear regardless of multi-monitor setup and are more pronounced with resolutions above 1920x1080.

**Comment by sihawken** [comment]
I am also getting this issue with my Framework 13 (12th gen Intel) laptop.

This happens with and without an external screen attached.

**Comment by KyleGospo** [comment]
Fixed in yesterday's update.

**Comment by kees2125** [comment]
I'm still encountering this error sometimes after my PC awakens from sleep.
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:86cfdc35deaa4b7fb896c4552300f5d7a096558d0218f678d3278877740dd684
                  Version: 42.20250804 (2025-08-04T05:24:44Z)

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:86cfdc35deaa4b7fb896c4552300f5d7a096558d0218f678d3278877740dd684
                  Version: 42.20250804 (2025-08-04T05:24:44Z)

**Comment by schoukro** [comment]
Yep, re-happening as well....
