### ISSUE TITLE
Yuzu emulator crashes Bazzite OS when launching Legend of Zelda: Breath of the Wild

### ISSUE THREAD

**Issue by ariusxscourger** [ublue-os/bazzite#2987]
### Describe the bug

When launching The Legend of Zelda: Breath of the Wild in Yuzu on Bazzite OS, the system crashes during the emulator's loading screen — the game doesn't even start.

This causes:

Black screen

Lenovo splash screen

Return to the login screen

### What did you expect to happen?

I expected the game to load and run normally. On the same hardware, using Pop!_OS, Yuzu runs this game fine without any crash.

### Output of `rpm-ostree status`

```shell
saqib@bazzite:~$ rpm-ostree status
State: idle
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-gnome:stable
                   Digest: sha256:23c02860f424869463e363a6e96948918c1036b6e6474b0420186cfb1fd31c68
                  Version: 42.20250720 (2025-07-20T07:43:36Z)
          LayeredPackages: dotnet-sdk-8.0 liberation-fonts
            LocalPackages: code-1.102.1-1752598767.el8.x86_64
                           microsoft-edge-beta-139.0.3405.42-1.x86_64

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-gnome:stable
                   Digest: sha256:23c02860f424869463e363a6e96948918c1036b6e6474b0420186cfb1fd31c68
                  Version: 42.20250720 (2025-07-20T07:43:36Z)
          LayeredPackages: dotnet-sdk-8.0 liberation-fonts
            LocalPackages: code-1.102.1-1752598767.el8.x86_64
                           microsoft-edge-beta-139.0.3405.42-1.x86_64
```

### Hardware

saqib@bazzite:~$ cat /sys/devices/virtual/dmi/id/product_name
82TT
saqib@bazzite:~$ lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation Alder Lake-UP3 GT1 [UHD Graphics] (rev 0c)

### Extra information or context

Yuzu installed via Flatpak from Flathub

Game: Legend of Zelda: Breath of the Wild

System crashes before game starts — only at the Yuzu loading screen

Happens every time; reproducible

No issues on Pop!_OS on same machine

**Comment by PVermeer** [comment]
Had the same issue. It's not a Bazzite issue.

When screwing around with configs and firmware this started happening. It think it was fixed with removing the config file (qt-config.ini) and settings thing up again.

**Comment by ariusxscourger** [comment]
> Had the same issue. It's not a Bazzite issue.
> 
> When screwing around with configs and firmware this started happening. It think it was fixed with removing the config file (qt-config.ini) and settings thing up again.

I’ve removed qt-config.ini and let Yuzu recreate it, but the crash still happens. I also tested with the Citron Emulator and see the exact same behavior.
