### ISSUE TITLE
Severe packet loss on r8169 (RTL8125 2.5GbE Controller (rev 05)) network driver for stable branch

### ISSUE THREAD

**Issue by BatStak** [ublue-os/bazzite#3146]
### Describe the bug

Using `ostree-unverified-registry:ghcr.io/ublue-os/bazzite:stable` you will have packet loss when testing https://packetlosstest.com/, up to 20% in some cases.

I switch to the `ostree-unverified-registry:ghcr.io/ublue-os/bazzite:latest` and I have no more packet loss, even if it's the same driver version `r8169`. It seems to be fixed.

Pretty weired because it seems to be the same version (`latest` being basically `stable` on 2 september 2025). Maybe the registry is not yet up to date.

### What did you expect to happen?

Would be nice to release a new stable version soon with this fix because people may drop Bazzite pretty fast with this problem.

### Output of `rpm-ostree status`

```shell
bazzite@bazzite:~$ rpm-ostree status
State: idle
Deployments:
● ostree-unverified-registry:ghcr.io/ublue-os/bazzite:latest
                   Digest: sha256:e26f9399bff1aeb8c819e932c3c160cac1a4fe6638c6efc5a8fe4dd2cfb76404
                  Version: 42.20250901.1 (2025-09-01T05:54:43Z)

  ostree-unverified-registry:ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:e26f9399bff1aeb8c819e932c3c160cac1a4fe6638c6efc5a8fe4dd2cfb76404
                  Version: 42.20250901.1 (2025-09-01T05:54:43Z)
```

### Hardware

bazzite@bazzite:~$ cat /sys/devices/virtual/dmi/id/product_name
Amd Am5

### Extra information or context

CS2 is barely playable with this problem. Any "livecd" version of linux with same hardware shows no issue. I spend some hours to figure it out.

**Comment by BatStak** [comment]
Maybe it's just the registry which is not updated yet for `stable` ?

**Comment by BatStak** [comment]
This is not fixed, packet loss reappears without any update. Same result for `rpm-ostree status`

**Comment by lostdharma** [comment]
I'm experiencing the same. Is this an issue in the kernel? Do you have a link to any bug report?

**Comment by badnetmask** [comment]
Maybe this is related?
https://discussion.fedoraproject.org/t/kernel-6-16-3-causes-intermittent-network-issues/163310

**Comment by lostdharma** [comment]
There's a fix coming in kernel 6.16.4-104: https://github.com/bazzite-org/kernel-bazzite/releases/tag/6.16.4-104

**Comment by BatStak** [comment]
> There's a fix coming in kernel 6.16.4-104: https://github.com/bazzite-org/kernel-bazzite/releases/tag/6.16.4-104

Seems to be only for wifi, I'm on ethernet so I doubt it's this bug (but maybe just a bad naming).

**Comment by lostdharma** [comment]
> > There's a fix coming in kernel 6.16.4-104: https://github.com/bazzite-org/kernel-bazzite/releases/tag/6.16.4-104
> 
> Seems to be only for wifi, I'm on ethernet so I doubt it's this bug (but maybe just a bad naming).

I think it's just an incorrect naming. According to the user reporting at https://bugzilla.kernel.org/show_bug.cgi?id=220484#c18, the patches further down have fixed the issue for them.

**Comment by KyleGospo** [comment]
Should now be fixed in the latest stable release.

**Comment by BatStak** [comment]
I can confirm that it seems to be fixed, I did several tests on https://packetlosstest.com/ and played 1 game with no issue. Will confirm it later after multiple games because I add no issue for some hours before the patch too (weird).

EDIT : seems fixed 2 (i will close the issue after some more games)

EDIT2 : seems fixed for good. I close the issue.

Thanks again. I love Bazzite.

**Comment by ageisen2000** [comment]
I am on 6.17.7-ba20.fc43.x86_64 and I am experiencing constant link up/down messages in my dmesg output. This isn't fixed for me. Is there a different bug to track?

<img width="742" height="1046" alt="Image" src="https://github.com/user-attachments/assets/dbb8d3c8-0392-4749-bb78-2c2e8c8bf0e1" />

I'm on a brand new bazzite install as of yesterday:

DMESG output 

```
[   14.965582] r8169 0000:09:00.0 enp9s0: Link is Down
[   17.317755] Bluetooth: RFCOMM TTY layer initialized
[   17.317761] Bluetooth: RFCOMM socket layer initialized
[   17.317764] Bluetooth: RFCOMM ver 1.11
[   18.404552] r8169 0000:09:00.0 enp9s0: Link is Up - 2.5Gbps/Full - flow control rx/tx
[   18.406153] r8169 0000:09:00.0 enp9s0: Link is Up - 2.5Gbps/Full - flow control rx/tx
[   60.846755] evm: overlay not supported
[   81.297350] r8169 0000:09:00.0 enp9s0: Link is Down
[   84.738702] r8169 0000:09:00.0 enp9s0: Link is Up - 2.5Gbps/Full - flow control rx/tx
[  111.160727] r8169 0000:09:00.0 enp9s0: Link is Down
[  114.603013] r8169 0000:09:00.0 enp9s0: Link is Up - 2.5Gbps/Full - flow control rx/tx
[  141.007337] r8169 0000:09:00.0 enp9s0: Link is Down
[  144.450957] r8169 0000:09:00.0 enp9s0: Link is Up - 2.5Gbps/Full - flow control rx/tx
[  170.837153] r8169 0000:09:00.0 enp9s0: Link is Down
[  174.278598] r8169 0000:09:00.0 enp9s0: Link is Up - 2.5Gbps/Full - flow control rx/tx
[  200.683718] r8169 0000:09:00.0 enp9s0: Link is Down
[  204.168620] r8169 0000:09:00.0 enp9s0: Link is Up - 2.5Gbps/Full - flow control rx/tx
[  230.572209] r8169 0000:09:00.0 enp9s0: Link is Down
[  234.042049] r8169 0000:09:00.0 enp9s0: Link is Up - 2.5Gbps/Full - flow control rx/tx
[  260.444082] r8169 0000:09:00.0 enp9s0: Link is Down
[  263.885148] r8169 0000:09:00.0 enp9s0: Link is Up - 2.5Gbps/Full - flow control rx/tx
[  290.275436] r8169 0000:09:00.0 enp9s0: Link is Down
[  293.817132] r8169 0000:09:00.0 enp9s0: Link is Up - 2.5Gbps/Full - flow control rx/tx
[  320.230967] r8169 0000:09:00.0 enp9s0: Link is Down
[  323.714818] r8169 0000:09:00.0 enp9s0: Link is Up - 2.5Gbps/Full - flow control rx/tx
```
