### ISSUE TITLE
aptX support ?

### ISSUE THREAD

**Issue by qherreros** [ublue-os/bazzite#3387]
Hi ! I just saw that aptX support has been removed. The libfreeaptx package is gone. Is it intentional?
Thanks

**Comment by qherreros** [comment]
I wonder if it could be linked to [that](https://github.com/ublue-os/main/issues/1512).

**Comment by KyleGospo** [comment]
Fixed in next update, thanks

**Comment by DDoS** [comment]
The aptX option is still missing in the sound settings even after the latest update.

**Comment by qherreros** [comment]
I can confirm, libfreeaptx is here but aptX is still missing as an option.
