### ISSUE TITLE
Dead keys not working in ptyxis since F43

### ISSUE THREAD

**Issue by biebel** [ublue-os/bazzite#3394]
### Describe the bug

None of the dead keys are currently working in ptyxis, they get completely ignored. ~  results in a space, `e results in a plain e, ...
This started happening since the F43 update and only in ptyxis

### What did you expect to happen?

Dead keys to function normally

### Session Logs

```shell
Logs from launching ptyxis in extra info
```

### Hardware

Desktop

### Extra information or context

``` 
Oct 31 17:10:11 desktop systemd[2431]: Started dbus-:1.3-org.gnome.Ptyxis@1.service.
Oct 31 17:10:11 desktop ptyxis[52790]: Locale not supported by C library.
                                               Using the fallback 'C' locale.
Oct 31 17:10:11 desktop ptyxis[52790]: Unknown key gtk-modules in /home/biebel/.config/gtk-4.0/settings.ini
Oct 31 17:10:11 desktop /usr/libexec/xdg-desktop-portal[2734]: A backend call failed: No such method 'CreateMonitor' in interface 'org.freedesktop.impl.portal.Inhibit' at object path '/org/freedesktop/portal/desktop' (signature 'ooss')
Oct 31 17:10:11 desktop /usr/libexec/xdg-desktop-portal[2734]: Failed to close session implementation: GDBus.Error:org.freedesktop.DBus.Error.UnknownObject: No such object path '/org/freedesktop/portal/desktop/session/1_391/gtk640377016'
Oct 31 17:10:11 desktop ptyxis[52790]: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
Oct 31 17:10:12 desktop ptyxis[52790]: WARNING: radv is not a conformant Vulkan implementation, testing use only.
Oct 31 17:10:12 desktop systemd[2431]: Started ptyxis-spawn-ad401ac2-9771-42a0-a1b9-23b540f41248.scope - [systemd-run] /usr/bin/bash.
```
```
Deployments:
● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:testing
                   Digest: sha256:d363fe9492e9d10929bda66521eaa96404a2ba7f25ed655e0290c46ea90c114b
                  Version: testing-43.20251029 (2025-10-29T07:29:34Z)
          LayeredPackages: coolercontrol liquidctl
                   Pinned: yes

  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:stable
                   Digest: sha256:86cfdc35deaa4b7fb896c4552300f5d7a096558d0218f678d3278877740dd684
                  Version: 42.20250804 (2025-08-04T05:24:44Z)
          LayeredPackages: coolercontrol liquidctl
                   Pinned: yes

```
Happening for me on belgian keyboard layout. Was happening for someone on the discord with a nordic layout as well.

**Comment by maia-s** [comment]
I have the same issue. Also, keys that require me to hold AltGr, like `{[]}`, also doesn't work, and my distrobox container isn't in the dropdown for that.

Issue seen on `43.20251029 (2025-10-29T18:51:11Z)` update, I had to rollback to `42.20251019 (2025-10-19T16:29:32Z)` which works

```
$ rpm-ostree status
State: idle
Deployments:
  ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia-open:stable
                   Digest: sha256:69cbc671b6f3c1c5a1711f5140b5034e0ef3d1df04e5f6c04c37518abce9126b
                  Version: 43.20251029 (2025-10-29T18:51:11Z)
                     Diff: 2535 upgraded, 6 downgraded, 157 removed, 59 added

● ostree-image-signed:docker://ghcr.io/ublue-os/bazzite-nvidia-open:stable
                   Digest: sha256:5d86b5f6db5361d4c74f4ed2c9503a694502d91e61f872ceb3c93e48503f2401
                  Version: 42.20251019 (2025-10-19T16:29:32Z)
```

**Comment by ZWx4** [comment]
So that's why I couldn't type single and double quotation marks `'"` into the terminal last night? I thought I had lost my mind, that I had imagined being able to do it before. I ended up layering in `konsole` to get around the problem.

**Comment by ZWx4** [comment]
It seems that launching Ptyxis with `GTK_IM_MODULE=ibus` set also fixes it, according to a post [here](https://gitlab.gnome.org/chergert/ptyxis/-/issues/487#note_2586246).

**Comment by HikariKnight** [comment]
This should be fixed in stable now

**Comment by maia-s** [comment]
Dead keys still don't work for me without overriding GTK_IM_MODULE. System update says I'm up to date

**Comment by biebel** [comment]
I'm currently on `testing-43.20251206.1` and dead keys are still not working :/. If there's anything I can do to help fix this, let me know.

**Comment by HikariKnight** [comment]
check if `/usr/bin/kde-ptyxis` has `env GTK_IM_MODULE=ibus /usr/bin/ptyxis`

**Comment by biebel** [comment]
It does:
```
#!/usr/bin/bash
# Shim to handle KDE only supporting -e
# https://bugs.kde.org/show_bug.cgi?id=459616
# We replace all standalone occurrences, but ignore others, e.g. in 'distrobox-enter'
args=()
for arg in ${@}; do
        if [[ "$arg" == -e ]]; then
                args+=("--")
        else
                args+=("$arg")
        fi
done

# Dolphin integration requires --new-window to function properly
if [[ ! "${args[@]}" =~ "--" && ! "${args[@]}" =~ "-h" && ! "${args[@]}" =~ "-x" ]]; then
        env GTK_IM_MODULE=ibus /usr/bin/ptyxis --new-window "${args[@]}"
else
        env GTK_IM_MODULE=ibus /usr/bin/ptyxis "${args[@]}"
fi
```

**Comment by HikariKnight** [comment]
potential fix is now in testing

**Comment by biebel** [comment]
It is fixed for me in testing-43.20251211
Never thought seeing a ~ appear would make me smile that much lol. Thank you!

**Comment by TheGroundZero** [comment]
For those that don´t dare (or don´t know how) to run testing, what's the solution? Wait?

**Comment by biebel** [comment]
Pretty much wait for the next stable release yeah. I've been on testing since whenever the 9070xt was released. It's not much of a risk. Just pin whatever deployment works for you now and rebase to testing if you want.

**Comment by HikariKnight** [comment]
> For those that don´t dare (or don´t know how) to run testing, what's the solution? Wait?

https://docs.bazzite.gg/Installing_and_Managing_Software/Updates_Rollbacks_and_Rebasing/bazzite_rollback_helper/

`brh rebase testing` for short
