### ISSUE TITLE
Can't enable HDR in games as of stable-43.20251102

### ISSUE THREAD

**Issue by gabevt** [ublue-os/bazzite#3430]
### Describe the bug

I can't enable HDR in game. HDR on the desktop seems to work as expected, but any game I launch is in a state where HDR support isn't detected. 
I've confirmed this problem was introduced in version "stable-43.20251102", rebasing with BRH to "stable-43.20251029" restores HDR functionality in all games.

Stuff I tried (on 20251102):
- Running without gamescope
- I tried modifying my gamescope arguments to include the minimum to run with HDR (mainly just the --hdr-enabled flag)
- Several games (Overwatch 2, Doom The Dark Ages, Helldivers 2)
- Toggling HDR in Bazzite settings and in my monitor
- Different proton versions (including regular and latest GE)
- Updating via "ujust update"

Update:
It looks like this is related to the KDE update to 6.5, 
testing-43.20251101.1 -> Doesn't present the problem
testing-43.20251102 -> Does present the problem

### What did you expect to happen?

HDR is detected by games and I can enable it

### Session Logs

```shell
I cleared my logs recently, but these should include me rebasing and launching games across a couple of releases (including 20251102)
https://paste.centos.org/view/2310372a
```

### Hardware

CPU: 5800x3d
GPU: 7900 XTX
RAM: 32 GB
Using KDE

**Comment by gabevt** [comment]
Switching to a GE Proton, removing gamescope from my game's launch arguments and adding 
PROTON_ENABLE_WAYLAND=1 PROTON_ENABLE_HDR=1
Seems to re enable HDR. 

Temporary workaround since it sadly locks me out of gamescope and locks me into GE protons.

**Comment by acardace** [comment]
This seems to be fixed in gamescope with https://github.com/ValveSoftware/gamescope/pull/1999. Bazzite should pick that up to fix this.

**Comment by antheas** [comment]
Fixed.

**Comment by plasmaplasmaplasma** [comment]
I am on 43.20251210.1 and the issue for me is still present.
Running without `gamescope` with GE Proton fixes the problem.
My scopebuddy setup:
`SCB_GAMESCOPE_ARGS="-f --mangoapp --force-grab-cursor"
SCB_AUTO_RES=1
command+=' '
SCB_AUTO_HDR=1
SCB_AUTO_VRR=1`

**Comment by g0nz0li0** [comment]
> I am on 43.20251210.1 and the issue for me is still present. Running without `gamescope` with GE Proton fixes the problem. My scopebuddy setup: `SCB_GAMESCOPE_ARGS="-f --mangoapp --force-grab-cursor" SCB_AUTO_RES=1 command+=' ' SCB_AUTO_HDR=1 SCB_AUTO_VRR=1`

Same. HDR only works with Proton GE running PROTON_ENABLE_WAYLAND=1 PROTON_ENABLE_HDR=1 ENABLE_HDR_WSI=1 %command% 

AMD RX7800 XT

**Comment by plasmaplasmaplasma** [comment]
@antheas Can you reopen the issue?

**Comment by gabevt** [comment]
I've updated my setup to 43.20251210.1 and I'm not seeing the issue, so this new instance may have a different root cause.

**Comment by plasmaplasmaplasma** [comment]
> I've updated my setup to 43.20251210.1 and I'm not seeing the issue, so this new instance may have a different root cause.

Maybe. For me the problem appears with Elden Ring Nightreign. I haven't tried rebasing to the older version in the original comment but when I was playing it months ago I did not have this problem.

- Using `GE-Proton10-25` with Steam, launch options `PROTON_ENABLE_WAYLAND=1 PROTON_ENABLE_HDR=1 ENABLE_HDR_WSI=1 %command%` makes me **able** to toggle On/Off Display -> HDR 
- Using `Proton Experimental` with Steam, launch options `gamescope --hdr-enabled -- %command%` makes me **unable** to toggle On/Off Display -> HDR

**Comment by fritz-fritz** [comment]
I wonder if this might be related to what is causing the issue in #3556

**Comment by plasmaplasmaplasma** [comment]
> I wonder if this might be related to what is causing the issue in [#3556](https://github.com/ublue-os/bazzite/issues/3556)

I tried `ENABLE_GAMESCOPE_WSI=0 gamescope --hdr-enabled -- %command%` but sadly it still doesn't enable HDR.

**Comment by fritz-fritz** [comment]
> > I wonder if this might be related to what is causing the issue in [#3556](https://github.com/ublue-os/bazzite/issues/3556)
> 
> I tried `ENABLE_GAMESCOPE_WSI=0 gamescope --hdr-enabled -- %command%` but sadly it still doesn't enable HDR.

@plasmaplasmaplasma Yes that environmental variable would indeed disable HDR functionality.

The thinking was more along the lines of multiple issues for gamescope occuring around nearly the same release.

FWIW the latest testing I think does resolve the other referenced issue. But in the meantime I'd suggest instead a rebase to a version before this bug affected you.

**Comment by saschanaz** [comment]
Seconding what @plasmaplasmaplasma said. `PROTON_ENABLE_HDR=1 ENABLE_HDR_WSI=1 %command%` with GE-Proton10-27 makes HDR work on Control Ultimate Edition. `PROTON_ENABLE_WAYLAND=1` wasn't a requirement for me though. Proton 10.0-3 doesn't work, it needs to be GE-Proton it seems.

**Comment by jefmes** [comment]
Experiencing this today with Doom: The Dark Ages "HDR is not supported with your hardware" on a Radeon 9070 XT. No luck with Proton Experimental or Proton-GE Latest as of 1/4/2026. I'm going to try PROTON_ENABLE_WAYLAND=1 PROTON_ENABLE_HDR=1 ENABLE_HDR_WSI=1 %command% as mentioned by others here and see if that resolves it.

**Comment by plasmaplasmaplasma** [comment]
I tried rebasing to the version in the op but it says the image may not exist or I do not have access for it (I guess it was deleted since it is more than 90 days old)
```plasma@bazzite:~$ brh rebase stable-43.20251029
Rebasing to: ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:stable-43.20251029
Continue? (Y/n) y
Performing rebase...
Pulling manifest: ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:stable-43.20251029
error: Preparing import: Fetching manifest: failed to invoke method OpenImage: reading manifest stable-43.20251029 in ghcr.io/ublue-os/bazzite: manifest unknown
Rebase failed. Image may not exist or be accessible.
```
Guess we are gonna be stuck without HDR for a while...

**Comment by schildbach** [comment]
I've tried Bazzite yesterday and in both Control and Alan Wake (remastered) it wasn't possible to enable HDR.

I'm using an HDR-capable DisplayPort 1.4 monitor and the HDR toggle in the Gnome display setting works – I set it to enabled.

**Comment by saschanaz** [comment]
> I've tried Bazzite yesterday and in both Control and Alan Wake (remastered) it wasn't possible to enable HDR.
> 
> I'm using an HDR-capable DisplayPort 1.4 monitor and the HDR toggle in the Gnome display setting works – I set it to enabled.

You mean even with the PROTON variables?

**Comment by schildbach** [comment]
> You mean even with the PROTON variables?

Well, I now learned you have to install "Proton GE" via "ProtonPlus" in order to use the above variables. So yes, it now works with the PROTON variables at least in a couple of games. I have yet to find a solution for Epic Store games (ProtonPlus doesn't support Heroic Launcher).

The Proton GE update also fixed my surround sound issues in at least one game. I wonder why Proton GE isn't at least already installed by default, and maybe even used by default rather than the experimental Proton which apparently causes many incompatibilities?

**Comment by plasmaplasmaplasma** [comment]
I tried again today with Elden Ring Nightreign, using Proton Experimental with Steam, with scopebuddy set with SCB_AUTO_HDR and HDR works now.

**Comment by rsmarples** [comment]
Cannot enable HDR in Pragmata with proton experimental.
Using Proton-GE I can but I then loose controller support.

**Comment by xiansr015** [comment]
> I tried again today with Elden Ring Nightreign, using Proton Experimental with Steam, with scopebuddy set with SCB_AUTO_HDR and HDR works now.

Thanks for your comment.

I use this setting to run resident evil 7 in 1440p HDR on AND 240hz Refresh Rate

Add the following lines in `~/.config/scopebuddy/scb.conf`:
```bash
export XDG_DEFAULT_LAYOUT=no
SCB_AUTO_HDR=1
SCB_GAMESCOPE_ARGS="-f -w 2560 -h 1440 -W 2560 -H 1440 -r 240"
```
And set the game's proton to Proton Experimental, too
And with this startup option `scb -- %command% --launcher-skip`
