### ISSUE TITLE
How to apply color profiles?

### ISSUE THREAD

**Issue by burakcan** [ublue-os/bazzite#370]
In the readme the preset color profiles are mentioned and they are visible in the color management section in KDE system settings. But I couldn’t find how to apply them and they’re not mentioned in the docs? How do we do it? Maybe we can add a section about it to the docs.

**Comment by KyleGospo** [comment]
KDE's colord package wasn't installed, should be fixed in the latest builds.

**Comment by Xuerian** [comment]
I see a change matching this issue, however it explicitly excludes nvidia: https://github.com/ublue-os/bazzite/commit/554849bc811fbbba98ac2ce9e4cf04f1ac8867d4

How should we go about them on nvidia cards?

**Comment by Xuerian** [comment]
Appropriate to say that this isn't really a Bazzite problem, it's a Wayland/Plasma 5 problem - and ColorD doesn't solve that.

I've since read that Plasma 6 will properly support icc profiles.

Hopefully this will be resolve with 6, along with direct color adjustments we don't currently have (on desktop) with Plasma/Wayland.
