### ISSUE TITLE
USB keyboard and mouse don't work on Steam deck 

### ISSUE THREAD

**Issue by benjamin7490** [ublue-os/bazzite#532]
Just after the installation of bazzite 39 my keyboard and my mouse don't work

**Comment by DarkenLX** [comment]
Can confirm..deck will lockup/freeze after a short period of pressing keys on any usb keyboard connected so not brand specific keyboards cause it all seem to.

**Comment by Gethec** [comment]
I've encountered this as well.  An update was installed this morning, and I I found myself unable to use a keyboard to enter my drive encryption password.  I reformatted the device and the USB and Ethernet from the dock work during that process, but once I boot into the desktop for the first time, the Ethernet connection is no longer available and USB no longer works.  I've tested this with multiple docks and adapters, and encounter the same issue on all.

**Comment by FlyingEclair** [comment]
Same situation.

**Comment by JaxiiRuff** [comment]
Yep same here. Docked experience is now broken for whatever reason.

**Comment by midnightgospel** [comment]
Can confirm same issue here. Using a Logitech USB mouse and keyboard combo wireless. Everything is fine until I press a key, then the system locks up in both game mode and desktop mode

**Comment by DarkenLX** [comment]
> Yep same here. Docked experience is now broken for whatever reason.
> 
> Edit: Switching to unstable fixed these issues for me.

Unstable version of what?

**Comment by nicknamenamenick** [comment]
> > Yep same here. Docked experience is now broken for whatever reason.
> > Edit: Switching to unstable fixed these issues for me.
> 
> Unstable version of what?

The unstable branch of Bazzite:

`rpm-ostree rebase ostree-image-signed:docker://ghcr.io/ublue-os/bazzite:unstable` (or `...bazzite-deck:unstable` for deck version or whatever image you're using.)

Unstable is exactly what it sounds like though, it's unstable.  The good news is that most likely the fix is already there, but it's not in the "`:latest`" (stable) channel yet.

**Comment by KyleGospo** [comment]
This should be fixed as of the latest update, thank you all for the reports.

**Comment by JaxiiRuff** [comment]
> This should be fixed as of the latest update, thank you all for the reports.

Okay well this is still a problem except its now on both latest and unstable in my experience.

**Comment by midnightgospel** [comment]
Just tested my deck with the Dell dock I have at work that was working on Friday, keyboard and mouse are dead. So it was an update I received towards the end of the week. Also my Logitech keyboard and mouse are still dead as well.

**Comment by benjamin7490** [comment]
I will try later if my keyboard and mouse have the same problem

**Comment by midnightgospel** [comment]
I will add, I am using Logitech devices at work as well. My keyboard at work at the moment will light up when the Deck is plugged in, but the numlock doesn't transition the light on the keyboard. Nor does caps lock. I have a razor keyboard I can test tonight to see if it works. But as of right now, wired and wireless Logitech devices do nothing on my Deck.

**Comment by DarkenLX** [comment]
I just use a generic usb keyboard its acer branded but theres nothing special about it or anything doesn't require drivers. And it didn't work either.

**Comment by Gethec** [comment]
I've tested with both a Razer and Logitech keyboard, an Anker dock as well as the official Steam one, and a simple USB A-to-C adapter, and none of them are registered in the OS.

**Comment by countrymater** [comment]
I have same issue. I tried resetting the usb PD via pushing ... and - and that did not work. I have unplugged and pluged in many variation to no avail

**Comment by Jarmo81987** [comment]
Works with USB XHCI mode

**Comment by Gethec** [comment]
> Works with USB XHCI mode

Confirmed, was just able to enter encryption key, and Ethernet is working on desktop.

**Comment by KyleGospo** [comment]
> Works with USB XHCI mode

That explains the discrepancy in testing, DRD also prevents booting from USB drives.

**Comment by countrymater** [comment]
confirmed working for me too with xhci

**Comment by DarkenLX** [comment]
> > Works with USB XHCI mode
> 
> That explains the discrepancy in testing, DRD also prevents booting from USB drives.

Is DRD the default setting in bios?

**Comment by Gethec** [comment]
It is.  I hadn't heard of DRD before, but it appears to be an option to allow the Deck to be connected to another computer as a mass storage device.  Since that's not a default behavior of the Deck I'm not terribly worried about changing it, though I _would_ be interested in hearing if there's additional use cases for the setting.

**Comment by midnightgospel** [comment]
Switching to XHCI mode has fixed my dock at work 👍🏼

Now just to test my stuff at home

**Comment by KyleGospo** [comment]
> > > Works with USB XHCI mode
> > 
> > That explains the discrepancy in testing, DRD also prevents booting from USB drives.
> 
> Is DRD the default setting in bios? As i never touched mine and i always have been able to boot from USB.

XHCI is the default, most people would have DRD on due to previous use of the DeckMTP decky plugin requiring it.

**Comment by midnightgospel** [comment]
> > > > Works with USB XHCI mode
> > > 
> > > 
> > > That explains the discrepancy in testing, DRD also prevents booting from USB drives.
> > 
> > 
> > Is DRD the default setting in bios? As i never touched mine and i always have been able to boot from USB.
> 
> XHCI is the default, most people would have DRD on due to previous use of the DeckMTP decky plugin requiring it.

Yup I now remember enabling this a long time ago. That's why I forgot about it. Well I guess the issue is kinda fixed then. Minus the fact that the DRD is now broken?

**Comment by KyleGospo** [comment]
> > > > > Works with USB XHCI mode
> > > > 
> > > > 
> > > > That explains the discrepancy in testing, DRD also prevents booting from USB drives.
> > > 
> > > 
> > > Is DRD the default setting in bios? As i never touched mine and i always have been able to boot from USB.
> > 
> > XHCI is the default, most people would have DRD on due to previous use of the DeckMTP decky plugin requiring it.
> 
> Yup I now remember enabling this a long time ago. That's why I forgot about it. Well I guess the issue is kinda fixed then. Minus the fact that the DRD is now broken? 

Yep, I'll look into that next.

**Comment by Gethec** [comment]
> > > > Works with USB XHCI mode
> > > 
> > > 
> > > That explains the discrepancy in testing, DRD also prevents booting from USB drives.
> > 
> > 
> > Is DRD the default setting in bios? As i never touched mine and i always have been able to boot from USB.
> 
> XHCI is the default, most people would have DRD on due to previous use of the DeckMTP decky plugin requiring it.

Very interesting.  I never enabled DeckMTP or adjusted this setting, but had DRD on.  Could it possibly have been a default setting on an earlier version of the hardware or BIOS?

**Comment by DarkenLX** [comment]
> > > > > Works with USB XHCI mode
> > > > 
> > > > 
> > > > That explains the discrepancy in testing, DRD also prevents booting from USB drives.
> > > 
> > > 
> > > Is DRD the default setting in bios? As i never touched mine and i always have been able to boot from USB.
> > 
> > 
> > XHCI is the default, most people would have DRD on due to previous use of the DeckMTP decky plugin requiring it.
> 
> Very interesting. I never enabled DeckMTP or adjusted this setting, but had DRD on. Could it possibly have been a default setting on an earlier version of the hardware or BIOS?

Same here and i know mine is DRD but i never used deckmtp or had any reason to change it..🤔

**Comment by RodoMa92** [comment]
Yeah, found this with using the hard path, one part of the driver is missing from Fedora, see [here](https://gitlab.freedesktop.org/drm/amd/-/issues/2984). It should be fixed shortly, and I can confirm that XHCI is quirky on the latest kernel since a commit from Valve impeded the XHCI stack to load by default on it. It should be fixed shortly, as soon as @KyleGospo complete to include dwc3 in it's entirety.

**Comment by endrift** [comment]
New fc39 kernel build with the dwc3 driver is available: https://bodhi.fedoraproject.org/updates/FEDORA-2023-9d54a271e2

**Comment by KyleGospo** [comment]
Latest builds on `:testing` should fix this.

**Comment by KyleGospo** [comment]
Fixed in next update!
