### ISSUE TITLE
First page of Bazzite Portal Not Working after Install

### ISSUE THREAD

**Issue by brandflake11** [ublue-os/bazzite#552]
Hello all,
I am here to report a bug that I saw. I just installed bazzite-deck-gnome on its own separate drive on my all amd desktop and one thing that is not working right is the first page of the bazzite portal program. No matter what I select to install on the first page, it doesn't seem to install what I want and if I click the console button, I get this error:
```
error: Unknown start of token:
    |
165 |   distrobox-create --nvidia --image quay.io/toolbx-images/centos-toolbox:latest -n centos -Y
    |                    ^
error: Unknown start of token:
    |
165 |   distrobox-create --nvidia --image quay.io/toolbx-images/centos-toolbox:latest -n centos -Y
    |                    ^
error: Unknown start of token:
    | 
165 |   distrobox-create --nvidia --image quay.io/toolbx-images/centos-toolbox:latest -n centos -Y
|
error: Unknown start of token:
    |
165 |   distrobox-create --nvidia --image quay.io/toolbx-images/centos-toolbox:latest -n centos -Y 
    |                    ^
Installation Complete!
```

The other pages of the application seem to work. 

Hopefully it is okay to report here, let me know if you need any more information.

**Comment by KyleGospo** [comment]
Thanks for the report, this was an issue from upstream and is now resolved. Please `rpm-ostree update` in your terminal or update from gamemode to fix this issue, you may then open bazzite portal again to install anything missed your first go through.

**Comment by brandflake11** [comment]
Hello, I'm still getting this error after the rpm-ostree update. I also get the same error whenever I try to use just. In my .justfile I have:
`
!include /usr/share/ublue-os/justfile`

**Comment by brandflake11** [comment]
Nevermind about this error now, the update did fix it. I was just loading the older ostree (user error!).
