### ISSUE TITLE
[Regression][SteamDeckOLED][bazzite-deck-gnome:latest] Bluetooth stopped working completely and is root cause for issue of auto-resume from suspend

### ISSUE THREAD

**Issue by Raltay** [ublue-os/bazzite#950]
### Describe the bug

Description
-----------------
Bluetooth is broken on Steam Deck OLED on bazzite-deck-gnome:latest after version 39.20240328.0 (this is the last version when it worked correctly).

It doesn't work at all - cannot connect to paired devices (fails immediately upon selection), doesn't detect new/unpaired devices. I'm not sure if Bluetooth on/off switch even works at all.

This issue also is most probably (from my superficial log analysis) root cause of device's "'auto-resume' after suspend" issue. When device is suspended (either via power button or via menu option), it 'auto-resumes' after a few seconds pass. It happens every time, regardless of whether Bluetooth switch is ON or OFF. Relevant logs can be found in journalctl_after-suspend.txt file.

Both of those issues occur in both gamescope and desktop mode.

Last version of bazzite-deck-gnome where neither of these issues occured was 39.20240328.0. After updating from it, both of those issues started occurring. 

Captured logs
--------------------
[dmesg_after-suspend.txt](https://github.com/ublue-os/bazzite/files/14893739/dmesg_after-suspend.txt)
[dmesg_before-suspend.txt](https://github.com/ublue-os/bazzite/files/14893740/dmesg_before-suspend.txt)
[journalctl_after-suspend.txt](https://github.com/ublue-os/bazzite/files/14893741/journalctl_after-suspend.txt)
[journalctl_before-suspend.txt](https://github.com/ublue-os/bazzite/files/14893742/journalctl_before-suspend.txt)
[journalctl-bluetooth_after-suspend.txt](https://github.com/ublue-os/bazzite/files/14893743/journalctl-bluetooth_after-suspend.txt)
[journalctl-bluetooth_before-suspend.txt](https://github.com/ublue-os/bazzite/files/14893744/journalctl-bluetooth_before-suspend.txt)
[lshw_after-suspend.txt](https://github.com/ublue-os/bazzite/files/14893745/lshw_after-suspend.txt)
[lshw_before-suspend.txt](https://github.com/ublue-os/bazzite/files/14893746/lshw_before-suspend.txt)
[lspci_after-suspend.txt](https://github.com/ublue-os/bazzite/files/14893747/lspci_after-suspend.txt)
[lspci_before-suspend.txt](https://github.com/ublue-os/bazzite/files/14893748/lspci_before-suspend.txt)
[lsusb_after-suspend.txt](https://github.com/ublue-os/bazzite/files/14893749/lsusb_after-suspend.txt)
[lsusb_before-suspend.txt](https://github.com/ublue-os/bazzite/files/14893750/lsusb_before-suspend.txt)

### What did you expect to happen?

I expected Bluetooth to continue to work properly (and not cause suspend issue) like in 39.20240328.0.

**Comment by its-Jassie** [comment]
Can confirm I also have this issue on my SteamDeck OLED. Rebasing to 39.20240328.0 and sleep / bluetooth is functional now

**Comment by RodoMa92** [comment]
Yeah, that's a Qualcomm driver regression:
```
[  457.706090] Bluetooth: hci0: SSR or FW download time out
[  457.706106] hci_uart_qca serial0-0: PM: dpm_run_callback(): acpi_subsys_suspend+0x0/0x60 returns -110
[  457.706126] hci_uart_qca serial0-0: PM: failed to suspend: error -110
```
It's probably worth to open a bluetooth regression issue on the bugzilla kernel repo.

**Comment by telorand** [comment]
Also having the exact same issue with the same symptoms. Had to rebase to `-gnome:39-20240328.0` to fix Bluetooth and sleep.

Hopefully Qualcomm or whoever works on that driver gets this solved quickly.

**Comment by KyleGospo** [comment]
Fixed on latest testing build, we are working on some unrelated sleep bugs and then will get this kernel to stable.

**Comment by Raltay** [comment]
I rebased back to `bazzite-deck-gnome:stable` on my Steam Deck OLED and I can confirm that the issue is fixed on `39-20240414`.

Thank you for fast response and have a nice day 🙂

**Comment by telorand** [comment]
Possibly still occurring.
https://github.com/ublue-os/bazzite/issues/960#issuecomment-2063993939

**Comment by sstendahl** [comment]
Hi,

I just tried with my Steam Deck OLED 1TB model, and the issue described here (non-functioning bluetooth and auto-resume from suspend) is definitely still present in `bazzite-deck-gnome:stable` in `39-20240419`. I tried to rebase to `bazzite-deck-gnome:testing`, but the issue is there as well, on top of WiFi not working in `testing`.

I rebased back to `20240328` as @Raltay suggested in the opening post, and it works fine from there. So it's definitely a regression indeed, and it does seem to be in the latest stable. Have not tried `20240414`, it could be possible that the regression slipped back in somehow.

**Comment by Raltay** [comment]
'bazzite-deck-gnome:stable in 39-20240419'

I can confirm that this also started happening again on my OLED with the above version.

Reopening ticket.

**Comment by telorand** [comment]
Doesn't seem to be occurring on the latest upgrade to `40-20240427`. There's still outstanding BT issues with controllers, but Sleep/Suspend and audio devices seem to be working correctly. Additionally, I've noticed that audio doesn't seem to be bugged when switching between Desktop Mode to Game Mode.

**Comment by sstendahl** [comment]
Yeah this got resolved for me as well a while ago. I think the issue can be closed.
